// @generated by tools/extract/extract.py — bodies copied verbatim from index.html

  function todayISO() {
    const d = new Date();
    d.setMinutes(d.getMinutes() - d.getTimezoneOffset());
    return d.toISOString().slice(0, 10);
  }

export { todayISO };
