// @generated by tools/extract/extract.py — bodies copied verbatim from index.html

  // Sept 6 2026, Jimmy: "no other account, i mean other email, can log in on
  // the same phone number" — trainer phone was made required at signup (to
  // match Whish payments), but nothing stopped two different email accounts
  // from using the same number. Digits-only comparison so "03 123 456",
  // "03-123-456", and "03123456" are correctly treated as the same number
  // instead of quietly sailing past a naive string match. Used at all three
  // places a trainer's phone gets written: self-signup, the manager editing
  // a trainer in the Trainers tab, and a trainer editing their own "My
  // Profile". Only 17 trainers on this platform, so fetching every phone and
  // comparing client-side is simpler and plenty fast — no need for a DB
  // migration just for this.
  function normalizePhoneDigits(v) {
    return (v || "").replace(/\D/g, "");
  }

export { normalizePhoneDigits };
