// @generated by tools/extract/extract.py — bodies copied verbatim from index.html
import { hourLabel12 } from "../../domain/group3.js";
import { e } from "../../shared/react.js";
import { styles } from "../../shared/theme.js";
import { Icon } from "../../shared/ui/Icon.js";
import { SessionRow } from "./group1.js";

  function DayTimeline({ daySessions, onSendEmail, onDelete, onEdit, onViewClient, sendingId, sendingChannel, past, canPickTrainer, trainerNameById, isToday, onQuickAdd }) {
    // Sept 13 2026, Jimmy: "more interactive...easy for trainers to use" —
    // the real current hour (today's timeline only) gets a highlighted
    // label + pulsing dot, same idea as a live calendar app's "now" line,
    // so a trainer glancing at today's rota can find "right now" instantly.
    const nowHour = isToday ? new Date().getHours() : -1;
    const byHour = {};
    const other = [];
    daySessions.forEach((s) => {
      const h = s.time ? parseInt(s.time.split(":")[0], 10) : NaN;
      if (Number.isFinite(h) && h >= 0 && h <= 23) (byHour[h] = byHour[h] || []).push(s);
      else other.push(s);
    });
    // Sept 10 2026 fix: a session with a genuine, saved time before 6 AM or
    // after 10 PM (e.g. a 5 AM session) used to fall into the "No time set"
    // bucket below just because it was outside the typical gym-hours
    // display window — which reads as "the app ignored the time I entered."
    // The base window stays 6 AM-10 PM for the common case, but any hour
    // that genuinely has a session gets its own row too, so a real time is
    // never mislabeled as no time at all. "No time set" is now strictly for
    // sessions with no time value saved.
    const baseHours = [];
    for (let h = 6; h <= 22; h++) baseHours.push(h);
    const extraHours = Object.keys(byHour).map(Number).filter((h) => h < 6 || h > 22);
    const HOURS = [...baseHours, ...extraHours].sort((a, b) => a - b);
    function rowFor(s) {
      return e(SessionRow, {
        key: s.id, session: s, onSendEmail, onDelete, onEdit, onViewClient,
        sendingChannel: sendingId === s.id ? sendingChannel : null, past,
        trainerName: canPickTrainer ? (trainerNameById[s.trainerId] || "Unassigned") : null
      });
    }
    return e("div", { style: styles.timelineWrap },
      HOURS.map((h) => {
        const items = byHour[h] || [];
        const isNow = h === nowHour;
        return e("div", { key: h, style: styles.timelineRow },
          e("div", { style: styles.timelineHourCol },
            isNow && e("span", { style: styles.timelineNowDot }),
            e("span", { style: { ...styles.timelineHourLabel, ...(isNow ? styles.timelineHourLabelNow : {}) } }, hourLabel12(h))
          ),
          e("div", { style: styles.timelineBody },
            items.length === 0
              ? (onQuickAdd
                  ? e("button", {
                      type: "button", className: "jfRotaSlot", style: styles.timelineSlot, onClick: () => onQuickAdd(h),
                      "aria-label": `Add a session at ${hourLabel12(h)}`
                    }, e(Icon, { name: "plus", size: 11 }), "Tap to add a session")
                  : e("div", { style: styles.timelineEmptyLine }))
              : e("div", { style: { display: "flex", flexDirection: "column", gap: 8 } }, items.map(rowFor))
          )
        );
      }),
      other.length > 0 && e("div", { style: { marginTop: 14 } },
        e("div", { style: styles.timelineOtherHeading }, "No time set"),
        e("div", { style: { display: "flex", flexDirection: "column", gap: 8 } }, other.map(rowFor))
      )
    );
  }

export { DayTimeline };
