// @generated by tools/extract/extract.py — bodies copied verbatim from index.html
import { shiftDateISO } from "../../domain/group3.js";
import { EMAILJS_READY, EMAILJS_SERVICE_ID, EMAILJS_TEMPLATE_ID } from "../../platform/email.js";
import { sb } from "../../platform/supabase.js";
import { todayISO } from "../../shared/lib/dates.js";
import { fmtDateFull } from "../../shared/lib/format.js";
import { e } from "../../shared/react.js";
import { C, styles } from "../../shared/theme.js";
import { Icon } from "../../shared/ui/Icon.js";
import { ClientPicker, ConfirmDialog } from "../../shared/ui/group1.js";
import { VoiceMicButton } from "../../shared/widgets/VoiceMicButton.js";
import { DayTimeline } from "./DayTimeline.js";
import { CalendarMonth } from "./group1.js";
import React, { useEffect, useMemo, useRef, useState } from "react";

  function SessionsPanel({ trainerId = null, canPickTrainer = false, trainers = [], clientOptions = [], onViewClient = null }) {
    // Sept 10 2026, Jimmy: "i want when to press the edit button to take me
    // back to the place where im editing" — the form sits above the
    // calendar/timeline, so tapping Edit on a session further down pre-fills
    // it but leaves it off-screen with no indication anything happened.
    // handleStartEdit below scrolls this into view.
    const formRef = useRef(null);
    const [sessions, setSessions] = useState([]);
    const [loaded, setLoaded] = useState(false);
    const [name, setName] = useState("");
    const [email, setEmail] = useState("");
    // Sept 18 2026: which real client account (if any) this session is
    // linked to. clientId is the source of truth once set — name/email
    // still get filled in alongside it (for display, and so the existing
    // email-reminder flow keeps working unchanged) but they're no longer
    // what a session gets matched back to elsewhere in the app.
    // manualEntry: true only when scheduling someone not yet a real client
    // (a walk-in/prospect) — reveals the old free-typed name/email fields
    // instead of the picker, and clientId stays null for that session.
    const [clientId, setClientId] = useState(null);
    const [manualEntry, setManualEntry] = useState(false);
    // Sept 18 2026: session cards already display a phone number when one's
    // on file, but the form itself had no way to actually enter one — any
    // phone shown today is a leftover from before that gap. Real field now.
    const [phone, setPhone] = useState("");
    const [date, setDate] = useState(todayISO());
    const [time, setTime] = useState("09:00");
    const [note, setNote] = useState("");
    const [formTrainerId, setFormTrainerId] = useState("");
    // Sept 10 2026: null while adding a new session; the session's id while
    // editing an existing one — same form, just switches what Save does.
    const [editingId, setEditingId] = useState(null);
    const [saving, setSaving] = useState(false);
    const [sendingId, setSendingId] = useState(null);
    const [sendingChannel, setSendingChannel] = useState(null);
    const [error, setError] = useState("");
    // Sept 18 2026: the trash icon used to delete a session the instant it
    // was tapped — every other delete in the app asks first. confirmDelete
    // holds the session being confirmed (or null); deletingSession is just
    // for the button's "Deleting…" state.
    const [confirmDelete, setConfirmDelete] = useState(null);
    const [deletingSession, setDeletingSession] = useState(false);
    // Sept 18 2026: scheduling a date before today isn't blocked outright —
    // backfilling a session that already happened is a real, legitimate use
    // — but it also isn't warned about at all right now, so a fat-fingered
    // date silently books into the past with zero signal. pastDateConfirmed
    // tracks whether the trainer has already clicked past the warning for
    // whatever date is currently in the field.
    const [pastDateConfirmed, setPastDateConfirmed] = useState(false);
    // Sept 18 2026 inspection fix: same soft-warning pattern as
    // pastDateConfirmed above, for the class of bug it is — two sessions
    // could be booked fully overlapping for the same trainer with zero
    // warning at all. Same shape as pastDateConfirmed: tracks whether the
    // trainer already clicked past the warning for whatever
    // trainer+date+time is currently in the form.
    const [conflictConfirmed, setConflictConfirmed] = useState(false);
    const today0 = new Date();
    const [calYear, setCalYear] = useState(today0.getFullYear());
    const [calMonth, setCalMonth] = useState(today0.getMonth());
    const [selectedDate, setSelectedDate] = useState(todayISO());

    function goPrevMonth() {
      if (calMonth === 0) { setCalMonth(11); setCalYear((y) => y - 1); } else { setCalMonth((m) => m - 1); }
    }
    function goNextMonth() {
      if (calMonth === 11) { setCalMonth(0); setCalYear((y) => y + 1); } else { setCalMonth((m) => m + 1); }
    }
    function goToDate(iso) {
      setSelectedDate(iso);
      const d = new Date(iso + "T00:00:00");
      setCalYear(d.getFullYear());
      setCalMonth(d.getMonth());
    }
    function goPrevDay() { goToDate(shiftDateISO(selectedDate, -1)); }
    function goNextDay() { goToDate(shiftDateISO(selectedDate, 1)); }

    const trainerNameById = useMemo(() => {
      const map = {};
      trainers.forEach((t) => { map[t.id] = t.name; });
      return map;
    }, [trainers]);

    // Sept 10 2026, Jimmy: "i want an option when i select email section to
    // be able to see all emails of my clients and choose... like client
    // name" — the Client name field already picks from a known-client
    // datalist; the Email field only ever took free-typed text. Same
    // pattern now on Email too, plus picking either field auto-fills the
    // other from the matching client (only when that other field is still
    // blank, so it never clobbers something already typed on purpose).
    const emailByName = useMemo(() => {
      const map = {};
      clientOptions.forEach((c) => { if (c.email) map[c.name] = c.email; });
      return map;
    }, [clientOptions]);
    const nameByEmail = useMemo(() => {
      const map = {};
      clientOptions.forEach((c) => { if (c.email) map[c.email] = c.name; });
      return map;
    }, [clientOptions]);
    const clientEmails = useMemo(() => Array.from(new Set(clientOptions.map((c) => c.email).filter(Boolean))), [clientOptions]);
    function handleNameChange(v) {
      setName(v);
      if (!email && emailByName[v]) setEmail(emailByName[v]);
    }
    function handleEmailChange(v) {
      setEmail(v);
      if (!name && nameByEmail[v]) setName(nameByEmail[v]);
    }

    useEffect(() => {
      if (!sb) { setLoaded(true); return; }
      let q = sb.from("scheduled_sessions").select("*").order("session_date", { ascending: true });
      if (trainerId) q = q.eq("trainer_id", trainerId);
      q.then(({ data, error: err }) => {
        if (!err && data) {
          setSessions(data.map((r) => ({ id: r.id, name: r.client_name, phone: r.client_phone, email: r.client_email, clientId: r.client_id || null, date: r.session_date, time: r.session_time, note: r.note, waSentAt: r.reminder_sent_at, emailSentAt: r.email_reminder_sent_at, trainerId: r.trainer_id })));
        }
        setLoaded(true);
      });
    }, []);

    async function handleSchedule() {
      if (!manualEntry && !clientId) {
        setError("Pick a client from the list, or switch to entering details manually.");
        return;
      }
      if (!name.trim() || !date) {
        setError("Add a client name and a date.");
        return;
      }
      // Sept 18 2026: soft warning, not a hard block — backfilling a session
      // that already happened is a real, legitimate use of this form. But a
      // date that silently lands in the past (a fat-fingered day/month) got
      // zero signal before. First tap on an unconfirmed past date just shows
      // this and stops; tapping the same button again goes through.
      if (date < todayISO() && !pastDateConfirmed) {
        setPastDateConfirmed(true);
        setError(`${fmtDateFull(date)} is in the past — tap "${editingId ? "Save changes" : "Schedule session"}" again to confirm, or pick a different date.`);
        return;
      }
      const assignedTrainerId = canPickTrainer ? (formTrainerId || null) : trainerId;
      // Sept 18 2026 inspection fix: same soft-warning shape as the
      // past-date check above — nothing in this form checked for a
      // trainer already having a session at the same date+time, so two
      // sessions could be booked fully overlapping with zero warning. Only
      // checks exact date+time matches (there's no session-duration field
      // in this schema to detect a partial overlap), and skips the
      // session's own row when editing it in place.
      if (assignedTrainerId && time) {
        const conflict = sessions.find((s) => s.id !== editingId && s.trainerId === assignedTrainerId && s.date === date && s.time === time);
        if (conflict && !conflictConfirmed) {
          setConflictConfirmed(true);
          const trainerLabel = canPickTrainer ? (trainerNameById[assignedTrainerId] || "This trainer") : "You";
          setError(`${trainerLabel} already ${canPickTrainer ? "has" : "have"} a session with ${conflict.name} booked at ${time} on ${fmtDateFull(date)} — tap "${editingId ? "Save changes" : "Schedule session"}" again to double-book anyway, or change the time.`);
          return;
        }
      }
      if (!sb) { setError("Backend not configured yet."); return; }
      // Sept 19 2026 inspection fix: the conflict check above only ever
      // looked at `sessions`, a snapshot loaded once when this screen
      // opened — two people scheduling the same trainer+slot around the
      // same time, each from their own tab/device, could both pass it
      // before either save lands, since neither one's in-flight insert
      // shows up in the other's local snapshot. This re-checks straight
      // against the database right before actually saving, so a slot
      // that got taken after this screen loaded is still caught. Not
      // foldable into the soft-warning above (which only re-runs on a
      // second tap) — this is the last moment before the write, so it's
      // a hard stop rather than another "tap again to override."
      if (assignedTrainerId && time) {
        const { data: freshConflicts, error: conflictCheckErr } = await sb
          .from("scheduled_sessions")
          .select("id, client_name")
          .eq("trainer_id", assignedTrainerId)
          .eq("session_date", date)
          .eq("session_time", time);
        if (!conflictCheckErr && freshConflicts) {
          const freshConflict = freshConflicts.find((r) => r.id !== editingId);
          if (freshConflict) {
            const trainerLabel = canPickTrainer ? (trainerNameById[assignedTrainerId] || "This trainer") : "You";
            setError(`${trainerLabel} already ${canPickTrainer ? "has" : "have"} a session with ${freshConflict.client_name} booked at ${time} on ${fmtDateFull(date)} now — someone just took this slot. Pick a different time.`);
            return;
          }
        }
      }
      setSaving(true);
      const payload = { client_name: name.trim(), client_email: email.trim() || null, client_phone: phone.trim() || null, client_id: clientId || null, session_date: date, session_time: time || null, note: note.trim() || null, trainer_id: assignedTrainerId };
      // Sept 10 2026: same form now also handles saving an edit to an
      // existing session (editingId set by handleStartEdit below) instead
      // of only ever inserting a new one.
      if (editingId) {
        const { data, error: err } = await sb.from("scheduled_sessions").update(payload).eq("id", editingId).select();
        setSaving(false);
        if (err || !data) { setError("Couldn't save those changes. Try again."); return; }
        const row = data[0];
        const mapped = { id: row.id, name: row.client_name, phone: row.client_phone, email: row.client_email, clientId: row.client_id || null, date: row.session_date, time: row.session_time, note: row.note, waSentAt: row.reminder_sent_at, emailSentAt: row.email_reminder_sent_at, trainerId: row.trainer_id };
        setSessions((prev) => prev.map((s) => (s.id === editingId ? mapped : s)).sort((a, b) => ((a.date + (a.time || "")) < (b.date + (b.time || "")) ? -1 : 1)));
        handleCancelEdit();
        return;
      }
      const { data, error: err } = await sb.from("scheduled_sessions").insert([payload]).select();
      setSaving(false);
      if (err || !data) { setError("Couldn't schedule that session. Check the scheduled_sessions table has a client_email column (see setup guide)."); return; }
      const row = data[0];
      const mapped = { id: row.id, name: row.client_name, phone: row.client_phone, email: row.client_email, clientId: row.client_id || null, date: row.session_date, time: row.session_time, note: row.note, emailSentAt: row.email_reminder_sent_at, trainerId: row.trainer_id };
      setSessions((prev) => [...prev, mapped].sort((a, b) => ((a.date + (a.time || "")) < (b.date + (b.time || "")) ? -1 : 1)));
      setName(""); setEmail(""); setPhone(""); setClientId(null); setManualEntry(false); setNote(""); setPastDateConfirmed(false); setConflictConfirmed(false); setError("");
    }

    // Sept 18 2026: picking a real client from the list — the source of
    // truth is clientId; name/email get carried along too (display, plus
    // the email-reminder flow keeps reading session.email unchanged).
    function handlePickClient(c) {
      setClientId(c.id);
      setName(c.name || "");
      setEmail(c.email || "");
      setPhone(c.phone || "");
      setError("");
    }

    // Sept 10 2026: pre-fills the same add-session form from an existing
    // session so fixing a typo (wrong time, wrong email, whatever) is a
    // couple of taps instead of deleting the session and retyping the
    // whole thing from scratch.
    function handleStartEdit(session) {
      setEditingId(session.id);
      setName(session.name || "");
      setEmail(session.email || "");
      setPhone(session.phone || "");
      // Sept 18 2026: a session linked to a real client reopens in "picked
      // from the list" mode; an older/unlinked session reopens in manual
      // mode with whatever name/email it already had, so nothing here ever
      // looks like it lost data that was already saved.
      setClientId(session.clientId || null);
      setManualEntry(!session.clientId);
      setDate(session.date || todayISO());
      setTime(session.time || "09:00");
      setNote(session.note || "");
      if (canPickTrainer) setFormTrainerId(session.trainerId || "");
      setError("");
      // An existing session already dated in the past is normal (you're just
      // fixing a typo on it, not freshly booking it into the past) — only a
      // NEW past date typed in from here should trigger the warning.
      setPastDateConfirmed(!!(session.date && session.date < todayISO()));
      // Editing this session's own slot is never itself a conflict (the
      // check above already excludes the session's own id), so this always
      // starts unconfirmed/false — only actually changing the time/trainer
      // to collide with a DIFFERENT session would trigger the warning.
      setConflictConfirmed(false);
      if (formRef.current) formRef.current.scrollIntoView({ behavior: "smooth", block: "start" });
    }

    function handleCancelEdit() {
      setEditingId(null);
      setName(""); setEmail(""); setPhone(""); setClientId(null); setManualEntry(false); setNote(""); setError("");
      setDate(todayISO()); setTime("09:00"); setPastDateConfirmed(false); setConflictConfirmed(false);
      if (canPickTrainer) setFormTrainerId("");
    }

    // Sept 13 2026, Jimmy: tapping an empty hour in the day timeline below
    // pre-fills the same add-session form with the day/hour already being
    // looked at (same "jump to the form" pattern handleStartEdit already
    // uses) instead of leaving a trainer to scroll up and re-enter a date
    // and time they were just staring right at.
    function handleQuickAdd(hour) {
      setEditingId(null);
      setName(""); setEmail(""); setPhone(""); setClientId(null); setManualEntry(false); setNote(""); setError("");
      setDate(selectedDate);
      setTime(`${String(hour).padStart(2, "0")}:00`);
      setPastDateConfirmed(selectedDate < todayISO());
      setConflictConfirmed(false);
      if (canPickTrainer) setFormTrainerId("");
      if (formRef.current) formRef.current.scrollIntoView({ behavior: "smooth", block: "start" });
    }

    async function handleDeleteSession(id) {
      setSessions((prev) => prev.filter((s) => s.id !== id));
      if (sb) await sb.from("scheduled_sessions").delete().eq("id", id);
      if (editingId === id) handleCancelEdit();
    }

    // Sept 18 2026: the trash icon used to call handleDeleteSession
    // straight away — this is the confirm step in front of it. Opens the
    // ConfirmDialog with the actual session's name/date so it's obvious
    // exactly what's about to go, same as every other delete in the app.
    function requestDeleteSession(session) {
      setConfirmDelete(session);
    }
    async function confirmDeleteSessionNow() {
      if (!confirmDelete) return;
      setDeletingSession(true);
      await handleDeleteSession(confirmDelete.id);
      setDeletingSession(false);
      setConfirmDelete(null);
    }

    async function handleSendEmail(session) {
      setError("");
      if (!session.email) {
        setError("No email saved for this session — delete it and reschedule with an email to send an email reminder.");
        return;
      }
      if (!EMAILJS_READY || !window.emailjs) {
        setError("Email reminders aren't set up yet — add your EmailJS keys near the top of the file (see the setup guide).");
        return;
      }
      setSendingId(session.id);
      setSendingChannel("email");
      try {
        await window.emailjs.send(EMAILJS_SERVICE_ID, EMAILJS_TEMPLATE_ID, {
          to_name: session.name,
          to_email: session.email,
          session_date: fmtDateFull(session.date),
          session_time: session.time || "",
          note: session.note || ""
        });
        const sentAt = new Date().toISOString();
        if (sb) await sb.from("scheduled_sessions").update({ email_reminder_sent_at: sentAt }).eq("id", session.id);
        setSessions((prev) => prev.map((s) => (s.id === session.id ? { ...s, emailSentAt: sentAt } : s)));
      } catch (err) {
        const detail = (err && (err.text || err.message)) ? ` (${err.text || err.message})` : "";
        setError("Couldn't send that email — double check your EmailJS service/template IDs and public key." + detail);
      }
      setSendingId(null);
      setSendingChannel(null);
    }

    const sessionCountByDate = useMemo(() => {
      const map = {};
      sessions.forEach((s) => { map[s.date] = (map[s.date] || 0) + 1; });
      return map;
    }, [sessions]);
    const daySessions = useMemo(() => sessions
      .filter((s) => s.date === selectedDate)
      .sort((a, b) => ((a.time || "") < (b.time || "") ? -1 : 1)), [sessions, selectedDate]);
    const isDayPast = selectedDate < todayISO();

    if (!loaded) return e("div", { style: styles.empty }, e("p", { style: styles.emptyText }, "Loading rota…"));

    return e("div", null,
      e("div", { ref: formRef, style: styles.sessionForm },
        // Sept 18 2026: picking a real client (instead of free-typing a
        // name + email that only ever got matched back to a client by that
        // text elsewhere in the app) so a session is actually linked to the
        // right account — see the note on ClientPicker above for why.
        !manualEntry
          ? e(React.Fragment, null,
              e("div", { style: styles.sessionFormRow },
                e(ClientPicker, { value: clientId, options: clientOptions, onSelect: handlePickClient, style: { flex: 1 } })
              ),
              e("button", {
                type: "button", style: { ...styles.demoLinkBtn, marginBottom: 10 },
                onClick: () => { setManualEntry(true); setClientId(null); setName(""); setEmail(""); }
              }, "Not a client yet? Enter details manually")
            )
          : e(React.Fragment, null,
              e("div", { style: styles.sessionFormRow },
                e("input", { style: styles.input, list: "rota-client-list", placeholder: "Name", value: name, onChange: (ev) => handleNameChange(ev.target.value) }),
                e(VoiceMicButton, { title: "Say the name", onTranscribed: handleNameChange })
              ),
              e("datalist", { id: "rota-client-list" }, clientOptions.map((c) => e("option", { key: c.id, value: c.name }))),
              e("div", { style: styles.sessionFormRow },
                e("input", { style: styles.input, type: "email", list: "rota-email-list", placeholder: "Email", value: email, onChange: (ev) => handleEmailChange(ev.target.value) })
              ),
              e("datalist", { id: "rota-email-list" }, clientEmails.map((em) => e("option", { key: em, value: em }))),
              e("button", {
                type: "button", style: { ...styles.demoLinkBtn, marginBottom: 10 },
                onClick: () => { setManualEntry(false); setName(""); setEmail(""); }
              }, "Pick an existing client instead")
            ),
        // Sept 18 2026: session cards already showed a phone number when one
        // was on file — this is the field that actually lets one get saved
        // going forward. Auto-fills from the picked client when they have
        // one on their profile; editable either way (a client's booking
        // preference number can differ from their profile's).
        e("div", { style: styles.sessionFormRow },
          e("input", { style: styles.input, type: "tel", placeholder: "Phone (optional)", value: phone, onChange: (ev) => setPhone(ev.target.value) })
        ),
        e("div", { style: styles.sessionFormRow },
          e("input", { style: styles.input, type: "date", value: date, onChange: (ev) => { setDate(ev.target.value); setPastDateConfirmed(false); setConflictConfirmed(false); } }),
          e("input", { style: styles.input, type: "time", value: time, onChange: (ev) => { setTime(ev.target.value); setConflictConfirmed(false); } })
        ),
        canPickTrainer && e("select", {
          value: formTrainerId, onChange: (ev) => { setFormTrainerId(ev.target.value); setConflictConfirmed(false); },
          style: { ...styles.input, marginBottom: 10 }
        }, [e("option", { key: "", value: "" }, "Unassigned"), ...trainers.map((t) => e("option", { key: t.id, value: t.id }, t.name))]),
        e("div", { style: { display: "flex", gap: 8, marginBottom: 12 } },
          e("input", { style: { ...styles.inputEllipsis, flex: 1 }, placeholder: "Note (optional) — e.g. \"Upper body day\"", value: note, onChange: (ev) => setNote(ev.target.value) }),
          e(VoiceMicButton, { title: "Say a note for this session", onTranscribed: setNote })
        ),
        error && e("div", { style: { ...styles.errorBanner, marginBottom: 12 } }, e(Icon, { name: "x", size: 13, color: C.critical }), error),
        e("div", { style: { display: "flex", gap: 8 } },
          e("button", {
            style: { ...styles.saveBtn, marginTop: 0, flex: 1, ...(saving ? styles.btnDisabled : {}) }, disabled: saving, onClick: handleSchedule
          }, e(Icon, { name: editingId ? "check" : "calendar", size: 15 }), saving ? (editingId ? "Saving…" : "Scheduling…") : editingId ? "Save changes" : "Schedule session"),
          editingId && e("button", { style: { ...styles.demoLinkBtn, padding: "0 10px" }, disabled: saving, onClick: handleCancelEdit }, "Cancel")
        )
      ),
      e(CalendarMonth, {
        year: calYear, month: calMonth, sessionCountByDate, selectedDate,
        onSelectDate: goToDate, onPrevMonth: goPrevMonth, onNextMonth: goNextMonth
      }),
      e("div", { style: { ...styles.sectionHead, marginTop: 18, flexDirection: "row", alignItems: "center", justifyContent: "space-between" } },
        e("button", { style: styles.calendarNavBtn, onClick: goPrevDay, "aria-label": "Previous day" }, e(Icon, { name: "back", size: 15 })),
        e("div", { style: { display: "flex", flexDirection: "column", alignItems: "center", gap: 2 } },
          e("span", { style: styles.sectionTitle }, fmtDateFull(selectedDate)),
          // Sept 13 2026, Jimmy: "easy for trainers to use" — a one-tap way
          // back to today instead of counting Prev/Next taps after browsing
          // ahead to check next week's rota.
          selectedDate !== todayISO() && e("button", { style: styles.todayJumpBtn, onClick: () => goToDate(todayISO()) }, "Jump to today")
        ),
        e("button", { style: { ...styles.calendarNavBtn, transform: "rotate(180deg)" }, onClick: goNextDay, "aria-label": "Next day" }, e(Icon, { name: "back", size: 15 }))
      ),
      e(DayTimeline, {
        daySessions, onSendEmail: handleSendEmail, onDelete: requestDeleteSession, onEdit: handleStartEdit, onViewClient,
        sendingId, sendingChannel, past: isDayPast,
        canPickTrainer, trainerNameById,
        isToday: selectedDate === todayISO(), onQuickAdd: handleQuickAdd
      }),
      // Sept 18 2026: the trash icon on a session card used to delete it
      // instantly — this is the confirm step, same ConfirmDialog pattern
      // every other delete in the app already uses.
      confirmDelete && e(ConfirmDialog, {
        title: "Delete this session?",
        message: `This removes ${confirmDelete.name || "this"}'s session on ${fmtDateFull(confirmDelete.date)}${confirmDelete.time ? ` at ${confirmDelete.time}` : ""}. This can't be undone.`,
        confirmLabel: "Delete session",
        busy: deletingSession,
        onCancel: () => setConfirmDelete(null),
        onConfirm: confirmDeleteSessionNow
      })
    );
  }

  // ---- dashboard (totals for trainers + manager) ----

export { SessionsPanel };
