// @generated by tools/extract/extract.py — bodies copied verbatim from index.html
import { WHISH_NAME, WHISH_NUMBER } from "../../domain/access.js";
import { e } from "../react.js";
import { C, styles, withAlpha } from "../theme.js";
import { Icon } from "./Icon.js";
import React, { useEffect, useRef, useState } from "react";

  const MUSCLE_COLORS = {
    Chest: "#3987e5",
    Back: "#d95926",
    Legs: "#199e70",
    Shoulders: "#c98500",
    Arms: "#d55181",
    Core: "#3fae3f",
    Glutes: "#9085e9",
    "Full Body": "#e66767"
  };

  function BirthdayBadge({ style }) {
    // Sept 19 2026 inspection fix: hardcoded amber instead of the
    // theme-aware C.warning/warningSoft tokens every other amber badge in
    // the file uses (see publicChip) — read as muddy/low-contrast in dark
    // mode. Shown on every roster card, so a real day-to-day visibility bug.
    return e("span", {
      style: {
        display: "inline-flex", alignItems: "center", gap: 4, alignSelf: "flex-start",
        background: C.warningSoft, color: C.warning,
        borderRadius: 999, padding: "3px 9px", fontSize: 11, fontWeight: 700,
        ...style
      }
    }, "🎂 Happy Birthday!");
  }

  function Dot({ color, size = 8 }) {
    return e("span", { style: { width: size, height: size, borderRadius: "50%", background: color, display: "inline-block", flexShrink: 0 } });
  }

  function Segmented({ options, value, onChange, accent = C.brand }) {
    return e("div", { style: styles.segmented }, options.map((opt) =>
      e("button", {
        key: opt.value,
        style: { ...styles.segmentedBtn, ...(value === opt.value ? { background: withAlpha(accent, 0.14), color: accent, borderColor: withAlpha(accent, 0.45) } : {}) },
        onClick: () => onChange(opt.value)
      }, opt.label)
    ));
  }

  function Select({ value, onChange, options, style }) {
    const norm = options.map((o) => (typeof o === "string" ? { value: o, label: o } : o));
    return e("div", { style: { position: "relative", ...style } },
      e("select", {
        value, onChange: (ev) => onChange(ev.target.value),
        style: styles.select
      }, norm.map((o) => e("option", { key: o.value, value: o.value }, o.label))),
      e("div", { style: styles.selectChevron }, e(Icon, { name: "chevron", size: 14, color: C.ink3 }))
    );
  }

  // Sept 18 2026: same problem as the exercise-name catalog below, but for
  // scheduling — the Rota used to match a session to a client purely by
  // typed name/email TEXT, with no link at all to the client's real
  // account. Two clients sharing a first name (normal across 17 trainers'
  // rosters) could get mixed up anywhere that text was later matched back
  // (the manager Dashboard's session counts, trainer reassignment, etc).
  // This picks from the real client list instead, so the session stores a
  // real client id — same "pick from a list" pattern as WorkoutFilterSelect
  // just above, reusing the same styles. Same-name clients get their email
  // appended to the label so they're still tellable apart while picking.
  function ClientPicker({ value, options, onSelect, placeholder = "Search your clients…", style }) {
    const [open, setOpen] = useState(false);
    const [query, setQuery] = useState("");
    const wrapRef = useRef(null);
    useEffect(() => {
      function onDocClick(ev) { if (wrapRef.current && !wrapRef.current.contains(ev.target)) setOpen(false); }
      document.addEventListener("mousedown", onDocClick);
      return () => document.removeEventListener("mousedown", onDocClick);
    }, []);
    const nameCounts = {};
    options.forEach((o) => { nameCounts[o.name] = (nameCounts[o.name] || 0) + 1; });
    const labeled = options.map((o) => ({ ...o, label: nameCounts[o.name] > 1 && o.email ? `${o.name} (${o.email})` : o.name }));
    const current = labeled.find((o) => o.id === value);
    const q = query.trim().toLowerCase();
    const filtered = !q ? labeled : labeled.filter((o) => o.label.toLowerCase().includes(q));
    function pick(o) { onSelect(o); setQuery(""); setOpen(false); }
    return e("div", { ref: wrapRef, style: { position: "relative", ...style } },
      e("input", {
        style: styles.select, placeholder,
        value: open ? query : (current ? current.label : ""),
        onFocus: (ev) => { setOpen(true); setQuery(""); ev.target.select(); },
        onClick: (ev) => { if (!open) { setOpen(true); setQuery(""); ev.target.select(); } },
        onChange: (ev) => { setQuery(ev.target.value); setOpen(true); }
      }),
      e("div", { style: styles.selectChevron }, e(Icon, { name: "chevron", size: 14, color: C.ink3 })),
      open && e("div", { style: styles.exercisePickerPanel },
        filtered.length === 0 && e("div", { style: styles.demoNote }, "No matching client — use “not on the list” below."),
        filtered.map((o) => e("button", {
          key: o.id, type: "button", style: styles.exercisePickerOption,
          onMouseDown: (ev) => ev.preventDefault(), onClick: () => pick(o)
        }, o.label))
      )
    );
  }

  // Watches real mic volume while a recording is live, for the "talking" trainer
  // emoji — taps the exact same getUserMedia stream every recorder already opens
  // (no extra permission prompt, no second mic grab), reads it through a Web Audio
  // AnalyserNode, and exposes a smoothed 0–1 loudness level via requestAnimationFrame.
  // Every voice button in the app shares this one hook so the emoji reacts the same
  // way everywhere. If Web Audio is unsupported/blocked, level just stays 0 and the
  // emoji sits still — recording and transcription are completely unaffected either way.
  function useTalkingLevel() {
    const [level, setLevel] = useState(0);
    const audioCtxRef = useRef(null);
    const analyserRef = useRef(null);
    const dataRef = useRef(null);
    const rafRef = useRef(null);

    function attach(stream) {
      try {
        const AudioCtx = window.AudioContext || window.webkitAudioContext;
        if (!AudioCtx) return;
        const ctx = new AudioCtx();
        ctx.resume().catch(() => {}); // Safari can start a context "suspended" if it wasn't created inside the click itself — harmless no-op elsewhere
        const source = ctx.createMediaStreamSource(stream);
        const analyser = ctx.createAnalyser();
        analyser.fftSize = 256;
        analyser.smoothingTimeConstant = 0.55;
        source.connect(analyser);
        audioCtxRef.current = ctx;
        analyserRef.current = analyser;
        dataRef.current = new Uint8Array(analyser.frequencyBinCount);
        const tick = () => {
          if (!analyserRef.current) return;
          analyserRef.current.getByteFrequencyData(dataRef.current);
          let sum = 0;
          for (let i = 0; i < dataRef.current.length; i++) sum += dataRef.current[i];
          const avg = sum / dataRef.current.length / 255; // 0..1
          setLevel(Math.min(1, avg * 2.6)); // normal speaking volume rarely maxes the raw average — scale up so quiet speech still visibly moves it
          rafRef.current = requestAnimationFrame(tick);
        };
        tick();
      } catch (e) { /* Web Audio unsupported/blocked — emoji just stays still */ }
    }

    function detach() {
      if (rafRef.current) cancelAnimationFrame(rafRef.current);
      rafRef.current = null;
      analyserRef.current = null;
      if (audioCtxRef.current) { audioCtxRef.current.close().catch(() => {}); audioCtxRef.current = null; }
      setLevel(0);
    }

    useEffect(() => () => detach(), []);
    return { level, attach, detach };
  }

  // The little "he's speaking" trainer emoji shown next to a voice button while
  // it's recording — a real 🏋️ (renders as a glossy 3D figure on iOS/Mac/most
  // modern phones via the system emoji font, no image asset needed) that visibly
  // bounces bigger and glows on your louder syllables and settles back down in the
  // quiet between them, driven live by useTalkingLevel's level — not a fixed loop,
  // it actually reacts to your real voice as you talk.
  function TalkingTrainerEmoji({ level = 0, size = 20 }) {
    const scale = 1 + Math.min(0.6, level * 0.6);
    return e("span", {
      "aria-hidden": "true",
      style: {
        display: "inline-block", fontSize: size, lineHeight: 1,
        transform: `scale(${scale})`,
        transition: "transform 70ms linear",
        filter: level > 0.12 ? "drop-shadow(0 0 5px rgba(255,255,255,0.4))" : "none"
      }
    }, "🏋️");
  }

  // Sept 12 2026, Jimmy: "when the client tap the mic and finish talking i
  // want to see a loading thing to understand... its loading" — every mic
  // button here used to go one of two ways once recording actually stopped
  // and the audio was off being transcribed: either a bare "…" with no
  // context, or (worse, in a couple of spots) it just kept saying
  // "Listening…" for those few seconds even though the client was done
  // talking — reads as frozen/broken. This is the one shared "working on
  // it" visual (three small dots, staggered pulse using the same `pulse`
  // keyframe as the splash screen) used by every voice input the moment
  // recording stops, paired with wording that actually matches what's
  // happening (transcribing/understanding), not still-listening.
  function VoiceLoadingDots({ size = 5, color = "currentColor" }) {
    return e("span", { style: { display: "inline-flex", alignItems: "center", gap: 3 } },
      [0, 1, 2].map((i) => e("span", {
        key: i,
        style: {
          width: size, height: size, borderRadius: "50%", background: color, display: "inline-block",
          animation: `pulse 1s ease-in-out ${i * 0.15}s infinite`
        }
      }))
    );
  }

  function StatTile({ label, value, unit, delta, size = "md" }) {
    return e("div", { style: styles.statTile }, [
      e("span", { key: "l", style: styles.statTileLabel }, label),
      e("div", { key: "v", style: { display: "flex", alignItems: "baseline", gap: 6, flexWrap: "wrap" } }, [
        e("span", { key: "n", style: size === "lg" ? styles.statTileValueLg : styles.statTileValue }, typeof value === "number" ? value.toLocaleString() : value),
        unit && e("span", { key: "u", style: styles.statTileUnit }, unit),
        delta ? e("span", { key: "d", style: { ...styles.deltaChip, color: delta.dir === "up" ? C.good : delta.dir === "down" ? C.critical : C.ink3, background: delta.dir === "up" ? C.goodSoft : delta.dir === "down" ? C.criticalSoft : "transparent" } }, [
          delta.dir !== "flat" && e(Icon, { key: "i", name: delta.dir === "up" ? "trendUp" : "trendDown", size: 11, strokeWidth: 2.5 }),
          e("span", { key: "t" }, delta.text)
        ]) : null
      ])
    ]);
  }

  function muscleRegionFill(regionKey, primaryKey, secondarySet) {
    // A visible (not near-transparent) neutral tone by default — this needs to
    // read as "a body" even where nothing is highlighted, not just show a few
    // colored blobs floating with nothing around them.
    if (!regionKey) return C.cardBorderStrong;
    // primaryKey is normally one exercise's single primary muscle (a string),
    // but the weekly muscle-balance view below needs to light up several
    // muscles as "trained" at once — accepting a Set here too (instead of a
    // second near-duplicate fill function) keeps both views drawing from the
    // exact same tier logic.
    const isPrimary = primaryKey instanceof Set ? primaryKey.has(regionKey) : primaryKey === regionKey;
    if (isPrimary) return C.brand;
    if (secondarySet.has(regionKey)) return withAlpha(C.brand, 0.45);
    return C.cardBorderStrong;
  }

  function DashboardStatGrid({ stats }) {
    const tiles = [
      { label: "Sessions today", value: String(stats.sessionsToday) },
      { label: "Sessions this month", value: String(stats.sessionsMonth) },
      { label: "Collected this month", value: `$${stats.monthPaid.toLocaleString()}` },
      { label: "Collected all-time", value: `$${stats.totalPaid.toLocaleString()}` }
    ];
    return e("div", { style: styles.dashGrid }, tiles.map((t) => e("div", { key: t.label, style: styles.dashTile },
      e("span", { style: styles.profileLabel }, t.label),
      e("span", { style: styles.dashTileValue }, t.value)
    )));
  }

  // Sept 11 2026, Jimmy: brand pass, bigger step — the reference mockups
  // called out the browser's own plain window.confirm() popup for deletes
  // ("bigger targets that ask first" vs. a system alert with no styling).
  // This is a reusable, on-brand replacement using the same bottom-sheet
  // look every other form in the app already uses, so a delete confirmation
  // doesn't look like it belongs to a different app. Swapped in for the
  // highest-stakes deletes first (a whole client, and clearing a client's
  // workout history) — see handleDeleteClient/handleClearWorkouts below.
  // Sept 16 2026, Jimmy: account-deletion work (Apple guideline 5.1.1(v) —
  // an app that supports account creation must let someone delete their own
  // account from inside the app). This is the highest-stakes "Delete" this
  // dialog is ever used for — a mistap on a client card is annoying and
  // recoverable by re-adding them; deleting your own login isn't — so
  // ConfirmDialog picked up an optional typed-confirmation gate rather than
  // spinning up a second, near-identical modal just for this one case.
  // Every existing call site (roster removal, set deletion, etc.) passes no
  // `requireTyped` and is completely unchanged.
  function ConfirmDialog({ title, message, confirmLabel = "Delete", onConfirm, onCancel, requireTyped = null, busy = false, extra = null }) {
    const [typed, setTyped] = useState("");
    const locked = !!requireTyped && typed.trim().toUpperCase() !== requireTyped.toUpperCase();
    return e("div", { style: styles.overlay, onClick: busy ? undefined : onCancel },
      e("div", { style: { ...styles.sheet, maxWidth: 420 }, onClick: (ev) => ev.stopPropagation() },
        e("span", { style: styles.sheetTitle }, title),
        e("p", { style: { ...styles.profileGoalText, marginTop: 10, marginBottom: requireTyped ? 14 : 22 } }, message),
        requireTyped && e("input", {
          type: "text", value: typed, onChange: (ev) => setTyped(ev.target.value),
          placeholder: `Type ${requireTyped} to confirm`, autoCapitalize: "characters",
          style: { ...styles.input, marginBottom: 18 }
        }),
        extra,
        e("div", { style: { display: "flex", gap: 10 } },
          e("button", { style: styles.confirmCancelBtn, onClick: onCancel, disabled: busy }, "Cancel"),
          e("button", {
            style: { ...styles.confirmDangerBtn, ...((locked || busy) ? styles.btnDisabled : {}) },
            disabled: locked || busy,
            onClick: onConfirm
          }, busy ? "Working…" : confirmLabel)
        )
      )
    );
  }

  // Tap-to-start rest timer. Counts down locally in the browser — no server
  // round trip needed, so it works instantly between sets.
  function RestTimerChip({ seconds }) {
    const [remaining, setRemaining] = useState(null);
    useEffect(() => {
      if (remaining === null || remaining <= 0) return;
      const id = setTimeout(() => setRemaining((r) => (r === null ? null : r - 1)), 1000);
      return () => clearTimeout(id);
    }, [remaining]);
    if (!seconds) return null;
    const running = remaining !== null && remaining > 0;
    const done = remaining === 0;
    function handleTap(ev) {
      ev.stopPropagation();
      setRemaining(seconds);
    }
    const mm = remaining != null ? Math.floor(remaining / 60) : 0;
    const ss = remaining != null ? remaining % 60 : 0;
    const label = running ? `${mm}:${String(ss).padStart(2, "0")}` : done ? "Rest done" : `Rest ${fmtRest(seconds)}`;
    return e("button", {
      style: {
        ...styles.setChip,
        cursor: "pointer",
        ...(running ? { color: C.brand, borderColor: withAlpha(C.brand, 0.4), background: C.brandSoft } : {}),
        ...(done ? { color: C.good, borderColor: withAlpha(C.good, 0.4), background: C.goodSoft } : {})
      },
      onClick: handleTap
    }, e(Icon, { name: "flame", size: 10, strokeWidth: 2.5 }), label);
  }

  // Reusable "how to pay" box — same Whish name/number everywhere a client
  // is told a payment is pending, so it's not just "ask your gym" with no
  // way to actually act on it. amount/note are optional; pass them to add
  // the "Send $X..." line under the box, same wording each screen used to
  // write out by hand.
  function WhishPayBox({ amount = null, note = "" }) {
    return e(React.Fragment, null,
      e("div", { style: { background: withAlpha(C.brand, 0.08), borderRadius: 10, padding: "10px 12px", width: "100%" } },
        e("p", { style: { margin: 0, fontSize: 12, color: C.ink3, textTransform: "uppercase", letterSpacing: "0.04em", fontWeight: 700 } }, "Pay via Whish Money"),
        e("p", { style: { margin: "4px 0 0", fontSize: 14, fontWeight: 600, color: C.ink } }, WHISH_NAME),
        e("p", { style: { margin: "2px 0 0", fontSize: 14, fontFamily: "'JetBrains Mono', monospace", color: C.ink } }, WHISH_NUMBER)
      ),
      // Sept 13 2026, Jimmy: "exact same the photo" — jimfit-flow_15.html
      // shows this line bold and gold/amber, not the small gray caption it
      // used to be; same gold as the SlideToUnlock lock icon.
      amount != null && e("p", { style: { margin: "8px 0 0", fontSize: 16, fontWeight: 700, color: "#F5C542", textAlign: "center" } }, `Send $${amount}${note ? `, ${note}` : ""}`)
    );
  }

export { MUSCLE_COLORS, BirthdayBadge, Dot, Segmented, Select, ClientPicker, useTalkingLevel, TalkingTrainerEmoji, VoiceLoadingDots, StatTile, muscleRegionFill, DashboardStatGrid, ConfirmDialog, RestTimerChip, WhishPayBox };
