// @generated by tools/extract/extract.py — bodies copied verbatim from index.html
import { e } from "../react.js";

  function Icon({ name, size = 18, color = "currentColor", strokeWidth = 2 }) {
    const common = { width: size, height: size, viewBox: "0 0 24 24", fill: "none", stroke: color, strokeWidth, strokeLinecap: "round", strokeLinejoin: "round" };
    switch (name) {
      case "dumbbell":
        return e("svg", common, e("path", { d: "M6 8v8M18 8v8M3 11v2M21 11v2M6 12h12" }));
      case "plus":
        return e("svg", common, e("path", { d: "M12 5v14M5 12h14" }));
      case "x":
        return e("svg", common, e("path", { d: "M18 6L6 18M6 6l12 12" }));
      case "trash":
        return e("svg", common, e("path", { d: "M3 6h18M8 6V4a1 1 0 011-1h6a1 1 0 011 1v2m2 0l-1 14a1 1 0 01-1 1H7a1 1 0 01-1-1L5 6" }));
      case "calendar":
        return e("svg", common, e("rect", { x: "3", y: "5", width: "18", height: "16", rx: "2" }), e("path", { d: "M16 3v4M8 3v4M3 10h18" }));
      case "clock":
        return e("svg", common, e("circle", { cx: "12", cy: "12", r: "9" }), e("path", { d: "M12 7v5l3.5 2" }));
      case "flame":
        return e("svg", common, e("path", { d: "M12 2c1 4-3 5-3 9a3 3 0 006 0c0-1.5-1-2-1-3.5 2 1 3 3 3 5.5a5 5 0 01-10 0c0-4 3-6 5-11z" }));
      case "activity":
        return e("svg", common, e("path", { d: "M22 12h-4l-3 9-6-18-3 9H2" }));
      case "users":
        return e("svg", common, e("circle", { cx: "9", cy: "8", r: "3" }), e("path", { d: "M2 21v-2a5 5 0 015-5h4a5 5 0 015 5v2" }), e("circle", { cx: "18", cy: "8", r: "2.3" }), e("path", { d: "M17 11.2c1.9.4 3 1.9 3 3.8v2" }));
      case "lock":
        return e("svg", common, e("rect", { x: "4", y: "10", width: "16", height: "10", rx: "2" }), e("path", { d: "M8 10V7a4 4 0 018 0v3" }));
      case "back":
        return e("svg", common, e("path", { d: "M15 18l-6-6 6-6" }));
      case "chevron":
        return e("svg", common, e("path", { d: "M6 9l6 6 6-6" }));
      case "trendUp":
        return e("svg", common, e("path", { d: "M3 17l6-6 4 4 8-8M15 7h6v6" }));
      case "trendDown":
        return e("svg", common, e("path", { d: "M3 7l6 6 4-4 8 8M21 11v6h-6" }));
      case "sparkle":
        return e("svg", common, e("path", { d: "M12 3v4M12 17v4M3 12h4M17 12h4M6 6l2.5 2.5M15.5 15.5L18 18M18 6l-2.5 2.5M8.5 15.5L6 18" }));
      case "trophy":
        return e("svg", common,
          e("path", { d: "M8 21h8M12 17v4M6 4h12v3a6 6 0 0 1-12 0V4z" }),
          e("path", { d: "M6 5H3v2a3 3 0 0 0 3 3M18 5h3v2a3 3 0 0 1-3 3" })
        );
      case "tag":
        return e("svg", common, e("path", { d: "M20.6 12.6L13 5H5v8l7.6 7.6a2 2 0 002.8 0l5.2-5.2a2 2 0 000-2.8z" }), e("circle", { cx: "8.5", cy: "8.5", r: "1.3", fill: color, stroke: "none" }));
      case "edit":
        return e("svg", common, e("path", { d: "M12 20h9" }), e("path", { d: "M16.5 3.5a2.1 2.1 0 013 3L7 19l-4 1 1-4L16.5 3.5z" }));
      case "mail":
        return e("svg", common, e("rect", { x: "3", y: "5", width: "18", height: "14", rx: "2" }), e("path", { d: "M3 7l9 6 9-6" }));
      case "check":
        return e("svg", common, e("path", { d: "M20 6L9 17l-5-5" }));
      case "logout":
        return e("svg", common, e("path", { d: "M9 21H5a2 2 0 01-2-2V5a2 2 0 012-2h4" }), e("path", { d: "M16 17l5-5-5-5" }), e("path", { d: "M21 12H9" }));
      case "alert":
        return e("svg", common, e("path", { d: "M12 3l9.5 17H2.5L12 3z" }), e("path", { d: "M12 10v4" }), e("circle", { cx: "12", cy: "17.3", r: "0.6", fill: color, stroke: "none" }));
      case "bell":
        return e("svg", common, e("path", { d: "M18 8a6 6 0 00-12 0c0 7-3 9-3 9h18s-3-2-3-9" }), e("path", { d: "M13.73 21a2 2 0 01-3.46 0" }));
      case "camera":
        return e("svg", common, e("path", { d: "M4 8h3l1.5-2h7L17 8h3a1 1 0 011 1v10a1 1 0 01-1 1H4a1 1 0 01-1-1V9a1 1 0 011-1z" }), e("circle", { cx: "12", cy: "13.5", r: "3.5" }));
      case "menu":
        return e("svg", common, e("path", { d: "M4 6h16M4 12h16M4 18h16" }));
      case "mic":
        return e("svg", common, e("path", { d: "M12 2a3 3 0 00-3 3v6a3 3 0 006 0V5a3 3 0 00-3-3z" }), e("path", { d: "M19 10v1a7 7 0 01-14 0v-1" }), e("path", { d: "M12 18v4M8 22h8" }));
      case "chat":
        return e("svg", common, e("path", { d: "M21 11.5a8.5 8.5 0 01-8.5 8.5 8.4 8.4 0 01-4-1L3 20l1.2-5.2A8.5 8.5 0 1121 11.5z" }));
      case "play":
        return e("svg", common, e("circle", { cx: "12", cy: "12", r: "9" }), e("path", { d: "M10 8.5l6 3.5-6 3.5v-7z", fill: color, stroke: "none" }));
      case "copy":
        return e("svg", common, e("rect", { x: "8", y: "8", width: "13", height: "13", rx: "2" }), e("path", { d: "M16 8V5a2 2 0 00-2-2H5a2 2 0 00-2 2v9a2 2 0 002 2h3" }));
      case "sun":
        return e("svg", common, e("circle", { cx: "12", cy: "12", r: "4.5" }), e("path", { d: "M12 2v2.5M12 19.5V22M4.2 4.2l1.8 1.8M18 18l1.8 1.8M2 12h2.5M19.5 12H22M4.2 19.8L6 18M18 6l1.8-1.8" }));
      case "moon":
        return e("svg", common, e("path", { d: "M20 14.5A8.5 8.5 0 019.5 4a8.5 8.5 0 1010.5 10.5z" }));
      case "apple":
        return e("svg", common, e("path", { d: "M12 8.2c-1.6-1.7-4-2-5.6-.5C4 10 4.3 16 8 19.5c1.1 1 2.2 1.5 3.3 1.5.8 0 1.4-.2 2-.4.6.2 1.2.4 2 .4 1.1 0 2.2-.5 3.3-1.5C22.3 16 22.6 10 20.2 7.7c-1.6-1.5-4-1.2-5.6.5" }), e("path", { d: "M12 8.2V5.5c0-1 .7-2 2-2.3" }));
      // Sept 7 2026, Jimmy: wanted a way to search the (often long)
      // "Exercise progression" list on Muscles and "Personal records" list
      // on Progress instead of scrolling the whole page — see the search
      // boxes added to StatsPanel and PersonalRecordsPanel below.
      case "search":
        return e("svg", common, e("circle", { cx: "11", cy: "11", r: "7" }), e("path", { d: "M21 21l-4.3-4.3" }));
      // Sept 12 2026, Jimmy: "the food swap click" — the "Show food swaps"
      // toggle used to be plain text, easy to miss/mistap. Gave it a real
      // pill button (styles.energyPillBtn) with this two-arrow "swap" icon
      // next to it, same branded-and-easy-to-tap treatment as the Energy
      // balance card's buttons got earlier.
      case "swap":
        return e("svg", common, e("path", { d: "M7 8h11l-3.5-3.5M17 16H6l3.5 3.5" }));
      case "user":
        return e("svg", common, e("circle", { cx: "12", cy: "8", r: "4" }), e("path", { d: "M4 20c0-3.9 3.6-7 8-7s8 3.1 8 7" }));
      case "minus":
        return e("svg", common, e("path", { d: "M5 12h14" }));
      case "eye":
        return e("svg", common, e("path", { d: "M1.5 12S5 5 12 5s10.5 7 10.5 7-3.5 7-10.5 7S1.5 12 1.5 12z" }), e("circle", { cx: "12", cy: "12", r: "3" }));
      case "eyeOff":
        return e("svg", common,
          e("path", { d: "M3 3l18 18" }),
          e("path", { d: "M10.6 5.1A10.7 10.7 0 0112 5c7 0 10.5 7 10.5 7a17.6 17.6 0 01-3.2 4.2M6.6 6.6C3.7 8.4 1.5 12 1.5 12S5 19 12 19a10.6 10.6 0 004-.8" }),
          e("path", { d: "M9.9 9.9a3 3 0 004.2 4.2" })
        );
      default:
        return null;
    }
  }

export { Icon };
