// @generated by tools/extract/extract.py — bodies copied verbatim from index.html
import { TRAINING_STYLES } from "./body.js";

  function urlBase64ToUint8Array(base64String) {
    const padding = "=".repeat((4 - (base64String.length % 4)) % 4);
    const base64 = (base64String + padding).replace(/-/g, "+").replace(/_/g, "/");
    const rawData = window.atob(base64);
    const outputArray = new Uint8Array(rawData.length);
    for (let i = 0; i < rawData.length; i++) outputArray[i] = rawData.charCodeAt(i);
    return outputArray;
  }

  // Sept 18 2026, Jimmy: "I need to see it before it saved and I need to
  // know that it is saved" — voice auto-save (below) was firing instantly,
  // clearing the exercise/sets fields before he could register what got
  // filled in, with only a generic "Added" flash as proof anything
  // happened. This builds a one-line summary of exactly what was logged
  // ("Bench Press — 3 × 10 reps @ 40kg") to show in that flash instead.
  function summarizeSetsForFlash(cleanSets, isTimed) {
    if (!cleanSets || !cleanSets.length) return "";
    const first = cleanSets[0];
    const sameAsFirst = (s) => (isTimed ? s.duration === first.duration : s.reps === first.reps) && s.weight === first.weight;
    const allSame = cleanSets.every(sameAsFirst);
    const oneLabel = (s) => {
      const amount = isTimed ? `${s.duration}s` : `${s.reps} reps`;
      const weightLabel = s.isBodyweight ? "bodyweight" : `${s.weight}kg`;
      return `${amount} @ ${weightLabel}`;
    };
    if (allSame) return `${cleanSets.length} × ${oneLabel(first)}`;
    return cleanSets.map(oneLabel).join(", ");
  }

  // Splits a calorie target into Calories/Protein/Carbs/Fat. Protein tracks
  // lean mass when it's known (2.2g/kg lean mass — muscle tissue is what
  // actually needs the protein, so this is more accurate for anyone
  // visibly muscular or visibly lean than a flat per-kg-bodyweight number),
  // falling back to bodyweight (2g/kg, 1.6g/kg if Female — women typically
  // carry a higher body-fat baseline so a slightly lower protein-per-kg
  // target still lands in a sensible range) when no body-fat%/muscle-mass
  // was given. Fat is 25% of calories either way, and carbs take whatever
  // calories are left over.
  // Standard sports-nutrition rule of thumb (35 ml per kg bodyweight) — used
  // any time a water target gets auto-calculated alongside calories/macros,
  // since without a water target set the water-logging card on the Diet tab
  // has nothing to measure against and stays hidden entirely (Sept 6 2026 —
  // Jimmy: "i also want to see the water log" — a self-train client with an
  // auto-calculated calorie/macro plan never got a water target, so she had
  // no way to log water at all).
  function waterTargetMlFromWeight(weightKg) {
    return Math.round((weightKg || 70) * 35);
  }

  function volumeInRange(entries, startDaysAgo, endDaysAgo) {
    const start = new Date(); start.setDate(start.getDate() - startDaysAgo);
    const end = new Date(); end.setDate(end.getDate() - endDaysAgo);
    let vol = 0;
    entries.forEach((x) => {
      const d = new Date(x.date);
      if (d >= start && d < end) x.sets.forEach((s) => { vol += (Number(s.reps) || 0) * (Number(s.weight) || 0); });
    });
    return Math.round(vol);
  }

  // Sept 18 2026: same idea as sparklineGeometry above but reading a plain
  // `value` field instead of a hardcoded `.weight`, so one geometry helper
  // works for any numeric metric (used by MetricTrendCard below for both
  // AssessmentPanel and MeasurementsPanel's new trend views). Left
  // sparklineGeometry itself untouched — ProgressCard's exercise-progression
  // sparklines already depend on its exact `.weight` shape.
  function trendGeometry(values, w, h, pad) {
    const min = Math.min(...values), max = Math.max(...values);
    const range = max - min || 1;
    const n = values.length;
    const stepX = n > 1 ? (w - 2 * pad) / (n - 1) : 0;
    return values.map((v, i) => [pad + i * stepX, pad + (h - 2 * pad) * (1 - (v - min) / range)]);
  }

  function youtubeEmbedUrl(url) {
    if (!url) return null;
    const m = url.match(/(?:youtube\.com\/watch\?v=|youtu\.be\/|youtube\.com\/shorts\/|youtube\.com\/embed\/)([a-zA-Z0-9_-]{6,})/);
    return m ? `https://www.youtube.com/embed/${m[1]}` : null;
  }

  // One-click jump to a pre-filled YouTube search for an exercise with no demo
  // yet, so finding a video is "click, pick the best result, copy the link"
  // instead of opening YouTube and typing the name in yourself every time.
  function youtubeSearchUrl(name) {
    return `https://www.youtube.com/results?search_query=${encodeURIComponent((name || "").trim() + " exercise tutorial")}`;
  }

  // Turns the structured multi-set result from SmartVoiceEntryButton (one row
  // per set, each with reps/weight/rest) into the compact strings this form's
  // own fields expect — "3x8" sets-x-reps, one rest number, and a per-set
  // "70x70x90" weight string (same shorthand the Weight field's own
  // placeholder already teaches) — since a program's exercise row is a single
  // compact row, not the Log feature's per-set grid.
  function summarizeVoiceSets(sets) {
    const firstReps = sets.map((s) => s.reps).find((r) => r != null);
    const setsReps = firstReps != null ? `${sets.length}x${firstReps}` : "";
    const firstRest = sets.map((s) => s.rest).find((r) => r != null);
    const rest = firstRest != null ? String(firstRest) : "";
    const weights = sets.map((s) => (s.weight != null ? String(s.weight) : null));
    const weight = weights.every((w) => w != null) ? weights.join("x") : (weights.find((w) => w != null) || "");
    return { setsReps, rest, weight };
  }

  // Fully editable — trainers build these programs themselves (create a program,
  // add days, add/edit/delete each exercise). The seeded programs are just a
  // starting point, not fixed content.
  function styleLabel(v) {
    const found = TRAINING_STYLES.find((s) => s.value === v);
    return found ? found.label : v;
  }

  // Faint, repeating overlay stamped over a client's program content so a
  // screenshot/photo of it carries the client's name — discourages a paid
  // program getting forwarded around for free, without blocking anything
  // (pointer-events: none) or hurting readability (very low opacity).
  function watermarkTileDataUri(label) {
    const safe = String(label)
      .replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;")
      .replace(/"/g, "&quot;").replace(/'/g, "&apos;");
    const svg =
      "<svg xmlns='http://www.w3.org/2000/svg' width='230' height='130'>" +
      "<text x='115' y='72' transform='rotate(-28 115 65)' text-anchor='middle' " +
      "font-family='Arial, sans-serif' font-size='13' fill='rgba(140,150,175,0.5)'>" + safe + "</text>" +
      "</svg>";
    return "data:image/svg+xml," + encodeURIComponent(svg);
  }

  // Turns this form's structured per-set array into the compact legacy
  // summary columns (sets count, "8x10x10" reps text, "60x60x65" weight
  // text, one rest value) — kept as a fallback display/search surface for
  // any exercise saved before `sets_detail` existed. `sets_detail` (the new
  // jsonb column, same per-set shape as workout_entries.sets) is always the
  // source of truth for anything saved through this form now.
  function summarizeSetsDetail(sets, isTimed, isBodyweight) {
    const reps = sets.map((s) => (isTimed ? `${s.duration}s` : s.reps)).join("x");
    const weight = isBodyweight ? "Bodyweight" : sets.map((s) => (s.weight != null ? s.weight : "")).join("x");
    const rest = sets.length && sets[0].rest != null ? sets[0].rest : null;
    return { sets: sets.length, reps, weight, rest_seconds: rest };
  }

export { urlBase64ToUint8Array, summarizeSetsForFlash, waterTargetMlFromWeight, volumeInRange, trendGeometry, youtubeEmbedUrl, youtubeSearchUrl, summarizeVoiceSets, styleLabel, watermarkTileDataUri, summarizeSetsDetail };
