// @generated by tools/extract/extract.py — bodies copied verbatim from index.html
import { summarizeVoiceSets } from "../../domain/group4.js";
import { e } from "../../shared/react.js";
import { C, styles } from "../../shared/theme.js";
import { Icon } from "../../shared/ui/Icon.js";
import { ExercisePicker } from "../../shared/widgets/ExercisePicker.js";
import { SmartVoiceEntryButton } from "../../shared/widgets/SmartVoiceEntryButton.js";

  function ExerciseForm({ values, onChange, onSave, onCancel, saving, showDayField, showWeekField, showWeightField, saveLabel = "Save", isEditing = false, savedFlash = false }) {
    return e("div", { style: { ...styles.sessionForm, marginTop: 10, marginBottom: 0 } },
      // Same one-mic "speak the whole exercise" experience as the Log
      // feature's New Exercise form. This form used to also have small
      // per-field mics on the Exercise picker, Day label, and Notes — so
      // speaking a full exercise into whichever one was handy just dumped
      // the raw sentence as plain text into that one field, instead of
      // splitting it out (Jimmy, Sept 9 2026: "one speaker... not many one
      // like the one in log"). Those per-field mics are now switched off
      // (see showMic: false below, and the Day label/Notes fields further
      // down) so this is the ONLY mic in the form, exactly matching the Log
      // feature's mic surface. This uses the same voice-log-entry parsing,
      // then reshapes its per-set array into this form's compact string
      // fields via summarizeVoiceSets above.
      e(SmartVoiceEntryButton, {
        label: "Speak this exercise — name, sets, weight",
        onParsed: (result) => {
          const next = { ...values };
          if (showDayField && result.workoutTitle && !values.dayLabel) next.dayLabel = result.workoutTitle;
          if (result.exerciseName) next.exercise = result.exerciseName;
          if (Array.isArray(result.sets) && result.sets.length) {
            const summary = summarizeVoiceSets(result.sets);
            if (summary.setsReps) next.setsReps = summary.setsReps;
            if (summary.rest) next.rest = summary.rest;
            if (showWeightField && summary.weight) next.weight = summary.weight;
          }
          onChange(next);
        }
      }),
      // Only ClientCustomProgramCard's trainer-written, client-specific
      // programs pass showWeekField — the shared TRAINING_STYLES library
      // above has no week concept, so every existing call site here leaves
      // it undefined and sees no change.
      showWeekField && e("div", { style: { display: "flex", gap: 8 } },
        e("input", {
          style: { ...styles.input, flex: 1 }, placeholder: "Week label (e.g. Week 1)",
          value: values.weekLabel, onChange: (ev) => onChange({ ...values, weekLabel: ev.target.value })
        })
      ),
      showDayField && e("div", { style: { display: "flex", gap: 8, marginTop: showWeekField ? 10 : 0 } },
        e("input", {
          style: { ...styles.input, flex: 1 }, placeholder: "Day label (e.g. Day 1 — Squat)",
          value: values.dayLabel, onChange: (ev) => onChange({ ...values, dayLabel: ev.target.value })
        })
      ),
      e("div", { style: (showDayField || showWeekField) ? { marginTop: 10 } : {} },
        // Sept 9 2026: this field's own mic is switched off here, same as the
        // Log form already does — the SmartVoiceEntryButton above is now the
        // one and only mic in this form (matching Jimmy's "one speaker, not
        // many like the log" ask), so a second mic that only fills the raw
        // spoken sentence into this one field would just be confusing again.
        e(ExercisePicker, {
          value: values.exercise, placeholder: "Search exercises… e.g. Bench Press",
          onSelect: (name) => onChange({ ...values, exercise: name }),
          showMic: false
        })
      ),
      e("div", { style: { display: "flex", gap: 8, marginTop: 10 } },
        e("input", { style: { ...styles.input, flex: 1 }, placeholder: "Sets x reps (e.g. 3x8)", value: values.setsReps, onChange: (ev) => onChange({ ...values, setsReps: ev.target.value }) }),
        e("input", { style: { ...styles.input, flex: 1 }, placeholder: "Rest (sec)", type: "number", min: "0", value: values.rest, onChange: (ev) => onChange({ ...values, rest: ev.target.value }) })
      ),
      showWeightField && e("div", { style: { marginTop: 10 } },
        e("input", { style: styles.input, placeholder: "Weight, kg — per set, e.g. 70x70x90 (optional)", type: "text", inputMode: "decimal", value: values.weight || "", onChange: (ev) => onChange({ ...values, weight: ev.target.value }) })
      ),
      e("div", { style: { display: "flex", gap: 8, marginTop: 10 } },
        e("input", { style: { ...styles.input, flex: 1 }, placeholder: "Notes (optional)", value: values.notes, onChange: (ev) => onChange({ ...values, notes: ev.target.value }) })
      ),
      // Sept 14 2026, Jimmy: "can we do the same when the trainer wants to
      // assign a program for a client... when i add an exercise i want the
      // same tab to save and add another" — same "Save & add another"
      // pattern as the workout-log's New exercise sheet. Only makes sense
      // while adding a brand-new exercise (to an existing day, or as the
      // first exercise of a new day), not while editing one that already
      // exists.
      !isEditing && e("button", {
        type: "button",
        style: { ...styles.exSheetSaveAddAnotherBtn, ...(saving ? styles.btnDisabled : {}) },
        onClick: () => onSave(true), disabled: saving
      }, e(Icon, { name: "plus", size: 15, strokeWidth: 3 }), saving ? "Saving…" : "Save & add another"),
      savedFlash && e("div", { style: { display: "flex", alignItems: "center", gap: 6, color: C.good, fontSize: 12.5, fontWeight: 600, marginTop: 10 } },
        e(Icon, { name: "check", size: 14, color: C.good }), "Added — add the next exercise below."
      ),
      e("div", { style: { display: "flex", gap: 8, marginTop: 10 } },
        e("button", { style: { ...styles.saveBtn, marginTop: 0, flex: 1, ...(saving ? styles.btnDisabled : {}) }, disabled: saving, onClick: () => onSave(false) }, saving ? "Saving…" : isEditing ? saveLabel : "Finish & close"),
        e("button", { style: { ...styles.demoLinkBtn, padding: "0 10px" }, onClick: onCancel }, "Cancel")
      )
    );
  }

export { ExerciseForm };
