// @generated by tools/extract/extract.py — bodies copied verbatim from index.html
import { fetchExerciseGif, notifyClient, saveManualExerciseGif } from "../../data/queries.js";
import { PROGRAM_PRICE } from "../../domain/access.js";
import { PROGRAM_REQUEST_TABS, exerciseGifKey, parseBulkExerciseLines, summarizeVoiceSets, youtubeSearchUrl } from "../../domain/rules.js";
import { sb } from "../../platform/supabase.js";
import { todayISO } from "../../shared/lib/dates.js";
import { fmtDate, fmtTime } from "../../shared/lib/format.js";
import { e } from "../../shared/react.js";
import { C, styles, withAlpha } from "../../shared/theme.js";
import { Dot, Icon, MUSCLE_COLORS, RestTimerChip, Segmented, Select } from "../../shared/ui/cross.js";
import { ExerciseLibraryEmptyArt, ProgramsEmptyArt } from "../../shared/ui/empty-art.js";
import { ExerciseDemo, ExerciseIcon, ExercisePicker, SmartVoiceEntryButton } from "../../shared/widgets/index.js";
import React, { useEffect, useMemo, useRef, useState } from "react";

  function ExerciseLibraryPanel() {
    const [loading, setLoading] = useState(true);
    const [items, setItems] = useState([]);
    const [results, setResults] = useState({});
    const [filter, setFilter] = useState("all");
    const [editingKey, setEditingKey] = useState(null);
    const [manualUrl, setManualUrl] = useState("");
    const [bulkOpen, setBulkOpen] = useState(false);
    const [bulkText, setBulkText] = useState("");
    const [bulkSaving, setBulkSaving] = useState(false);
    const [bulkResult, setBulkResult] = useState(null);

    useEffect(() => {
      if (!sb) { setLoading(false); return; }
      let cancelled = false;
      (async () => {
        const [progRes, entryRes] = await Promise.all([
          sb.from("program_exercises").select("exercise"),
          sb.from("workout_entries").select("exercise")
        ]);
        // Count how many times each exercise shows up across programs + logged
        // workouts — a proxy for how many clients actually see it — so the list
        // can be sorted highest-impact-first. Filling in the demo for something
        // used 40 times matters a lot more than something used once.
        const seen = new Map();
        const counts = new Map();
        [...(progRes.data || []), ...(entryRes.data || [])].forEach((r) => {
          const raw = ((r && r.exercise) || "").trim();
          if (!raw) return;
          const key = exerciseGifKey(raw);
          counts.set(key, (counts.get(key) || 0) + 1);
          if (!seen.has(key)) seen.set(key, raw);
        });
        const list = [...seen.entries()]
          .map(([key, name]) => ({ key, name, count: counts.get(key) || 0 }))
          .sort((a, b) => b.count - a.count || a.name.localeCompare(b.name));
        if (cancelled) return;
        setItems(list);
        const found = await Promise.all(list.map(async (item) => [item.key, await fetchExerciseGif(item.name)]));
        if (cancelled) return;
        const map = {};
        found.forEach(([key, r]) => { map[key] = r; });
        setResults(map);
        setLoading(false);
      })();
      return () => { cancelled = true; };
    }, []);

    async function handleSaveManual(item) {
      if (!manualUrl.trim()) return;
      await saveManualExerciseGif(item.name, manualUrl.trim());
      setResults((prev) => ({ ...prev, [item.key]: { gifUrl: manualUrl.trim(), frame2Url: null, matchedName: null } }));
      setEditingKey(null);
      setManualUrl("");
    }

    // Matches each pasted line against the exercises already in this library
    // (same normalized-key lookup used everywhere else) so a manager pasting a
    // list from a spreadsheet gets an instant "matched" / "not found" preview
    // before anything is saved.
    const bulkParsed = useMemo(() => {
      return parseBulkExerciseLines(bulkText).map((row) => {
        if (!row.url) return { ...row, status: "error", reason: "Couldn't find a link on this line" };
        if (!row.name) return { ...row, status: "error", reason: "Couldn't find an exercise name on this line" };
        const key = exerciseGifKey(row.name);
        const exact = items.find((it) => it.key === key);
        const fuzzy = !exact ? items.find((it) => it.key.startsWith(key) || key.startsWith(it.key)) : null;
        const match = exact || fuzzy;
        if (!match) return { ...row, status: "error", reason: `No exercise named "${row.name}" in your library — check the spelling` };
        return { ...row, status: "ok", match };
      });
    }, [bulkText, items]);
    const bulkOkRows = bulkParsed.filter((r) => r.status === "ok");

    async function handleBulkSave() {
      if (!bulkOkRows.length || bulkSaving) return;
      setBulkSaving(true);
      await Promise.all(bulkOkRows.map((row) => saveManualExerciseGif(row.match.name, row.url)));
      setResults((prev) => {
        const next = { ...prev };
        bulkOkRows.forEach((row) => { next[row.match.key] = { gifUrl: row.url, frame2Url: null, matchedName: null }; });
        return next;
      });
      setBulkResult({ savedCount: bulkOkRows.length });
      setBulkText("");
      setBulkSaving(false);
    }

    if (loading) return e("div", { style: styles.empty }, e("p", { style: styles.emptyText }, "Checking every exercise for a demo…"));
    if (!items.length) return e("div", { style: styles.empty }, e(ExerciseLibraryEmptyArt, {}), e("p", { style: styles.emptyText }, "No exercises yet — once your programs or logged workouts have some, they'll show up here."));

    const missingCount = items.filter((item) => !(results[item.key] && results[item.key].gifUrl)).length;
    const filtered = items.filter((item) => {
      const has = !!(results[item.key] && results[item.key].gifUrl);
      if (filter === "missing") return !has;
      if (filter === "found") return has;
      return true;
    });

    return e("div", null,
      e("p", { style: { ...styles.profileGoalText, marginBottom: 12 } },
        `${items.length} exercise${items.length === 1 ? "" : "s"} used across your programs and logs — `,
        missingCount === 0 ? "every one has a demo." : `${missingCount} still missing a demo.`,
        missingCount > 0 && " Sorted by how often each one's used, so the ones your clients see most are at the top — you don't need to work through the whole list, just as far down as feels worth it."
      ),
      e("div", { style: { display: "flex", gap: 10, alignItems: "flex-end", flexWrap: "wrap", marginBottom: 14 } },
        e("div", { style: { maxWidth: 240, flex: 1, minWidth: 200 } },
          e(Select, {
            value: filter, onChange: setFilter,
            options: [
              { value: "all", label: "All exercises" },
              { value: "missing", label: `Missing a demo (${missingCount})` },
              { value: "found", label: `Has a demo (${items.length - missingCount})` }
            ]
          })
        ),
        !bulkOpen && e("button", { style: { ...styles.demoLinkBtn, marginTop: 0 }, onClick: () => { setBulkOpen(true); setBulkResult(null); } }, "+ Bulk add links")
      ),
      bulkOpen && e("div", { style: { ...styles.clientCard, flexDirection: "column", alignItems: "stretch", gap: 10, cursor: "default", marginBottom: 14 } },
        e("div", null,
          e("span", { style: styles.exerciseName }, "Bulk add demo links"),
          e("p", { style: { ...styles.muscleSubText, marginTop: 4 } },
            "Paste one exercise per line, name then link — works with a dash, colon, comma, or a tab pasted straight from a spreadsheet."
          )
        ),
        e("textarea", {
          style: { ...styles.input, minHeight: 120, fontFamily: "'JetBrains Mono', monospace", fontSize: 12.5, resize: "vertical" },
          placeholder: "Bench Press - https://youtu.be/abc123\nSquat - https://youtu.be/def456",
          value: bulkText,
          onChange: (ev) => { setBulkText(ev.target.value); setBulkResult(null); }
        }),
        bulkParsed.length > 0 && e("div", { style: { display: "flex", flexDirection: "column", gap: 5, maxHeight: 170, overflowY: "auto", padding: "2px 0" } },
          bulkParsed.map((row, i) => e("div", { key: i, style: { display: "flex", alignItems: "flex-start", gap: 6, fontSize: 12.5 } },
            e("span", { style: { marginTop: 2, flexShrink: 0 } }, e(Icon, { name: row.status === "ok" ? "check" : "alert", size: 12, color: row.status === "ok" ? C.good : C.critical })),
            e("span", { style: { color: row.status === "ok" ? C.ink2 : C.critical, lineHeight: 1.4 } },
              row.status === "ok" ? `${row.match.name} → link added` : row.reason
            )
          ))
        ),
        bulkResult && e("span", { style: { ...styles.demoNote, color: C.brand } },
          `Saved ${bulkResult.savedCount} link${bulkResult.savedCount === 1 ? "" : "s"}.`
        ),
        e("div", { style: { display: "flex", gap: 8 } },
          e("button", {
            style: { ...styles.saveBtn, width: "auto", flex: 1, marginTop: 0, padding: "11px", opacity: bulkOkRows.length && !bulkSaving ? 1 : 0.5 },
            disabled: !bulkOkRows.length || bulkSaving,
            onClick: handleBulkSave
          }, bulkSaving ? "Saving…" : `Save ${bulkOkRows.length} link${bulkOkRows.length === 1 ? "" : "s"}`),
          e("button", {
            style: { ...styles.demoLinkBtn, marginTop: 0, color: C.ink3, flexShrink: 0 },
            onClick: () => { setBulkOpen(false); setBulkText(""); setBulkResult(null); }
          }, "Close")
        )
      ),
      filtered.length === 0
        ? e("p", { style: styles.emptyText }, "Nothing matches that filter.")
        : e("div", { style: { display: "flex", flexDirection: "column", gap: 8 } }, filtered.map((item) => {
            const r = results[item.key];
            const has = !!(r && r.gifUrl);
            const isEditing = editingKey === item.key;
            return e("div", { key: item.key, style: { ...styles.clientCard, alignItems: "center" } },
              e("div", { style: { display: "flex", alignItems: "center", gap: 10, flex: 1, minWidth: 0 } },
                has
                  ? e("img", { src: r.gifUrl, alt: "", style: { width: 34, height: 34, borderRadius: 8, objectFit: "cover", flexShrink: 0, background: "#0B1526" } })
                  : e("div", { style: { width: 34, height: 34, borderRadius: 8, background: withAlpha(C.critical, 0.1), display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0 } },
                      e(Icon, { name: "alert", size: 14, color: C.critical })
                    ),
                e("div", { style: { display: "flex", flexDirection: "column", minWidth: 0 } },
                  e("span", { style: styles.exerciseName }, item.name),
                  e("span", { style: styles.muscleSubText },
                    `Used ${item.count}×`, " · ",
                    has ? (r.matchedName ? `Matched: "${r.matchedName}"` : "Custom link") : "No demo found"
                  )
                )
              ),
              !isEditing
                ? e("div", { style: { display: "flex", gap: 12, alignItems: "center", flexShrink: 0 } },
                    !has && e("a", { href: youtubeSearchUrl(item.name), target: "_blank", rel: "noopener noreferrer", style: { ...styles.demoLinkBtn, marginTop: 0 } }, "Search ↗"),
                    e("button", { style: { ...styles.demoLinkBtn, marginTop: 0 }, onClick: () => { setEditingKey(item.key); setManualUrl(""); } }, has ? "Change" : "+ Add link")
                  )
                : e("div", { style: { display: "flex", gap: 6, alignItems: "center", flexShrink: 0 } },
                    e("input", {
                      style: { ...styles.input, width: 150 }, placeholder: "YouTube or image URL",
                      value: manualUrl, onChange: (ev) => setManualUrl(ev.target.value)
                    }),
                    e("button", { style: { ...styles.demoLinkBtn, marginTop: 0, padding: "0 6px" }, onClick: () => handleSaveManual(item) }, "Save"),
                    e("button", { style: { ...styles.demoLinkBtn, marginTop: 0, padding: "0 6px", color: C.ink3 }, onClick: () => setEditingKey(null) }, "✕")
                  )
            );
          }))
    );
  }

  function ExerciseContent({ entry, maxW, unit, onEdit, onDelete, onDuplicate, onDeleteSet }) {
    const mColor = MUSCLE_COLORS[entry.muscleGroup] || MUSCLE_COLORS["Full Body"];
    // Sept 12 2026, Jimmy: design audit — see deleteConfirmBar's comment.
    // Local to this card, so confirming/cancelling one entry never affects
    // any other entry's delete button.
    const [confirmDelete, setConfirmDelete] = useState(false);
    // Sept 12 2026, Jimmy: "can we make the workout exercise look to look
    // like this" — same safer-delete treatment one level down, per SET
    // row, not just the whole entry: which row (if any) currently has its
    // inline "are you sure" open. Only one at a time per card.
    const [confirmSetIdx, setConfirmSetIdx] = useState(null);
    const entryTime = fmtTime(entry.createdAt);
    // Sept 13 2026, Jimmy: "cant open it" — lets tapping the small icon
    // below open the same ExerciseDemo panel as its own "Show demo" button.
    const demoRef = useRef(null);
    return e(React.Fragment, null,
      e("div", { style: styles.cardHeader },
        e("div", { style: { display: "flex", alignItems: "flex-start", gap: 8, minWidth: 0 } },
          // Sept 13 2026, Jimmy: same always-visible consistent-style icon
          // as the Programs tab rows — was only wired into the program
          // builder at first; adding it here too so a logged entry's
          // exercise also shows it, not just "Show demo" below.
          e(ExerciseIcon, { name: entry.exercise, size: 36, onOpen: () => demoRef.current && demoRef.current.open() }),
          e("div", { style: styles.cardHeaderLeft },
            e("span", { style: styles.exerciseName }, entry.exercise),
            e("span", { style: styles.muscleTag }, e(Dot, { color: mColor, size: 7 }), entry.muscleGroup || "Full Body"),
            entry.createdAt && fmtTime(entry.createdAt) && e("span", { style: styles.entryTime }, e(Icon, { name: "clock", size: 10 }), fmtTime(entry.createdAt))
          )
        ),
        (onEdit || onDelete || onDuplicate) && e("div", { style: styles.cardHeaderActions },
          onDuplicate && e("button", { style: styles.editBtn, onClick: () => onDuplicate(entry), "aria-label": "Duplicate entry", title: "Duplicate this as a new entry today" }, e(Icon, { name: "copy", size: 14 })),
          onEdit && e("button", { style: styles.editBtn, onClick: () => onEdit(entry), "aria-label": "Edit entry" }, e(Icon, { name: "edit", size: 14 })),
          onDelete && e("button", { style: { ...styles.deleteBtn, padding: 7 }, onClick: () => setConfirmDelete(true), "aria-label": "Delete entry" }, e(Icon, { name: "trash", size: 15 }))
        )
      ),
      confirmDelete && e("div", { style: styles.deleteConfirmBar },
        e("span", { style: styles.deleteConfirmText }, "Delete this entry? Can't be undone."),
        e("div", { style: { display: "flex", gap: 6, flexShrink: 0 } },
          e("button", { style: { ...styles.confirmCancelBtn, flex: "none", padding: "7px 14px", fontSize: 12 }, onClick: () => setConfirmDelete(false) }, "Cancel"),
          e("button", { style: { ...styles.confirmDangerBtn, flex: "none", padding: "7px 14px", fontSize: 12 }, onClick: () => onDelete(entry.id) }, "Delete")
        )
      ),
      e("div", { style: styles.setListCol }, entry.sets.map((s, i) => {
        // Sept 10 2026, Jimmy: "add an option to set the timing and also if
        // im doing the exercise a body weight" — timed sets (planks, wall
        // sits) carry a `duration` (seconds) instead of `reps`, and
        // bodyweight sets carry `isBodyweight` with weight forced to 0.
        // Neither should count toward a weight PR badge — a bodyweight set's
        // weight is 0 by definition, not an actual lift.
        const isTimedSet = !!s.isTimed;
        const isBW = !!s.isBodyweight;
        const isPR = !isTimedSet && !isBW && maxW > 0 && s.weight === maxW;
        const amount = isTimedSet ? (s.duration != null ? s.duration : s.reps) : s.reps;
        const setLabel = e(React.Fragment, null,
          isPR && e(Icon, { name: "sparkle", size: 10, strokeWidth: 2.5, color: C.brand }),
          amount, isTimedSet ? "s" : " × ",
          isTimedSet ? null : (isBW ? "Bodyweight" : `${s.weight}${unit}`),
          isPR && e("span", { style: styles.setListPRTag }, " — PR")
        );
        const isConfirming = confirmSetIdx === i;
        // Sept 14 2026, Jimmy: "the red delete button is not correct and i
        // cant click it in new exercise logs" — a freshly logged exercise
        // almost always has exactly one set at first, and this button used
        // to be silently disabled (dimmed + a hover-only tooltip explaining
        // why — no help on a phone, where there's no hover) whenever it was
        // the exercise's only set, since an exercise can't be left with
        // zero sets. From Jimmy's side that just looked like a broken
        // button that didn't respond to taps. It's tappable now regardless
        // of set count; tapping it on the last remaining set offers to
        // delete the whole exercise instead (below), which is the only
        // thing "delete this one and only set" could actually mean anyway.
        const isOnlySet = entry.sets.length <= 1;
        return e("div", { key: i, style: { ...styles.setListRow, ...(isConfirming ? styles.setListRowActive : {}) } },
          e("span", { style: styles.setIndex }, i + 1),
          isConfirming
            ? e(React.Fragment, null,
                e("div", { style: { flex: 1, minWidth: 0 } },
                  e("div", { style: styles.setListTextStrike }, setLabel),
                  e("span", { style: styles.deleteConfirmText },
                    isOnlySet ? "This is the only set — delete the whole exercise instead?" : "Delete this set? Can't be undone."
                  )
                ),
                e("div", { style: { display: "flex", gap: 6, flexShrink: 0 } },
                  e("button", { type: "button", style: styles.setConfirmCancelBtn, onClick: () => setConfirmSetIdx(null) }, "Cancel"),
                  e("button", {
                    type: "button", style: styles.setConfirmDangerBtn,
                    onClick: () => {
                      if (isOnlySet) { if (onDelete) onDelete(entry.id); } else { onDeleteSet(entry.id, i); }
                      setConfirmSetIdx(null);
                    }
                  }, isOnlySet ? "Delete exercise" : "Delete")
                )
              )
            : e(React.Fragment, null,
                e("span", { style: styles.setListText }, setLabel, s.rest ? e(RestTimerChip, { seconds: s.rest }) : null),
                entryTime && e("span", { style: styles.setListTime }, entryTime),
                onDeleteSet && e("button", {
                  type: "button",
                  style: styles.setDeleteBtn,
                  onClick: () => setConfirmSetIdx(i),
                  "aria-label": isOnlySet ? "Delete this exercise" : "Delete this set",
                  title: isOnlySet ? "This is the only set — delete the whole exercise instead" : "Delete this set"
                }, e(Icon, { name: "trash", size: 14 }))
              )
        );
      })),
      e(ExerciseDemo, { name: entry.exercise, ref: demoRef })
    );
  }

  // A single pending program-payment request, with its own inline "mark as
  // paid" form — same $35 default and same writes ProgramPaymentCard's own
  // button does (client_program_assignments.paid + a client_payments row),
  // just reachable from one central list instead of that client's own page.
  function ProgramRequestRow({ req, programName, clientProfile, onIncrementTotalDue = null, onResolved }) {
    const [unlocking, setUnlocking] = useState(false);
    const [amount, setAmount] = useState(String(PROGRAM_PRICE));
    const [date, setDate] = useState(todayISO());
    const [saving, setSaving] = useState(false);
    const [declining, setDeclining] = useState(false);
    const [error, setError] = useState("");
    // Sept 13 2026, Jimmy: inline "are you sure" instead of window.confirm().
    const [confirmDecline, setConfirmDecline] = useState(false);

    // Client picked a program then changed their mind before paying — this
    // just removes the pick entirely (same delete client_program_assignments
    // does from the client's own trash icon), so it drops off this list
    // without ever being charged. Doesn't touch client_payments, since
    // nothing was ever paid here.
    async function handleDecline() {
      if (!sb) return;
      setConfirmDecline(false);
      setDeclining(true);
      const { error: err } = await sb.from("client_program_assignments").delete().eq("id", req.id);
      setDeclining(false);
      if (err) { setError("Couldn't remove: " + err.message); return; }
      onResolved(req.id);
    }

    async function handleUnlock() {
      setError("");
      const amt = Number(amount);
      if (!amount || isNaN(amt) || amt <= 0) { setError("Enter a valid amount."); return; }
      if (!date) { setError("Pick a date."); return; }
      if (!sb) { setError("Backend not configured yet."); return; }
      setSaving(true);
      const { data: updated, error: err } = await sb.from("client_program_assignments").update({ paid: true, paid_at: date }).eq("id", req.id).select();
      if (err) { setSaving(false); setError("Couldn't save: " + err.message); return; }
      if (!updated || updated.length === 0) { setSaving(false); setError("Save was blocked by a permissions rule (0 rows updated) — this needs a database fix, not a retry. Tell your developer: RLS blocked update on client_program_assignments."); return; }
      // Log it as a real payment, same ledger as everything else this client pays.
      if (clientProfile && clientProfile.user_id) {
        await sb.from("client_payments").insert([{ user_id: clientProfile.user_id, client_name: req.client_name, amount: amt, paid_on: date, note: `Program: ${programName || "Program"}`, program_id: req.program_id || null }]);
        // Sept 19 2026 inspection fix: same bug class the diet-plan unlock
        // fix closed a round ago — this logged the payment but never
        // bumped total_due, so approving a program pick here made the
        // client's shown balance go DOWN by the unlock amount (a payment
        // against nothing) instead of being a separate charge added on
        // top of what they already owe.
        if (onIncrementTotalDue) onIncrementTotalDue(clientProfile.id, amt);
        notifyClient(clientProfile.user_id, `Your program${programName ? ` "${programName}"` : ""} is ready — check your Programs tab.`);
      }
      setSaving(false);
      onResolved(req.id);
    }

    return e("div", { style: styles.trainerStatCard },
      e("div", { style: { display: "flex", flexDirection: "column", gap: 4, marginBottom: 10 } },
        e("span", { style: styles.exerciseName }, req.client_name || "Unknown client"),
        clientProfile && clientProfile.phone && e("span", { style: { ...styles.muscleSubText, fontFamily: "'JetBrains Mono', monospace" } }, clientProfile.phone),
        e("span", { style: styles.muscleSubText },
          programName ? `picked "${programName}" on ` : "picked a program on ",
          fmtDate((req.assigned_at || "").slice(0, 10))
        )
      ),
      error && e("span", { style: { ...styles.inlineError, display: "block", marginBottom: 8 } }, error),
      unlocking
        ? e("div", null,
            e("label", { style: { ...styles.formLabel, marginTop: 0 } }, "Amount received"),
            e("input", { style: styles.input, type: "number", placeholder: "Amount", value: amount, onChange: (ev) => setAmount(ev.target.value) }),
            e("input", { style: { ...styles.input, marginTop: 8 }, type: "date", value: date, onChange: (ev) => setDate(ev.target.value) }),
            e("div", { style: { display: "flex", gap: 8, marginTop: 10 } },
              e("button", { style: { ...styles.saveBtn, marginTop: 0, flex: 1, ...(saving ? styles.btnDisabled : {}) }, disabled: saving, onClick: handleUnlock }, saving ? "Saving…" : "Mark as paid & unlock"),
              e("button", { style: { ...styles.demoLinkBtn, padding: "0 10px" }, onClick: () => { setUnlocking(false); setError(""); setAmount(String(PROGRAM_PRICE)); } }, "Cancel")
            )
          )
        : confirmDecline
        ? e("div", { style: styles.deleteConfirmBar },
            e("span", { style: styles.deleteConfirmText }, `Remove this pick of ${programName || "this program"}?`),
            e("div", { style: { display: "flex", gap: 6, flexShrink: 0 } },
              e("button", { type: "button", style: styles.setConfirmCancelBtn, onClick: () => setConfirmDecline(false) }, "Cancel"),
              e("button", { type: "button", style: { ...styles.setConfirmDangerBtn, ...(declining ? styles.btnDisabled : {}) }, disabled: declining, onClick: handleDecline }, declining ? "…" : "Remove")
            )
          )
        : e("div", { style: { display: "flex", gap: 8 } },
            e("button", { style: { ...styles.saveBtn, marginTop: 0, flex: 1 }, onClick: () => setUnlocking(true) }, `Mark as paid ($${PROGRAM_PRICE}) →`),
            e("button", { style: styles.deleteBtn, onClick: () => setConfirmDecline(true), "aria-label": "Remove this request" }, e(Icon, { name: "trash", size: 14 }))
          )
    );
  }

  // Queue of pending program picks from self-train clients (no trainer) who've
  // chosen a program from the library but haven't paid for it yet — same idea
  // as DietPlanRequestsPanel, centralized here instead of hunting through each
  // client's own Programs tab. Trainer-owned clients never show up (filtered
  // out one level up, in selfTrainProgramRequests — programs are free/ungated
  // for them, so an unpaid row there was never actually "a request").
  //
  // Also doubles as the paid-vs-unpaid roster Jimmy asked for: a "Paid" tab
  // lists every program payment on record (paidPayments, sourced off
  // allPayments up in the Owner view — no separate fetch), with a running
  // total, so it's a one-stop place to see who's requested, who's already
  // paid, and how much programs have brought in.
  function ProgramRequestsPanel({ requests, paidPayments = [], profiles, onResolved, onDeletePayment, onIncrementTotalDue = null }) {
    const [tab, setTab] = useState("pending");
    const [programs, setPrograms] = useState([]);
    useEffect(() => {
      if (!sb) return;
      sb.from("training_programs").select("id, name, style").then(({ data, error: err }) => {
        if (!err && data) setPrograms(data);
      });
    }, []);

    const paidTotal = useMemo(() => paidPayments.reduce((sum, p) => sum + (Number(p.amount) || 0), 0), [paidPayments]);
    // Sept 14 2026, Jimmy: "same here" — same search box added to the Diet
    // plan requests Paid list, mirrored here.
    const [paidSearch, setPaidSearch] = useState("");
    const visiblePaidPayments = useMemo(() => {
      const q = paidSearch.trim().toLowerCase();
      if (!q) return paidPayments;
      return paidPayments.filter((p) => (p.client_name || "").toLowerCase().includes(q));
    }, [paidPayments, paidSearch]);

    return e("div", null,
      e(Segmented, {
        options: PROGRAM_REQUEST_TABS.map((t) => ({
          ...t,
          label: t.value === "pending" ? (requests.length > 0 ? `${t.label} (${requests.length})` : t.label) : (paidPayments.length > 0 ? `${t.label} (${paidPayments.length})` : t.label)
        })),
        value: tab, onChange: setTab
      }),
      tab === "pending"
        ? (requests.length === 0
            ? e("div", { style: { ...styles.empty, marginTop: 14 } }, e(ProgramsEmptyArt, {}), e("p", { style: styles.emptyText }, "No pending program requests."))
            : e("div", { style: { display: "flex", flexDirection: "column", gap: 10, marginTop: 14 } },
                requests.map((req) => {
                  const prog = req.program_id ? programs.find((p) => p.id === req.program_id) : null;
                  const clientProfile = profiles.find((p) => p.id === req.client_id) || null;
                  return e(ProgramRequestRow, { key: req.id, req, programName: prog ? `${styleLabel(prog.style)} — ${prog.name}` : null, clientProfile, onIncrementTotalDue, onResolved });
                })
              )
          )
        : (paidPayments.length === 0
            ? e("div", { style: { ...styles.empty, marginTop: 14 } }, e(ProgramsEmptyArt, {}), e("p", { style: styles.emptyText }, "No program payments logged yet."))
            : e("div", { style: { marginTop: 14 } },
                e("div", { style: styles.dashGrid },
                  e("div", { style: styles.dashTile }, e("span", { style: styles.profileLabel }, "Collected"), e("span", { style: styles.dashTileValue }, `$${paidTotal.toLocaleString()}`)),
                  e("div", { style: styles.dashTile }, e("span", { style: styles.profileLabel }, "Clients"), e("span", { style: styles.dashTileValue }, String(paidPayments.length)))
                ),
                e("div", { style: { display: "flex", alignItems: "center", justifyContent: "space-between", marginTop: 14, marginBottom: 4 } },
                  e("div", { style: styles.rosterSearchWrap },
                    e(Icon, { name: "search", size: 14, color: C.ink3 }),
                    e("input", {
                      style: styles.rosterSearchInput, type: "text", value: paidSearch,
                      onChange: (ev) => setPaidSearch(ev.target.value),
                      placeholder: "Search by name…"
                    }),
                    paidSearch && e("button", {
                      type: "button", onClick: () => setPaidSearch(""), style: styles.rosterSearchClear, "aria-label": "Clear search"
                    }, e(Icon, { name: "x", size: 12, color: C.ink3 }))
                  ),
                  e("span", { style: styles.rosterCount }, visiblePaidPayments.length, "/", paidPayments.length)
                ),
                visiblePaidPayments.length === 0
                  ? e("div", { style: styles.empty }, e("p", { style: styles.emptyText }, `No payments match "${paidSearch.trim()}".`))
                  : e("div", { style: { display: "flex", flexDirection: "column", gap: 10, marginTop: 10 } },
                      visiblePaidPayments.map((p) => {
                        const prog = p.program_id ? programs.find((pr) => pr.id === p.program_id) : null;
                        return e("div", { key: p.id, style: styles.trainerStatCard },
                          e("div", { style: { display: "flex", justifyContent: "space-between", alignItems: "flex-start", gap: 8 } },
                            e("div", { style: { display: "flex", flexDirection: "column", gap: 3 } },
                              e("span", { style: styles.exerciseName }, p.client_name || "Unknown client"),
                              e("span", { style: styles.muscleSubText }, prog ? `${styleLabel(prog.style)} — ${prog.name}` : (p.note || "Program"))
                            ),
                            e("div", { style: { display: "flex", alignItems: "center", gap: 10 } },
                              e("div", { style: { display: "flex", flexDirection: "column", alignItems: "flex-end", gap: 3 } },
                                e("span", { style: styles.rosterVol }, `$${Number(p.amount).toLocaleString()}`),
                                e("span", { style: styles.muscleSubText }, fmtDate((p.paid_on || "").slice(0, 10)))
                              ),
                              onDeletePayment && e("button", {
                                style: styles.deleteBtn, onClick: () => onDeletePayment(p), "aria-label": "Delete payment", title: "Delete payment"
                              }, e(Icon, { name: "trash", size: 15 }))
                            )
                          )
                        );
                      })
                    )
              )
          )
    );
  }

  function ExerciseForm({ values, onChange, onSave, onCancel, saving, showDayField, showWeekField, showWeightField, saveLabel = "Save", isEditing = false, savedFlash = false }) {
    return e("div", { style: { ...styles.sessionForm, marginTop: 10, marginBottom: 0 } },
      // Same one-mic "speak the whole exercise" experience as the Log
      // feature's New Exercise form. This form used to also have small
      // per-field mics on the Exercise picker, Day label, and Notes — so
      // speaking a full exercise into whichever one was handy just dumped
      // the raw sentence as plain text into that one field, instead of
      // splitting it out (Jimmy, Sept 9 2026: "one speaker... not many one
      // like the one in log"). Those per-field mics are now switched off
      // (see showMic: false below, and the Day label/Notes fields further
      // down) so this is the ONLY mic in the form, exactly matching the Log
      // feature's mic surface. This uses the same voice-log-entry parsing,
      // then reshapes its per-set array into this form's compact string
      // fields via summarizeVoiceSets above.
      e(SmartVoiceEntryButton, {
        label: "Speak this exercise — name, sets, weight",
        onParsed: (result) => {
          const next = { ...values };
          if (showDayField && result.workoutTitle && !values.dayLabel) next.dayLabel = result.workoutTitle;
          if (result.exerciseName) next.exercise = result.exerciseName;
          if (Array.isArray(result.sets) && result.sets.length) {
            const summary = summarizeVoiceSets(result.sets);
            if (summary.setsReps) next.setsReps = summary.setsReps;
            if (summary.rest) next.rest = summary.rest;
            if (showWeightField && summary.weight) next.weight = summary.weight;
          }
          onChange(next);
        }
      }),
      // Only ClientCustomProgramCard's trainer-written, client-specific
      // programs pass showWeekField — the shared TRAINING_STYLES library
      // above has no week concept, so every existing call site here leaves
      // it undefined and sees no change.
      showWeekField && e("div", { style: { display: "flex", gap: 8 } },
        e("input", {
          style: { ...styles.input, flex: 1 }, placeholder: "Week label (e.g. Week 1)",
          value: values.weekLabel, onChange: (ev) => onChange({ ...values, weekLabel: ev.target.value })
        })
      ),
      showDayField && e("div", { style: { display: "flex", gap: 8, marginTop: showWeekField ? 10 : 0 } },
        e("input", {
          style: { ...styles.input, flex: 1 }, placeholder: "Day label (e.g. Day 1 — Squat)",
          value: values.dayLabel, onChange: (ev) => onChange({ ...values, dayLabel: ev.target.value })
        })
      ),
      e("div", { style: (showDayField || showWeekField) ? { marginTop: 10 } : {} },
        // Sept 9 2026: this field's own mic is switched off here, same as the
        // Log form already does — the SmartVoiceEntryButton above is now the
        // one and only mic in this form (matching Jimmy's "one speaker, not
        // many like the log" ask), so a second mic that only fills the raw
        // spoken sentence into this one field would just be confusing again.
        e(ExercisePicker, {
          value: values.exercise, placeholder: "Search exercises… e.g. Bench Press",
          onSelect: (name) => onChange({ ...values, exercise: name }),
          showMic: false
        })
      ),
      e("div", { style: { display: "flex", gap: 8, marginTop: 10 } },
        e("input", { style: { ...styles.input, flex: 1 }, placeholder: "Sets x reps (e.g. 3x8)", value: values.setsReps, onChange: (ev) => onChange({ ...values, setsReps: ev.target.value }) }),
        e("input", { style: { ...styles.input, flex: 1 }, placeholder: "Rest (sec)", type: "number", min: "0", value: values.rest, onChange: (ev) => onChange({ ...values, rest: ev.target.value }) })
      ),
      showWeightField && e("div", { style: { marginTop: 10 } },
        e("input", { style: styles.input, placeholder: "Weight, kg — per set, e.g. 70x70x90 (optional)", type: "text", inputMode: "decimal", value: values.weight || "", onChange: (ev) => onChange({ ...values, weight: ev.target.value }) })
      ),
      e("div", { style: { display: "flex", gap: 8, marginTop: 10 } },
        e("input", { style: { ...styles.input, flex: 1 }, placeholder: "Notes (optional)", value: values.notes, onChange: (ev) => onChange({ ...values, notes: ev.target.value }) })
      ),
      // Sept 14 2026, Jimmy: "can we do the same when the trainer wants to
      // assign a program for a client... when i add an exercise i want the
      // same tab to save and add another" — same "Save & add another"
      // pattern as the workout-log's New exercise sheet. Only makes sense
      // while adding a brand-new exercise (to an existing day, or as the
      // first exercise of a new day), not while editing one that already
      // exists.
      !isEditing && e("button", {
        type: "button",
        style: { ...styles.exSheetSaveAddAnotherBtn, ...(saving ? styles.btnDisabled : {}) },
        onClick: () => onSave(true), disabled: saving
      }, e(Icon, { name: "plus", size: 15, strokeWidth: 3 }), saving ? "Saving…" : "Save & add another"),
      savedFlash && e("div", { style: { display: "flex", alignItems: "center", gap: 6, color: C.good, fontSize: 12.5, fontWeight: 600, marginTop: 10 } },
        e(Icon, { name: "check", size: 14, color: C.good }), "Added — add the next exercise below."
      ),
      e("div", { style: { display: "flex", gap: 8, marginTop: 10 } },
        e("button", { style: { ...styles.saveBtn, marginTop: 0, flex: 1, ...(saving ? styles.btnDisabled : {}) }, disabled: saving, onClick: () => onSave(false) }, saving ? "Saving…" : isEditing ? saveLabel : "Finish & close"),
        e("button", { style: { ...styles.demoLinkBtn, padding: "0 10px" }, onClick: onCancel }, "Cancel")
      )
    );
  }

  // Sept 11 2026, Jimmy: "add the option to add bodyweight or seconds like
  // we did in log", "one option to add one weight theres no like for each
  // set", "no back arrow", and editing an exercise "goes to a alone
  // exercise with the same title but seperate" — this replaces the old
  // compact "3x8" + single weight-string fields, used only by
  // ClientCustomProgramCard below, with the exact same per-set grid the Log
  // tab already has: one row per set (its own reps-or-seconds, its own
  // weight, its own rest), plus the same Timed/Bodyweight toggle. Editing an
  // exercise never shows Week/Day fields at all (those don't change on a
  // per-exercise edit — only the "add" version of this form ever needs
  // them), and `contextLabel`, when set, renders a small "editing under
  // Week X · Day Y" breadcrumb plus a proper back-style Cancel control
  // instead of a bare text link — so editing reads as "still inside this
  // day," not as a new, disconnected entry with nothing to click to leave.
  function ProgramSetsForm({ values, onChange, onSave, onCancel, saving, showWeekField, showDayField, saveLabel = "Save", contextLabel, savedFlash = false }) {
    function updateSet(i, field, v) {
      onChange({ ...values, sets: values.sets.map((s, idx) => (idx === i ? { ...s, [field]: v } : s)) });
    }
    // Sept 12 2026, Jimmy: "easier to add them" — same pre-fill-from-last-set
    // behavior as the workout-log sheets above.
    function addSet() {
      const last = values.sets.length > 0 ? values.sets[values.sets.length - 1] : null;
      onChange({ ...values, sets: [...values.sets, last ? { ...last } : { reps: "", weight: "", rest: "" }] });
    }
    function removeSet(i) {
      if (values.sets.length === 1) return;
      onChange({ ...values, sets: values.sets.filter((_, idx) => idx !== i) });
    }
    const isTimed = values.isTimed;
    const isBodyweight = values.isBodyweight;
    return e("div", { style: { ...styles.sessionForm, marginTop: 10, marginBottom: 0, ...(contextLabel ? { borderLeft: `2px solid ${C.brand}` } : {}) } },
      contextLabel && e("div", { style: { display: "flex", alignItems: "center", gap: 6, marginBottom: 10 } },
        e("span", { style: { fontFamily: "'JetBrains Mono', monospace", fontSize: 10.5, fontWeight: 700, color: C.ink3, letterSpacing: "0.05em", textTransform: "uppercase" } }, contextLabel)
      ),
      e(SmartVoiceEntryButton, {
        label: "Speak this exercise — name, sets, weight",
        onParsed: (result) => {
          const next = { ...values };
          if (result.exerciseName) next.exercise = result.exerciseName;
          if (Array.isArray(result.sets) && result.sets.length) {
            next.sets = result.sets.map((s) => ({ reps: s.reps != null ? String(s.reps) : "", weight: s.weight != null ? String(s.weight) : "", rest: s.rest != null ? String(s.rest) : "" }));
          }
          onChange(next);
        }
      }),
      showWeekField && e("div", { style: { display: "flex", gap: 8 } },
        e("input", { style: { ...styles.input, flex: 1 }, placeholder: "Week label (e.g. Week 1)", value: values.weekLabel, onChange: (ev) => onChange({ ...values, weekLabel: ev.target.value }) })
      ),
      showDayField && e("div", { style: { display: "flex", gap: 8, marginTop: showWeekField ? 10 : 0 } },
        e("input", { style: { ...styles.input, flex: 1 }, placeholder: "Day label (e.g. Day 1 — Squat)", value: values.dayLabel, onChange: (ev) => onChange({ ...values, dayLabel: ev.target.value }) })
      ),
      e("div", { style: (showDayField || showWeekField) ? { marginTop: 10 } : {} },
        e(ExercisePicker, { value: values.exercise, placeholder: "Search exercises… e.g. Bench Press", onSelect: (name) => onChange({ ...values, exercise: name }), showMic: false })
      ),
      e("div", { style: { display: "flex", alignItems: "center", justifyContent: "space-between", flexWrap: "wrap", gap: 8, marginTop: 12 } },
        e("label", { style: { ...styles.formLabel, marginBottom: 0 } }, "Sets"),
        e("div", { style: { display: "flex", gap: 6 } },
          e("button", {
            type: "button",
            style: { ...styles.demoToggleBtn, marginTop: 0, ...(isTimed ? { background: C.brandSoft, color: C.brand, borderColor: C.brand } : {}) },
            onClick: () => onChange({ ...values, isTimed: !isTimed })
          }, e(Icon, { name: "clock", size: 12 }), " Timed"),
          e("button", {
            type: "button",
            style: { ...styles.demoToggleBtn, marginTop: 0, ...(isBodyweight ? { background: C.brandSoft, color: C.brand, borderColor: C.brand } : {}) },
            onClick: () => onChange({ ...values, isBodyweight: !isBodyweight })
          }, "Bodyweight")
        )
      ),
      e("div", { style: styles.setRows },
        e("div", { style: { ...styles.setRowHeader, ...(isBodyweight ? { gridTemplateColumns: "26px 1fr 1fr 24px" } : {}) } },
          e("span", { style: styles.setColLabel }, "SET"),
          e("span", { style: styles.setColLabel }, isTimed ? "SECONDS" : "REPS"),
          !isBodyweight && e("span", { style: styles.setColLabel }, "WEIGHT"),
          e("span", { style: styles.setColLabel }, "REST (S)"),
          e("span", null)
        ),
        values.sets.map((s, i) => e("div", { key: i, style: { ...styles.setRow, ...(isBodyweight ? { gridTemplateColumns: "26px 1fr 1fr 24px" } : {}) } },
          e("span", { style: styles.setIndex }, i + 1),
          e("input", { type: "number", min: "0", value: s.reps, onChange: (ev) => updateSet(i, "reps", ev.target.value), style: styles.setInput, placeholder: isTimed ? "30" : "8" }),
          !isBodyweight && e("input", { type: "number", min: "0", step: "0.5", value: s.weight, onChange: (ev) => updateSet(i, "weight", ev.target.value), style: styles.setInput, placeholder: "60" }),
          e("input", { type: "number", min: "0", value: s.rest, onChange: (ev) => updateSet(i, "rest", ev.target.value), style: styles.setInput, placeholder: "90" }),
          e("button", { style: styles.rowDelete, onClick: () => removeSet(i), disabled: values.sets.length === 1, "aria-label": "Remove set" }, e(Icon, { name: "x", size: 14 }))
        ))
      ),
      e("button", { type: "button", style: styles.addSetBtn, onClick: addSet }, e(Icon, { name: "plus", size: 13, strokeWidth: 3 }), "Add set"),
      e("div", { style: { display: "flex", gap: 8, marginTop: 10 } },
        e("input", { style: { ...styles.input, flex: 1 }, placeholder: "Notes (optional)", value: values.notes, onChange: (ev) => onChange({ ...values, notes: ev.target.value }) })
      ),
      // Sept 14 2026, Jimmy: "can we do the same when the trainer wants to
      // assign a program for a client... when i add an exercise i want the
      // same tab to save and add another" — same "Save & add another"
      // pattern as the workout-log's New exercise sheet. contextLabel is
      // only ever passed while editing an existing exercise (see the
      // "Editing under ..." call site below), so it doubles as the signal
      // for "this is a brand-new exercise, adding another makes sense."
      !contextLabel && e("button", {
        type: "button",
        style: { ...styles.exSheetSaveAddAnotherBtn, ...(saving ? styles.btnDisabled : {}) },
        onClick: () => onSave(true), disabled: saving
      }, e(Icon, { name: "plus", size: 15, strokeWidth: 3 }), saving ? "Saving…" : "Save & add another"),
      savedFlash && e("div", { style: { display: "flex", alignItems: "center", gap: 6, color: C.good, fontSize: 12.5, fontWeight: 600, marginTop: 10 } },
        e(Icon, { name: "check", size: 14, color: C.good }), "Added — add the next exercise below."
      ),
      e("div", { style: { display: "flex", gap: 8, marginTop: 10 } },
        e("button", { style: { ...styles.saveBtn, marginTop: 0, flex: 1, ...(saving ? styles.btnDisabled : {}) }, disabled: saving, onClick: () => onSave(false) }, saving ? "Saving…" : contextLabel ? saveLabel : "Finish & close"),
        e("button", { style: { ...styles.demoLinkBtn, padding: "0 10px", display: "flex", alignItems: "center", gap: 4 }, onClick: onCancel }, e(Icon, { name: "back", size: 13 }), "Cancel")
      )
    );
  }

  // Manual "mark as paid" gate for a self-train client's access to whichever ONE
  // program they've picked from the shared library — same pattern as the diet
  // plan unlock (trainer/manager enters what was received and when, no real
  // payment gateway involved yet). Priced and unlocked per program, not as a
  // whole-library subscription: it reads the client's current pick from
  // client_program_assignments and pays for that specific row. Picking a
  // different program later resets it back to unpaid (a fresh assignment row
  // is always paid = false until marked otherwise). Only ever shown to a
  // trainer/manager viewing a self-train client's own detail page; a client
  // can never see or trigger this themselves.
  function ProgramPaymentCard({ clientProfile, onUpdate, refreshKey = 0, onIncrementTotalDue = null }) {
    const clientId = clientProfile ? clientProfile.id : null;
    const [loaded, setLoaded] = useState(false);
    const [assignment, setAssignment] = useState(null);
    const [program, setProgram] = useState(null);
    const [unlocking, setUnlocking] = useState(false);
    const [amount, setAmount] = useState(String(PROGRAM_PRICE));
    const [date, setDate] = useState(todayISO());
    const [saving, setSaving] = useState(false);
    const [error, setError] = useState("");
    // Sept 13 2026, Jimmy: inline "are you sure" instead of window.confirm().
    const [confirmRevoke, setConfirmRevoke] = useState(false);

    // refreshKey is bumped by the sibling ClientProgramCard whenever the
    // client's pick changes — this card fetches its own copy of the
    // assignment independently, so without this it'd keep showing stale
    // "hasn't picked a program yet" after a pick was just made.
    useEffect(() => { load(); }, [clientId, refreshKey]);

    async function load() {
      if (!sb || !clientId) { setLoaded(true); return; }
      setLoaded(false);
      const { data: rows } = await sb.from("client_program_assignments").select("*").eq("client_id", clientId).order("assigned_at", { ascending: false }).limit(1);
      const a = rows && rows[0];
      setAssignment(a || null);
      if (a) {
        const { data: prog } = await sb.from("training_programs").select("*").eq("id", a.program_id).maybeSingle();
        setProgram(prog || null);
      } else {
        setProgram(null);
      }
      setLoaded(true);
    }

    async function handleSubscribe() {
      setError("");
      const amt = Number(amount);
      if (!amount || isNaN(amt) || amt <= 0) { setError("Enter a valid amount."); return; }
      if (!date) { setError("Pick a date."); return; }
      if (!sb || !clientProfile || !assignment) { setError("Backend not configured yet."); return; }
      setSaving(true);
      const { data: updated, error: err } = await sb.from("client_program_assignments").update({ paid: true, paid_at: date }).eq("id", assignment.id).select();
      if (err) { setSaving(false); setError("Couldn't save: " + err.message); return; }
      if (!updated || updated.length === 0) { setSaving(false); setError("Save was blocked by a permissions rule (0 rows updated) — this needs a database fix, not a retry. Tell your developer: RLS blocked update on client_program_assignments."); return; }
      // Log it as a real payment, same ledger as everything else this client pays.
      const label = program ? `${styleLabel(program.style)} — ${program.name}` : "Program";
      await sb.from("client_payments").insert([{ user_id: clientProfile.user_id, client_name: clientProfile.client_name, amount: amt, paid_on: date, note: `Program: ${label}`, program_id: assignment.program_id || null }]);
      // Sept 19 2026 inspection fix: same bug class the diet-plan unlock fix
      // closed a round ago — logged the payment but never bumped total_due,
      // so unlocking a program here made the client's shown balance go DOWN
      // by the unlock amount instead of adding it as a separate charge.
      if (onIncrementTotalDue) onIncrementTotalDue(clientId, amt);
      notifyClient(clientProfile.user_id, `Your program "${label}" is ready — check your Programs tab.`);
      setSaving(false);
      setUnlocking(false);
      setAmount("");
      setDate(todayISO());
      await load();
      if (onUpdate) onUpdate();
    }

    async function handleRevoke() {
      if (!sb || !assignment) return;
      setConfirmRevoke(false);
      const { data: updated, error: err } = await sb.from("client_program_assignments").update({ paid: false }).eq("id", assignment.id).select();
      if (err) { setError("Couldn't save: " + err.message); return; }
      if (!updated || updated.length === 0) { setError("Save was blocked by a permissions rule (0 rows updated)."); return; }
      await load();
      if (onUpdate) onUpdate();
    }

    if (!loaded) return null;

    if (!assignment) {
      return e("div", { style: { ...styles.sessionForm, marginTop: 20 } },
        e("span", { style: styles.profileLabel }, "Program payment"),
        e("p", { style: { ...styles.emptyText, marginTop: 6 } }, "This client hasn't picked a program from the library yet — nothing to charge for until they do.")
      );
    }

    const paid = !!assignment.paid;
    const label = program ? `${styleLabel(program.style)} — ${program.name}` : "their picked program";

    return e("div", { style: { ...styles.sessionForm, marginTop: 20 } },
      e("div", { style: { display: "flex", justifyContent: "space-between", alignItems: "center" } },
        e("span", { style: styles.profileLabel }, "Program payment"),
        e("span", {
          style: {
            fontSize: 11, fontWeight: 600, letterSpacing: "0.03em",
            color: paid ? C.good : C.ink3, display: "flex", alignItems: "center", gap: 4
          }
        },
          e(Icon, { name: "lock", size: 11, color: paid ? C.good : C.ink3 }),
          paid ? "Active" : "Not paid — can't see this program's exercises yet"
        )
      ),
      e("p", { style: { ...styles.profileGoalText, marginTop: 6 } }, "Picked: ", label),
      paid && error && e("span", { style: { ...styles.inlineError, display: "block", marginTop: 6 } }, error),
      paid
        ? (confirmRevoke
            ? e("div", { style: { ...styles.deleteConfirmBar, flexDirection: "column", alignItems: "stretch", gap: 8, marginTop: 10 } },
                e("span", { style: styles.deleteConfirmText }, "Turn off this client's access? They'll stop seeing this program's exercises until you mark it paid again — it stays picked, it just re-locks."),
                e("div", { style: { display: "flex", gap: 8 } },
                  e("button", { style: { ...styles.confirmCancelBtn, flex: 1 }, onClick: () => setConfirmRevoke(false) }, "Cancel"),
                  e("button", { style: { ...styles.confirmDangerBtn, flex: 1 }, onClick: handleRevoke }, "Turn off")
                )
              )
            : e("button", { style: { ...styles.demoLinkBtn, marginTop: 10, color: C.critical }, onClick: () => setConfirmRevoke(true) }, "Turn off access")
          )
        : (unlocking
            ? e("div", { style: { marginTop: 10 } },
                e("label", { style: { ...styles.formLabel, marginTop: 0 } }, "Amount received"),
                e("input", { style: styles.input, type: "number", placeholder: "Amount", value: amount, onChange: (ev) => setAmount(ev.target.value) }),
                e("input", { style: { ...styles.input, marginTop: 8 }, type: "date", value: date, onChange: (ev) => setDate(ev.target.value) }),
                error && e("span", { style: styles.inlineError }, error),
                e("div", { style: { display: "flex", gap: 8, marginTop: 10 } },
                  e("button", { style: { ...styles.saveBtn, marginTop: 0, flex: 1, ...(saving ? styles.btnDisabled : {}) }, disabled: saving, onClick: handleSubscribe }, saving ? "Saving…" : "Mark as paid & unlock"),
                  e("button", { style: { ...styles.demoLinkBtn, padding: "0 10px" }, onClick: () => { setUnlocking(false); setError(""); setAmount(String(PROGRAM_PRICE)); } }, "Cancel")
                )
              )
            : e("button", { style: { ...styles.demoLinkBtn, marginTop: 10 }, onClick: () => setUnlocking(true) }, `Mark as paid ($${PROGRAM_PRICE}) →`)
         )
    );
  }

  // Sept 12 2026, Jimmy: "for each section his own logo related to programs
  // or levels its more fun" — a small colored icon badge per program, read
  // from its name (Beginner/Intermediate/Advanced) first and falling back to
  // its training style, so a stacked list of cards is visually distinct
  // instead of the same gray dumbbell square repeated down the page.
  function programVisual(name, style) {
    const n = (name || "").toLowerCase();
    if (/\b(beginner|foundation|starter|intro)\b/.test(n)) return { icon: "sparkle", color: C.good };
    if (/\b(intermediate|builder|progression)\b/.test(n)) return { icon: "trendUp", color: C.brand };
    if (/\b(advanced|elite|pro|master)\b/.test(n)) return { icon: "flame", color: C.critical };
    // Sept 15 2026, Jimmy: "do logo for every section here" — pointed at the
    // Programs list where the 5 circuit programs all share the
    // circuit_training style and so all fell through to the same "swap"
    // badge below, right back to the repeated-gray-box look the level check
    // above was built to fix. Name-match the specific circuit programs to
    // their own icon/color too, one level down from Beginner/Intermediate/
    // Advanced — same idea, just keyed off what's actually in the name.
    if (/\btotal body\b/.test(n)) return { icon: "activity", color: C.brand };
    if (/\bupper\s*\/?\s*lower\b/.test(n)) return { icon: "trendUp", color: C.clientAccent };
    if (/\bbodyweight\b/.test(n) || /\bat home\b/.test(n)) return { icon: "user", color: C.good };
    if (/\bcore\b/.test(n) || /\bconditioning\b/.test(n)) return { icon: "flame", color: C.warning };
    if (/\bstrength.endurance\b/.test(n) || /\bendurance\b/.test(n)) return { icon: "trophy", color: C.critical };
    const byStyle = { powerlifting: "dumbbell", calisthenics: "activity", hyrox: "clock", general_resistance: "dumbbell", circuit_training: "swap" };
    return { icon: byStyle[style] || "dumbbell", color: C.brand };
  }

  // A rounded, tinted square carrying one icon — the shared "logo" shape
  // behind both programVisual (above) and dietPlanVisual (near DietPanel).
  function IconBadge({ icon, color, size = 44 }) {
    return e("div", {
      style: {
        width: size, height: size, borderRadius: Math.round(size * 0.3), flexShrink: 0,
        background: withAlpha(color, 0.16), border: `1px solid ${withAlpha(color, 0.32)}`,
        display: "flex", alignItems: "center", justifyContent: "center"
      }
    }, e(Icon, { name: icon, size: Math.round(size * 0.42), color, strokeWidth: 2.1 }));
  }

export { ExerciseLibraryPanel, ExerciseContent, ProgramRequestRow, ProgramRequestsPanel, ExerciseForm, ProgramSetsForm, ProgramPaymentCard, programVisual, IconBadge };
