// @generated by tools/extract/extract.py — bodies copied verbatim from index.html
import { notifyClient } from "../../data/group1.js";
import { PROGRAM_PRICE } from "../../domain/access.js";
import { sb } from "../../platform/supabase.js";
import { todayISO } from "../../shared/lib/dates.js";
import { e } from "../../shared/react.js";
import { C, styles } from "../../shared/theme.js";
import { Icon } from "../../shared/ui/Icon.js";
import { useEffect, useState } from "react";

  // Manual "mark as paid" gate for a self-train client's access to whichever ONE
  // program they've picked from the shared library — same pattern as the diet
  // plan unlock (trainer/manager enters what was received and when, no real
  // payment gateway involved yet). Priced and unlocked per program, not as a
  // whole-library subscription: it reads the client's current pick from
  // client_program_assignments and pays for that specific row. Picking a
  // different program later resets it back to unpaid (a fresh assignment row
  // is always paid = false until marked otherwise). Only ever shown to a
  // trainer/manager viewing a self-train client's own detail page; a client
  // can never see or trigger this themselves.
  function ProgramPaymentCard({ clientProfile, onUpdate, refreshKey = 0, onIncrementTotalDue = null }) {
    const clientId = clientProfile ? clientProfile.id : null;
    const [loaded, setLoaded] = useState(false);
    const [assignment, setAssignment] = useState(null);
    const [program, setProgram] = useState(null);
    const [unlocking, setUnlocking] = useState(false);
    const [amount, setAmount] = useState(String(PROGRAM_PRICE));
    const [date, setDate] = useState(todayISO());
    const [saving, setSaving] = useState(false);
    const [error, setError] = useState("");
    // Sept 13 2026, Jimmy: inline "are you sure" instead of window.confirm().
    const [confirmRevoke, setConfirmRevoke] = useState(false);

    // refreshKey is bumped by the sibling ClientProgramCard whenever the
    // client's pick changes — this card fetches its own copy of the
    // assignment independently, so without this it'd keep showing stale
    // "hasn't picked a program yet" after a pick was just made.
    useEffect(() => { load(); }, [clientId, refreshKey]);

    async function load() {
      if (!sb || !clientId) { setLoaded(true); return; }
      setLoaded(false);
      const { data: rows } = await sb.from("client_program_assignments").select("*").eq("client_id", clientId).order("assigned_at", { ascending: false }).limit(1);
      const a = rows && rows[0];
      setAssignment(a || null);
      if (a) {
        const { data: prog } = await sb.from("training_programs").select("*").eq("id", a.program_id).maybeSingle();
        setProgram(prog || null);
      } else {
        setProgram(null);
      }
      setLoaded(true);
    }

    async function handleSubscribe() {
      setError("");
      const amt = Number(amount);
      if (!amount || isNaN(amt) || amt <= 0) { setError("Enter a valid amount."); return; }
      if (!date) { setError("Pick a date."); return; }
      if (!sb || !clientProfile || !assignment) { setError("Backend not configured yet."); return; }
      setSaving(true);
      const { data: updated, error: err } = await sb.from("client_program_assignments").update({ paid: true, paid_at: date }).eq("id", assignment.id).select();
      if (err) { setSaving(false); setError("Couldn't save: " + err.message); return; }
      if (!updated || updated.length === 0) { setSaving(false); setError("Save was blocked by a permissions rule (0 rows updated) — this needs a database fix, not a retry. Tell your developer: RLS blocked update on client_program_assignments."); return; }
      // Log it as a real payment, same ledger as everything else this client pays.
      const label = program ? `${styleLabel(program.style)} — ${program.name}` : "Program";
      await sb.from("client_payments").insert([{ user_id: clientProfile.user_id, client_name: clientProfile.client_name, amount: amt, paid_on: date, note: `Program: ${label}`, program_id: assignment.program_id || null }]);
      // Sept 19 2026 inspection fix: same bug class the diet-plan unlock fix
      // closed a round ago — logged the payment but never bumped total_due,
      // so unlocking a program here made the client's shown balance go DOWN
      // by the unlock amount instead of adding it as a separate charge.
      if (onIncrementTotalDue) onIncrementTotalDue(clientId, amt);
      notifyClient(clientProfile.user_id, `Your program "${label}" is ready — check your Programs tab.`);
      setSaving(false);
      setUnlocking(false);
      setAmount("");
      setDate(todayISO());
      await load();
      if (onUpdate) onUpdate();
    }

    async function handleRevoke() {
      if (!sb || !assignment) return;
      setConfirmRevoke(false);
      const { data: updated, error: err } = await sb.from("client_program_assignments").update({ paid: false }).eq("id", assignment.id).select();
      if (err) { setError("Couldn't save: " + err.message); return; }
      if (!updated || updated.length === 0) { setError("Save was blocked by a permissions rule (0 rows updated)."); return; }
      await load();
      if (onUpdate) onUpdate();
    }

    if (!loaded) return null;

    if (!assignment) {
      return e("div", { style: { ...styles.sessionForm, marginTop: 20 } },
        e("span", { style: styles.profileLabel }, "Program payment"),
        e("p", { style: { ...styles.emptyText, marginTop: 6 } }, "This client hasn't picked a program from the library yet — nothing to charge for until they do.")
      );
    }

    const paid = !!assignment.paid;
    const label = program ? `${styleLabel(program.style)} — ${program.name}` : "their picked program";

    return e("div", { style: { ...styles.sessionForm, marginTop: 20 } },
      e("div", { style: { display: "flex", justifyContent: "space-between", alignItems: "center" } },
        e("span", { style: styles.profileLabel }, "Program payment"),
        e("span", {
          style: {
            fontSize: 11, fontWeight: 600, letterSpacing: "0.03em",
            color: paid ? C.good : C.ink3, display: "flex", alignItems: "center", gap: 4
          }
        },
          e(Icon, { name: "lock", size: 11, color: paid ? C.good : C.ink3 }),
          paid ? "Active" : "Not paid — can't see this program's exercises yet"
        )
      ),
      e("p", { style: { ...styles.profileGoalText, marginTop: 6 } }, "Picked: ", label),
      paid && error && e("span", { style: { ...styles.inlineError, display: "block", marginTop: 6 } }, error),
      paid
        ? (confirmRevoke
            ? e("div", { style: { ...styles.deleteConfirmBar, flexDirection: "column", alignItems: "stretch", gap: 8, marginTop: 10 } },
                e("span", { style: styles.deleteConfirmText }, "Turn off this client's access? They'll stop seeing this program's exercises until you mark it paid again — it stays picked, it just re-locks."),
                e("div", { style: { display: "flex", gap: 8 } },
                  e("button", { style: { ...styles.confirmCancelBtn, flex: 1 }, onClick: () => setConfirmRevoke(false) }, "Cancel"),
                  e("button", { style: { ...styles.confirmDangerBtn, flex: 1 }, onClick: handleRevoke }, "Turn off")
                )
              )
            : e("button", { style: { ...styles.demoLinkBtn, marginTop: 10, color: C.critical }, onClick: () => setConfirmRevoke(true) }, "Turn off access")
          )
        : (unlocking
            ? e("div", { style: { marginTop: 10 } },
                e("label", { style: { ...styles.formLabel, marginTop: 0 } }, "Amount received"),
                e("input", { style: styles.input, type: "number", placeholder: "Amount", value: amount, onChange: (ev) => setAmount(ev.target.value) }),
                e("input", { style: { ...styles.input, marginTop: 8 }, type: "date", value: date, onChange: (ev) => setDate(ev.target.value) }),
                error && e("span", { style: styles.inlineError }, error),
                e("div", { style: { display: "flex", gap: 8, marginTop: 10 } },
                  e("button", { style: { ...styles.saveBtn, marginTop: 0, flex: 1, ...(saving ? styles.btnDisabled : {}) }, disabled: saving, onClick: handleSubscribe }, saving ? "Saving…" : "Mark as paid & unlock"),
                  e("button", { style: { ...styles.demoLinkBtn, padding: "0 10px" }, onClick: () => { setUnlocking(false); setError(""); setAmount(String(PROGRAM_PRICE)); } }, "Cancel")
                )
              )
            : e("button", { style: { ...styles.demoLinkBtn, marginTop: 10 }, onClick: () => setUnlocking(true) }, `Mark as paid ($${PROGRAM_PRICE}) →`)
         )
    );
  }

export { ProgramPaymentCard };
