// @generated by tools/extract/extract.py — bodies copied verbatim from index.html
import { notifyClient } from "../../data/group1.js";
import { PROGRAM_PRICE } from "../../domain/access.js";
import { sb } from "../../platform/supabase.js";
import { todayISO } from "../../shared/lib/dates.js";
import { fmtDate } from "../../shared/lib/format.js";
import { e } from "../../shared/react.js";
import { styles } from "../../shared/theme.js";
import { Icon } from "../../shared/ui/Icon.js";
import { useState } from "react";

  // A single pending program-payment request, with its own inline "mark as
  // paid" form — same $35 default and same writes ProgramPaymentCard's own
  // button does (client_program_assignments.paid + a client_payments row),
  // just reachable from one central list instead of that client's own page.
  function ProgramRequestRow({ req, programName, clientProfile, onIncrementTotalDue = null, onResolved }) {
    const [unlocking, setUnlocking] = useState(false);
    const [amount, setAmount] = useState(String(PROGRAM_PRICE));
    const [date, setDate] = useState(todayISO());
    const [saving, setSaving] = useState(false);
    const [declining, setDeclining] = useState(false);
    const [error, setError] = useState("");
    // Sept 13 2026, Jimmy: inline "are you sure" instead of window.confirm().
    const [confirmDecline, setConfirmDecline] = useState(false);

    // Client picked a program then changed their mind before paying — this
    // just removes the pick entirely (same delete client_program_assignments
    // does from the client's own trash icon), so it drops off this list
    // without ever being charged. Doesn't touch client_payments, since
    // nothing was ever paid here.
    async function handleDecline() {
      if (!sb) return;
      setConfirmDecline(false);
      setDeclining(true);
      const { error: err } = await sb.from("client_program_assignments").delete().eq("id", req.id);
      setDeclining(false);
      if (err) { setError("Couldn't remove: " + err.message); return; }
      onResolved(req.id);
    }

    async function handleUnlock() {
      setError("");
      const amt = Number(amount);
      if (!amount || isNaN(amt) || amt <= 0) { setError("Enter a valid amount."); return; }
      if (!date) { setError("Pick a date."); return; }
      if (!sb) { setError("Backend not configured yet."); return; }
      setSaving(true);
      const { data: updated, error: err } = await sb.from("client_program_assignments").update({ paid: true, paid_at: date }).eq("id", req.id).select();
      if (err) { setSaving(false); setError("Couldn't save: " + err.message); return; }
      if (!updated || updated.length === 0) { setSaving(false); setError("Save was blocked by a permissions rule (0 rows updated) — this needs a database fix, not a retry. Tell your developer: RLS blocked update on client_program_assignments."); return; }
      // Log it as a real payment, same ledger as everything else this client pays.
      if (clientProfile && clientProfile.user_id) {
        await sb.from("client_payments").insert([{ user_id: clientProfile.user_id, client_name: req.client_name, amount: amt, paid_on: date, note: `Program: ${programName || "Program"}`, program_id: req.program_id || null }]);
        // Sept 19 2026 inspection fix: same bug class the diet-plan unlock
        // fix closed a round ago — this logged the payment but never
        // bumped total_due, so approving a program pick here made the
        // client's shown balance go DOWN by the unlock amount (a payment
        // against nothing) instead of being a separate charge added on
        // top of what they already owe.
        if (onIncrementTotalDue) onIncrementTotalDue(clientProfile.id, amt);
        notifyClient(clientProfile.user_id, `Your program${programName ? ` "${programName}"` : ""} is ready — check your Programs tab.`);
      }
      setSaving(false);
      onResolved(req.id);
    }

    return e("div", { style: styles.trainerStatCard },
      e("div", { style: { display: "flex", flexDirection: "column", gap: 4, marginBottom: 10 } },
        e("span", { style: styles.exerciseName }, req.client_name || "Unknown client"),
        clientProfile && clientProfile.phone && e("span", { style: { ...styles.muscleSubText, fontFamily: "'JetBrains Mono', monospace" } }, clientProfile.phone),
        e("span", { style: styles.muscleSubText },
          programName ? `picked "${programName}" on ` : "picked a program on ",
          fmtDate((req.assigned_at || "").slice(0, 10))
        )
      ),
      error && e("span", { style: { ...styles.inlineError, display: "block", marginBottom: 8 } }, error),
      unlocking
        ? e("div", null,
            e("label", { style: { ...styles.formLabel, marginTop: 0 } }, "Amount received"),
            e("input", { style: styles.input, type: "number", placeholder: "Amount", value: amount, onChange: (ev) => setAmount(ev.target.value) }),
            e("input", { style: { ...styles.input, marginTop: 8 }, type: "date", value: date, onChange: (ev) => setDate(ev.target.value) }),
            e("div", { style: { display: "flex", gap: 8, marginTop: 10 } },
              e("button", { style: { ...styles.saveBtn, marginTop: 0, flex: 1, ...(saving ? styles.btnDisabled : {}) }, disabled: saving, onClick: handleUnlock }, saving ? "Saving…" : "Mark as paid & unlock"),
              e("button", { style: { ...styles.demoLinkBtn, padding: "0 10px" }, onClick: () => { setUnlocking(false); setError(""); setAmount(String(PROGRAM_PRICE)); } }, "Cancel")
            )
          )
        : confirmDecline
        ? e("div", { style: styles.deleteConfirmBar },
            e("span", { style: styles.deleteConfirmText }, `Remove this pick of ${programName || "this program"}?`),
            e("div", { style: { display: "flex", gap: 6, flexShrink: 0 } },
              e("button", { type: "button", style: styles.setConfirmCancelBtn, onClick: () => setConfirmDecline(false) }, "Cancel"),
              e("button", { type: "button", style: { ...styles.setConfirmDangerBtn, ...(declining ? styles.btnDisabled : {}) }, disabled: declining, onClick: handleDecline }, declining ? "…" : "Remove")
            )
          )
        : e("div", { style: { display: "flex", gap: 8 } },
            e("button", { style: { ...styles.saveBtn, marginTop: 0, flex: 1 }, onClick: () => setUnlocking(true) }, `Mark as paid ($${PROGRAM_PRICE}) →`),
            e("button", { style: styles.deleteBtn, onClick: () => setConfirmDecline(true), "aria-label": "Remove this request" }, e(Icon, { name: "trash", size: 14 }))
          )
    );
  }

export { ProgramRequestRow };
