// @generated by tools/extract/extract.py — bodies copied verbatim from index.html
import { B2B_FLAT_RATE_MONTHLY } from "../../domain/access.js";
import { sb } from "../../platform/supabase.js";
import { e } from "../../shared/react.js";
import { C, styles } from "../../shared/theme.js";
import { Icon } from "../../shared/ui/Icon.js";
import { EditableStat, StatTile } from "../../shared/ui/controls.js";
import { GymsEmptyArt } from "../../shared/ui/empty-art.js";
import { useEffect, useState } from "react";

  // Jimmy's platform-level view of every self-serve gym: what each owes this
  // month (their percentage of their clients' fees), a note on payment status,
  // and a freeze switch to cut off access if they haven't renewed.
  function GymsBillingPanel() {
    const [loading, setLoading] = useState(true);
    const [gyms, setGyms] = useState([]);
    const [trainerCounts, setTrainerCounts] = useState({});
    const [clientStats, setClientStats] = useState({}); // gymId -> { count, totalDue }
    const [freezingId, setFreezingId] = useState(null);
    const [saveError, setSaveError] = useState("");
    // Sept 13 2026, Jimmy: inline "are you sure" instead of window.confirm()
    // — which gym (if any) currently has its freeze/unfreeze button
    // swapped for the inline confirm bar.
    const [confirmFreezeId, setConfirmFreezeId] = useState(null);
    // Sept 15 2026, Jimmy: "i want to delete some gyms if i can" — cleanup
    // for empty/test gyms (signed up, never actually used) that otherwise
    // just sit in this list forever. Deliberately narrower than
    // handleDeleteTrainer elsewhere in the app, which orphans a deleted
    // trainer's clients rather than blocking — a GYM can have several
    // trainers each with their own clients underneath, so silently
    // cascading that delete is a much bigger blast radius. Instead this
    // only allows deleting a gym that already has zero trainers (and so,
    // by construction, zero clients under it) — a real gym with people in
    // it has to be emptied out first (reassign/delete its trainers on the
    // Trainers screen, same as any other gym owner would), which is enough
    // friction that it can't happen by accident.
    const [confirmDeleteGymId, setConfirmDeleteGymId] = useState(null);
    const [deletingGymId, setDeletingGymId] = useState(null);

    useEffect(() => {
      if (!sb) { setLoading(false); return; }
      (async () => {
        const [gymsRes, trainersRes, clientsRes] = await Promise.all([
          sb.from("gyms").select("*").order("created_at", { ascending: false }),
          sb.from("trainers").select("gym_id").not("gym_id", "is", null),
          // is_trainer_self_log excluded — every other client count/roster in
          // the app does this too, so a trainer's own personal-tracking row
          // never counts as a client (Sept 6 2026 deep bug search: this was
          // the one query that had been missed).
          sb.from("client_profiles").select("gym_id, total_due").not("gym_id", "is", null).eq("is_trainer_self_log", false)
        ]);
        if (!gymsRes.error && gymsRes.data) {
          setGyms(gymsRes.data);
          // Sept 19 2026 inspection fix: same backfill shape as
          // TrainersBillingPanel's own next_payment_date/rate_monthly
          // backfill below — any gym created before the fix that stamps
          // a rate at signup, or added some other way with no rate set,
          // otherwise sits billing $0/month forever with nothing flagging
          // it. Runs once per gym: the next load finds flat_rate_monthly
          // already set and skips it.
          const needsRateBackfill = gymsRes.data.filter((g) => g.flat_rate_monthly == null);
          if (needsRateBackfill.length > 0 && sb) {
            needsRateBackfill.forEach((g) => { sb.from("gyms").update({ flat_rate_monthly: B2B_FLAT_RATE_MONTHLY }).eq("id", g.id).then(() => {}); });
            setGyms((prev) => prev.map((g) => (g.flat_rate_monthly == null ? { ...g, flat_rate_monthly: B2B_FLAT_RATE_MONTHLY } : g)));
          }
        }
        if (!trainersRes.error && trainersRes.data) {
          const counts = {};
          trainersRes.data.forEach((t) => { counts[t.gym_id] = (counts[t.gym_id] || 0) + 1; });
          setTrainerCounts(counts);
        }
        if (!clientsRes.error && clientsRes.data) {
          const stats = {};
          clientsRes.data.forEach((c) => {
            const s = stats[c.gym_id] || { count: 0, totalDue: 0 };
            s.count += 1;
            s.totalDue += Number(c.total_due) || 0;
            stats[c.gym_id] = s;
          });
          setClientStats(stats);
        }
        setLoading(false);
      })();
    }, []);

    async function updateGymField(gymId, field, value) {
      // Optimistic update, but if the write actually fails we revert it and
      // say so — previously this just applied the change on screen and never
      // checked the result, so a failed save (bad connection, RLS reject)
      // left the UI showing "Frozen"/a new rate that the database never got.
      const prevGym = gyms.find((g) => g.id === gymId);
      const prevValue = prevGym ? prevGym[field] : undefined;
      setSaveError("");
      setGyms((prev) => prev.map((g) => (g.id === gymId ? { ...g, [field]: value } : g)));
      if (!sb) return;
      const { error } = await sb.from("gyms").update({ [field]: value }).eq("id", gymId);
      if (error) {
        setGyms((prev) => prev.map((g) => (g.id === gymId ? { ...g, [field]: prevValue } : g)));
        setSaveError("Couldn't save that change — check your connection and try again.");
      }
    }

    async function toggleFreeze(gym) {
      const nextFrozen = !gym.is_frozen;
      setConfirmFreezeId(null);
      setFreezingId(gym.id);
      await updateGymField(gym.id, "is_frozen", nextFrozen);
      setFreezingId(null);
    }

    async function handleDeleteGym(gym) {
      setConfirmDeleteGymId(null);
      setSaveError("");
      setDeletingGymId(gym.id);
      if (sb) {
        const { error } = await sb.from("gyms").delete().eq("id", gym.id);
        if (error) {
          setSaveError(`Couldn't delete ${gym.name} — check your connection and try again.`);
          setDeletingGymId(null);
          return;
        }
      }
      setGyms((prev) => prev.filter((g) => g.id !== gym.id));
      setDeletingGymId(null);
    }

    if (loading) return e("div", { style: styles.empty }, e("p", { style: styles.emptyText }, "Loading gyms…"));

    // Flat per-gym rate, unlimited clients (see B2B_FLAT_RATE_MONTHLY above)
    // — no longer multiplied by client count now that pricing isn't per-seat.
    // Sept 18 2026 fix: this used to sum EVERY gym's rate, including ones
    // already frozen for non-payment — so the headline number counted money
    // that isn't actually coming in as if it were. Frozen gyms are excluded
    // now; their rate still shows on their own card below, just not folded
    // into the total.
    const activeGyms = gyms.filter((g) => !g.is_frozen);
    const totalMonthlyCut = activeGyms.reduce((sum, g) => sum + (Number(g.flat_rate_monthly) || 0), 0);
    const frozenCount = gyms.length - activeGyms.length;

    return e("div", null,
      saveError && e("div", { style: { ...styles.setupNotice, marginBottom: 14 } }, e(Icon, { name: "alert", size: 14, color: C.critical }), " ", saveError),
      gyms.length > 0 && e(StatTile, { label: "Estimated monthly cut, all gyms", value: Math.round(totalMonthlyCut), unit: "", size: "lg" }),
      gyms.length > 0 && frozenCount > 0 && e("p", { style: { ...styles.profileGoalText, fontSize: 12, marginTop: 4, color: C.critical } }, `Excludes ${frozenCount} frozen gym${frozenCount === 1 ? "" : "s"} — not counted as revenue until unfrozen.`),
      gyms.length > 0 && e("p", { style: { ...styles.profileGoalText, fontSize: 12, marginTop: 6 } }, `Standard rate is $${B2B_FLAT_RATE_MONTHLY}/month per gym, unlimited clients — each gym's rate below can be adjusted individually if you negotiate a different one.`),
      // Sept 18 2026, Jimmy: a QA pass flagged this as confusing ("looks like
      // double billing") — clarified to spell out these are two DIFFERENT
      // revenue streams from two different customers, on purpose, not a
      // reconciliation bug: a gym here is a white-label customer paying for
      // their whole operation, separate from any individual trainer's own
      // $B2B_FLAT_RATE_MONTHLY/month (Trainer billing screen), which every
      // real trainer pays regardless of which gym (if any) they belong to.
      gyms.length > 0 && e("p", { style: { ...styles.profileGoalText, fontSize: 12, marginTop: 4 } }, `Two separate revenue streams, on purpose — this gym's flat rate is what its owner pays you for the whole gym (a white-label customer). Its individual trainers still each pay their own $${B2B_FLAT_RATE_MONTHLY}/month on the Trainer billing screen too — that's not double-counted here, it's simply a different customer relationship. Freezing a gym here signs out its owner and every trainer in it, regardless of whether they individually show Active on Trainer billing.`),
      gyms.length === 0 && e("div", { style: styles.empty }, e(GymsEmptyArt, {}), e("p", { style: styles.emptyText }, "No self-serve gyms have signed up yet.")),
      e("div", { style: { display: "flex", flexDirection: "column", gap: 14, marginTop: gyms.length > 0 ? 18 : 0 } }, gyms.map((g) => {
        const stats = clientStats[g.id] || { count: 0, totalDue: 0 };
        const cut = Number(g.flat_rate_monthly) || 0;
        return e("div", { key: g.id, style: styles.profileSummary },
          e("div", { style: { display: "flex", justifyContent: "space-between", alignItems: "flex-start", marginBottom: 8 } },
            e("div", null,
              e("div", { style: styles.exerciseName }, g.name),
              e("div", { style: styles.muscleSubText }, g.owner_email)
            ),
            e("span", { style: { ...styles.goalChip, ...(g.is_frozen ? styles.goalChipBad : styles.goalChipGood) } }, g.is_frozen ? "Frozen" : "Active")
          ),
          e("div", { style: styles.muscleSubText }, `${trainerCounts[g.id] || 0} trainer${(trainerCounts[g.id] || 0) === 1 ? "" : "s"} · ${stats.count} client${stats.count === 1 ? "" : "s"} (unlimited) · code ${g.invite_code || "—"}`),
          e("div", { style: styles.profileSummaryGrid },
            e(EditableStat, { label: "Flat rate ($/mo, unlimited clients)", value: g.flat_rate_monthly, suffix: "$", onCommit: (v) => updateGymField(g.id, "flat_rate_monthly", v != null ? v : 0) }),
            e("div", null,
              e("span", { style: styles.profileLabel }, "Est. monthly cut"),
              e("p", { style: styles.profileValue }, `$${Math.round(cut).toLocaleString()}`)
            )
          ),
          e(EditableStat, { label: "Billing note", value: g.billing_note, type: "text", block: true, placeholder: "e.g. Paid through August", onCommit: (v) => updateGymField(g.id, "billing_note", v) }),
          confirmFreezeId === g.id
            ? e("div", { style: { ...styles.deleteConfirmBar, flexDirection: "column", alignItems: "stretch", gap: 10, marginTop: 12 } },
                e("span", { style: styles.deleteConfirmText },
                  g.is_frozen
                    ? `Unfreeze ${g.name}? Their trainers will be able to log in again.`
                    : `Freeze ${g.name}? Their owner and every trainer in this gym will be signed out and blocked from logging in until you unfreeze it.`
                ),
                e("div", { style: { display: "flex", gap: 8 } },
                  e("button", { style: styles.confirmCancelBtn, onClick: () => setConfirmFreezeId(null) }, "Cancel"),
                  e("button", { style: styles.confirmDangerBtn, onClick: () => toggleFreeze(g) }, g.is_frozen ? "Unfreeze" : "Freeze")
                )
              )
            : e("button", {
                style: { ...styles.saveBtn, marginTop: 12, ...(g.is_frozen ? {} : { background: C.criticalStrong }), ...(freezingId === g.id ? styles.btnDisabled : {}) },
                disabled: freezingId === g.id,
                onClick: () => setConfirmFreezeId(g.id)
              }, freezingId === g.id ? "Working…" : g.is_frozen ? "Unfreeze this gym" : "Freeze this gym"),
          confirmDeleteGymId === g.id
            ? e("div", { style: { ...styles.deleteConfirmBar, flexDirection: "column", alignItems: "stretch", gap: 10, marginTop: 10 } },
                e("span", { style: styles.deleteConfirmText }, `Delete ${g.name}? This can't be undone.`),
                e("div", { style: { display: "flex", gap: 8 } },
                  e("button", { style: styles.confirmCancelBtn, onClick: () => setConfirmDeleteGymId(null) }, "Cancel"),
                  e("button", { style: styles.confirmDangerBtn, onClick: () => handleDeleteGym(g) }, "Delete")
                )
              )
            : (trainerCounts[g.id] || 0) > 0
            ? e("p", { style: { ...styles.muscleSubText, marginTop: 10, fontStyle: "italic" } }, `Remove or reassign its ${trainerCounts[g.id]} trainer${trainerCounts[g.id] === 1 ? "" : "s"} on the Trainers screen before this gym can be deleted.`)
            : e("button", {
                style: { ...styles.deleteClientBtn, margin: "10px 0 0", ...(deletingGymId === g.id ? styles.btnDisabled : {}) },
                disabled: deletingGymId === g.id,
                onClick: () => setConfirmDeleteGymId(g.id)
              }, e(Icon, { name: "trash", size: 13 }), deletingGymId === g.id ? "Deleting…" : "Delete gym")
        );
      }))
    );
  }

export { GymsBillingPanel };
