// @generated by tools/extract/extract.py — bodies copied verbatim from index.html
import { B2B_FLAT_RATE_MONTHLY, SELF_TRAIN_MONTHLY_PRICE } from "../../domain/access.js";
import { BrandMark, GateDecor } from "../../shared/brand.js";
import { e } from "../../shared/react.js";
import { C, styles } from "../../shared/theme.js";
import { Icon } from "../../shared/ui/Icon.js";
import { PaymentStatusStepper } from "../../shared/widgets/PaymentStatusStepper.js";
import { IconBadge } from "../programs/group1.js";
import React, { useEffect, useState } from "react";
import { fmtDateMed } from "../../shared/lib/format.js";

  // A trainer's real photo where one's been uploaded, falling back to the
  // same letter-in-a-circle every other avatar in the app already uses.
  function TrainerAvatar({ name, photoUrl, size }) {
    const s = size || 36;
    // Sept 13 2026, Jimmy: "can the client open the profile picture" —
    // TrainerAvatar is the same component used everywhere a trainer photo
    // shows (the client's "Find a trainer" list included), so making it
    // tap-to-enlarge here covers every one of those spots at once. Just a
    // fullscreen tap-to-dismiss viewer over the existing photo, no new data.
    const [zoomed, setZoomed] = useState(false);
    if (photoUrl) {
      return e(React.Fragment, null,
        e("img", {
          src: photoUrl, alt: name || "Trainer",
          style: { width: s, height: s, borderRadius: "50%", objectFit: "cover", flexShrink: 0, cursor: "pointer" },
          onClick: () => setZoomed(true)
        }),
        zoomed && e("div", {
          style: { position: "fixed", inset: 0, background: C.scrim, display: "flex", alignItems: "center", justifyContent: "center", zIndex: 70, padding: 24 },
          onClick: () => setZoomed(false)
        },
          e("img", {
            src: photoUrl, alt: name || "Trainer",
            style: { maxWidth: "100%", maxHeight: "100%", borderRadius: 16, boxShadow: "0 20px 60px rgba(0,0,0,0.5)" },
            onClick: (ev) => ev.stopPropagation()
          }),
          e("button", {
            type: "button",
            style: { position: "fixed", top: "max(16px, env(safe-area-inset-top))", right: 16, background: "rgba(0,0,0,0.4)", border: "none", borderRadius: "50%", width: 34, height: 34, display: "flex", alignItems: "center", justifyContent: "center", cursor: "pointer" },
            onClick: () => setZoomed(false), "aria-label": "Close photo"
          }, e(Icon, { name: "x", size: 18, color: "#FFFFFF" }))
        )
      );
    }
    return e("div", { style: { ...styles.avatar, width: s, height: s, fontSize: Math.round(s * 0.39) } }, (name || "?").slice(0, 1).toUpperCase());
  }

  // Sept 13 2026, Jimmy (jimfit-trainer-profile.html mockup): an always-
  // visible multi-line textarea that saves itself on blur — for text that's
  // likely to run past one line (a bio, a list of specialties), where
  // EditableStat's single-line tap-to-edit chip made writing/reading it
  // awkward. Keeps this screen's "no Save button, everything saves itself"
  // behavior; it just does that with a real textarea instead of a chip.
  function AutoSaveTextarea({ label, value, placeholder = "", onCommit, minHeight = 52 }) {
    const [draft, setDraft] = useState(value || "");
    useEffect(() => { setDraft(value || ""); }, [value]);

    function commit() {
      const v = draft.trim() || null;
      if (v !== (value || null)) onCommit(v);
    }

    return e("div", { style: { marginTop: 10 } },
      e("span", { style: styles.profileLabel }, label),
      e("textarea", {
        value: draft, placeholder, onChange: (ev) => setDraft(ev.target.value), onBlur: commit,
        style: { ...styles.input, marginTop: 4, minHeight, padding: "9px 11px", lineHeight: 1.5, resize: "vertical", fontFamily: "'Inter', sans-serif" }
      })
    );
  }

  // Sept 15 2026, Jimmy: "make the info tab more pro and interactive" — the
  // client's own "My info" tab used to be one flat grid (name through
  // injuries, undifferentiated). Groups fields into labeled sections with an
  // icon badge each, so it reads like a real profile page. Originally
  // self-view only; extended the same day to the trainer's and manager's
  // client detail "Info" view too ("still the same" — Jimmy expected the
  // upgrade everywhere this grid appears, not just the client-facing tab),
  // so all three places that used to share the old flat grid now share this
  // instead.
  function InfoSectionCard({ icon, color, title, children }) {
    return e("div", { style: { ...styles.profileSummary, marginBottom: 14 } },
      e("div", { style: { display: "flex", alignItems: "center", gap: 10, marginBottom: 12 } },
        e(IconBadge, { icon, color, size: 34 }),
        e("span", { style: { fontFamily: "'Oswald', sans-serif", fontSize: 14.5, fontWeight: 600, letterSpacing: "0.02em", color: C.ink } }, title)
      ),
      children
    );
  }

  function TrainerPendingApprovalScreen({ trainer, onLogout }) {
    return e("div", { style: { ...styles.gateWrap, position: "relative" } },
      e(GateDecor, {}),
      e("div", { style: { ...styles.gateCard, position: "relative", zIndex: 1 } },
        e("div", { style: { opacity: 0, animation: "popIn 0.4s cubic-bezier(.16,1,.3,1) 0.06s forwards" } }, e(BrandMark, {})),
        e("h1", { style: { ...styles.gateTitle, opacity: 0, animation: "fadeUp 0.4s cubic-bezier(.16,1,.3,1) 0.16s forwards" } }, "Almost there!"),
        e("p", { style: { ...styles.gateSub, opacity: 0, animation: "fadeUp 0.4s cubic-bezier(.16,1,.3,1) 0.26s forwards" } },
          `Thanks for signing up${trainer && trainer.name ? `, ${trainer.name}` : ""} — your trainer account is waiting for approval. You'll be able to log in and see your assigned clients as soon as it's approved.`
        ),
        e("button", { style: { ...styles.saveBtn, marginTop: 18, opacity: 0, animation: "fadeUp 0.4s cubic-bezier(.16,1,.3,1) 0.38s forwards" }, onClick: onLogout }, "Log out")
      )
    );
  }

  // Shown instead of the whole TrainerView once a trainer's payment is
  // overdue — same "informational, no self-serve unlock button" pattern as
  // SelfTrainAccessLockedScreen (only a manager confirming a payment clears
  // this, via "Mark this month's payment received" on Trainers → Billing).
  // Deliberately softer than is_frozen's hard sign-out above: this is a
  // routine "your month is up," not a manager forcibly locking someone out,
  // so it stays logged in and just explains what's needed and how to pay,
  // rather than booting them with no explanation.
  function TrainerPaymentOverdueScreen({ trainer, onLogout }) {
    // Sept 15 2026, Jimmy: "and the payment" — same GateDecor + staggered
    // popIn/fadeUp entrance as TrainerFirstPaymentDueScreen (the "one more
    // step" first-payment screen already got this in an earlier pass); this
    // recurring/overdue version was missed at the time. Same content/logic,
    // just no longer the flat static version.
    return e("div", { style: { ...styles.gateWrap, position: "relative" } },
      e(GateDecor, {}),
      e("div", { style: { ...styles.gateCard, position: "relative", zIndex: 1 } },
        e("div", { style: { opacity: 0, animation: "popIn 0.4s cubic-bezier(.16,1,.3,1) 0.06s forwards" } }, e(BrandMark, {})),
        e("h1", { style: { ...styles.gateTitle, opacity: 0, animation: "fadeUp 0.4s cubic-bezier(.16,1,.3,1) 0.16s forwards" } }, "Payment due"),
        e("p", { style: { ...styles.gateSub, opacity: 0, animation: "fadeUp 0.4s cubic-bezier(.16,1,.3,1) 0.26s forwards" } },
          `Hi${trainer && trainer.name ? ` ${trainer.name}` : ""} — your monthly payment was due ${trainer && trainer.next_payment_date ? fmtDateMed(trainer.next_payment_date) : "recently"} and hasn't been confirmed yet, so your account is paused until it is.`
        ),
        e("div", { style: { width: "100%", opacity: 0, animation: "fadeUp 0.4s cubic-bezier(.16,1,.3,1) 0.38s forwards" } },
          e(PaymentStatusStepper, {
            email: trainer && trainer.email, context: "trainer_monthly",
            amount: (trainer && Number(trainer.rate_monthly)) || B2B_FLAT_RATE_MONTHLY,
            approvedCopy: "Approved — access resumes"
          })
        ),
        e("button", { style: { ...styles.saveBtn, marginTop: 18, opacity: 0, animation: "fadeUp 0.4s cubic-bezier(.16,1,.3,1) 0.5s forwards" }, onClick: onLogout }, "Log out")
      )
    );
  }

  // Sept 6 2026, Jimmy: "i want the trainer when he first open to pay and
  // then get my approved to accept him not using the app for free" —
  // approval alone used to be enough (a real due date got stamped 30 days
  // out, so isTrainerPaymentOverdue stayed false the whole time). Now a
  // trainer who has never had a single trainer_payments row lands here
  // instead of the full app, no matter how far off next_payment_date is —
  // same informational, no self-serve-unlock pattern as the overdue screen
  // above.
  // Sept 7 2026, Jimmy: this screen now shows immediately on first login
  // after signup — before approval, not after — since the Trainers admin
  // panel's "Approve & confirm payment" action now approves the trainer and
  // logs this same payment together in one step. See the render-order
  // comment near the top-level router for the full reasoning.
  // Sept 12 2026, Jimmy: "the same design and popups and animation and flow
  // of what im sending you" — this is the real-app match for stepPayment in
  // jimfit-flow_1.html, which was missing the GateDecor background and the
  // staggered entrance the other gate screens already got.
  function TrainerFirstPaymentDueScreen({ trainer, onLogout }) {
    return e("div", { style: { ...styles.gateWrap, position: "relative" } },
      e(GateDecor, {}),
      e("div", { style: { ...styles.gateCard, position: "relative", zIndex: 1 } },
        e("div", { style: { opacity: 0, animation: "popIn 0.4s cubic-bezier(.16,1,.3,1) 0.06s forwards" } }, e(BrandMark, {})),
        e("h1", { style: { ...styles.gateTitle, opacity: 0, animation: "fadeUp 0.4s cubic-bezier(.16,1,.3,1) 0.16s forwards" } }, "One more step"),
        e("p", { style: { ...styles.gateSub, opacity: 0, animation: "fadeUp 0.4s cubic-bezier(.16,1,.3,1) 0.26s forwards" } },
          `Hi${trainer && trainer.name ? ` ${trainer.name}` : ""} — send your first month's payment below, then JimFit will confirm it and approve your account. You'll be able to log in and get started as soon as it's confirmed.`
        ),
        e("div", { style: { width: "100%", opacity: 0, animation: "fadeUp 0.4s cubic-bezier(.16,1,.3,1) 0.38s forwards" } },
          e(PaymentStatusStepper, {
            email: trainer && trainer.email, context: "trainer_first_payment",
            amount: (trainer && Number(trainer.rate_monthly)) || B2B_FLAT_RATE_MONTHLY,
            approvedCopy: "Approved — you're in"
          })
        ),
        e("button", { style: { ...styles.saveBtn, marginTop: 18, opacity: 0, animation: "fadeUp 0.4s cubic-bezier(.16,1,.3,1) 0.54s forwards" }, onClick: onLogout }, "Log out")
      )
    );
  }

  // Shown to a self-train client in place of the Log/Diet tabs once their
  // 14-day trial (or a previous month's payment) has run out. A client
  // still never has a "mark as paid" button of their own — only a manager
  // can flip that switch (see AppAccessCard below), after confirming the
  // Whish payment actually arrived — but PaymentStatusStepper above now
  // gives them a real "I've sent it" step instead of just instructions.
  function SelfTrainAccessLockedScreen({ profile, userEmail }) {
    const trialEnded = profile && profile.trial_ends_at && new Date(profile.trial_ends_at) <= new Date();
    return e("div", { style: { padding: "16px 18px 0" } },
      e("div", { style: { ...styles.setupNotice, flexDirection: "column", alignItems: "flex-start", gap: 8, padding: 16 } },
        e("div", { style: { display: "flex", alignItems: "center", gap: 8 } },
          e(Icon, { name: "lock", size: 16, color: C.ink3 }),
          e("span", { style: { fontFamily: "'Oswald', sans-serif", fontWeight: 600, fontSize: 15, letterSpacing: "0.02em", color: C.ink } },
            trialEnded ? "Your free trial has ended" : "Payment due to keep using the app"
          )
        ),
        e("p", { style: { margin: 0 } }, `$${SELF_TRAIN_MONTHLY_PRICE}/month keeps this unlocked — logging workouts, tracking food, and seeing calories burned vs. eaten.`),
        e("div", { style: { display: "flex", flexDirection: "column", gap: 3, margin: "4px 0" } },
          e("p", { style: { margin: 0, fontSize: 12.5, color: C.ink2 } }, "Instead of separate apps for lifting and food tracking, it's all in one place — plus a weekly muscle-balance view and AI Chat for when there's no coach to ask."),
        ),
        e(PaymentStatusStepper, { email: userEmail, context: "self_train_access", amount: SELF_TRAIN_MONTHLY_PRICE, approvedCopy: "Approved — unlocked" })
      )
    );
  }

export { TrainerAvatar, AutoSaveTextarea, InfoSectionCard, TrainerPendingApprovalScreen, TrainerPaymentOverdueScreen, TrainerFirstPaymentDueScreen, SelfTrainAccessLockedScreen };
