// @generated by tools/extract/extract.py — bodies copied verbatim from index.html
import { PRIVACY_POLICY_SECTIONS } from "../../domain/group1.js";
import { sb } from "../../platform/supabase.js";
import { BrandMark, GateDecor } from "../../shared/brand.js";
import { e } from "../../shared/react.js";
import { C, styles } from "../../shared/theme.js";
import { Icon } from "../../shared/ui/Icon.js";
import { useState } from "react";

  // "Start your own gym" signup is invite-only, not a public button — reached
  // only via a link with ?newgym=1 on it, handed out directly by Jimmy to
  // pilot gym owners he knows. Nobody stumbles into creating a gym by accident.
  const ALLOW_GYM_SIGNUP = (() => {
    try { return new URLSearchParams(window.location.search).get("newgym") === "1"; }
    catch (e) { return false; }
  })();

  // Sept 12 2026, Jimmy: "no eye password" — every password field on the
  // auth screens was a plain dot-masked input with no way to check what
  // you typed. Small show/hide "eye" toggle, same pattern as every other
  // app's password field, dropped in wherever a password is collected.
  function PasswordField({ value, onChange, placeholder, onKeyDown, autoFocus, style }) {
    const [visible, setVisible] = useState(false);
    return e("div", { style: { position: "relative" } },
      e("input", {
        type: visible ? "text" : "password",
        style: { ...styles.input, paddingRight: 40, ...(style || {}) },
        placeholder: placeholder || "••••••••",
        value, onChange, onKeyDown, autoFocus
      }),
      e("button", {
        type: "button",
        onClick: () => setVisible((v) => !v),
        "aria-label": visible ? "Hide password" : "Show password",
        style: {
          position: "absolute", right: 10, top: "50%", transform: "translateY(-50%)",
          background: "none", border: "none", padding: 4, display: "flex",
          alignItems: "center", justifyContent: "center", cursor: "pointer", color: C.ink3
        }
      }, e(Icon, { name: visible ? "eyeOff" : "eye", size: 17 }))
    );
  }

  function PrivacyPolicyModal({ onClose }) {
    return e("div", { style: styles.overlay, onClick: onClose },
      e("div", { style: { ...styles.sheet, maxWidth: 480 }, onClick: (ev) => ev.stopPropagation() },
        e("div", { style: styles.sheetHeader },
          e("span", { style: styles.sheetTitle }, "Privacy Policy"),
          e("button", { style: styles.closeBtn, onClick: onClose, "aria-label": "Close" }, e(Icon, { name: "x", size: 18 }))
        ),
        e("p", { style: { margin: "0 0 16px", fontSize: 11, color: C.ink3 } }, "Last updated September 2026"),
        e("div", { style: { display: "flex", flexDirection: "column", gap: 16 } }, PRIVACY_POLICY_SECTIONS.map((s) => e("div", { key: s.h },
          e("span", { style: { display: "block", fontFamily: "'Oswald', sans-serif", fontWeight: 600, fontSize: 13, letterSpacing: "0.02em", color: C.ink, marginBottom: 4 } }, s.h),
          e("p", { style: { margin: 0, fontSize: 12.5, color: C.ink2, lineHeight: 1.6 } }, s.p)
        )))
      )
    );
  }

  // Sept 12 2026, Jimmy: "the same design and popups and animation and flow
  // of what im sending you" — the reference file doesn't pop the whole card
  // in at once; each element fades/pops in on its own, staggered (logo,
  // title, subtitle, CTA), exactly matching jimfit-flow_1.html's timing.
  function WelcomeGate({ onContinue }) {
    const [showPrivacy, setShowPrivacy] = useState(false);
    return e("div", { style: { ...styles.gateWrap, position: "relative" } },
      e(GateDecor, {}),
      e("div", { style: { ...styles.gateCard, position: "relative", zIndex: 1 } },
        e("div", { style: { opacity: 0, animation: "popIn 0.4s cubic-bezier(.16,1,.3,1) 0.08s forwards" } }, e(BrandMark, {})),
        e("h1", { style: { ...styles.gateTitle, fontSize: 24, opacity: 0, animation: "fadeUp 0.4s cubic-bezier(.16,1,.3,1) 0.24s forwards" } }, "Welcome to JimFit"),
        e("p", { style: { ...styles.gateSub, opacity: 0, animation: "fadeUp 0.4s cubic-bezier(.16,1,.3,1) 0.38s forwards" } }, "Personal training, workout logging and nutrition — all in one place."),
        e("button", {
          style: {
            ...styles.wizardActionBtn, width: "100%", marginTop: 18, opacity: 0,
            animation: "fadeUp 0.4s cubic-bezier(.16,1,.3,1) 0.5s forwards, ctaPulse 2.2s ease-in-out 1.4s infinite"
          },
          onClick: onContinue
        }, "Get started"),
        e("button", {
          type: "button", onClick: () => setShowPrivacy(true),
          style: { display: "block", width: "100%", background: "none", border: "none", marginTop: 16, fontSize: 11.5, color: C.ink3, textDecoration: "underline", cursor: "pointer", padding: 0, opacity: 0, animation: "fadeUp 0.4s cubic-bezier(.16,1,.3,1) 0.6s forwards" }
        }, "Privacy Policy")
        // Sept 13 2026, Jimmy: "or i can hide it when they first get
        // started the clients" — the required RepDB exercise-data
        // attribution link used to live here too, right below Privacy
        // Policy. Moved off this very first screen down into the client
        // header (see TrainingLog, next to "Log out") — the license only
        // requires the credit to be visible somewhere in the app, not on
        // this specific welcome screen, and the header shows on every
        // client visit after they're past onboarding.
      ),
      showPrivacy && e(PrivacyPolicyModal, { onClose: () => setShowPrivacy(false) })
    );
  }

  // Sept 12 2026, Jimmy: same "same design and popups and animation and
  // flow" pass — role bubbles now use the reference's bouncier bubblePop
  // (overshoot + slight rotation) instead of the plain scale-in, staggered
  // at the reference's exact .18s/.42s delays.
  function RoleGate({ onPick, onBack, allowGymOwner }) {
    return e("div", { style: { ...styles.gateWrap, position: "relative" } },
      e(GateDecor, {}),
      onBack && e("button", {
        type: "button", onClick: onBack, style: styles.gateBackBtn
      }, e(Icon, { name: "back", size: 13 }), "Back"),
      e("div", { style: { ...styles.gateCard, position: "relative", zIndex: 1 } },
        e("div", { style: { opacity: 0, animation: "popIn 0.4s cubic-bezier(.16,1,.3,1) 0.06s forwards" } }, e(BrandMark, {})),
        e("p", { style: { ...styles.gateSub, fontSize: 15, fontWeight: 600, color: C.ink, marginTop: 8, opacity: 0, animation: "fadeUp 0.4s cubic-bezier(.16,1,.3,1) 0.16s forwards" } }, "How are you logging in?"),
        e("div", { style: { display: "flex", gap: 22, justifyContent: "center", marginTop: 8 } },
          e("button", { type: "button", style: { ...styles.roleCircleBtn, opacity: 0, animation: "bubblePop 0.68s cubic-bezier(.34,1.56,.64,1) 0.18s forwards" }, onClick: () => onPick("client") },
            e("div", { style: { ...styles.roleCircle, ...styles.roleCircleClient } }, e(Icon, { name: "user", size: 26, color: C.clientAccent })),
            e("span", { style: styles.roleCircleLabel }, "I'm a Client")
          ),
          e("button", { type: "button", style: { ...styles.roleCircleBtn, opacity: 0, animation: "bubblePop 0.68s cubic-bezier(.34,1.56,.64,1) 0.42s forwards" }, onClick: () => onPick("trainer") },
            e("div", { style: { ...styles.roleCircle, ...styles.roleCircleTrainer } }, e(Icon, { name: "calendar", size: 26, color: C.brand })),
            e("span", { style: styles.roleCircleLabel }, "I'm a Trainer")
          )
        ),
        allowGymOwner && e("button", {
          type: "button", onClick: () => onPick("gymowner"),
          style: { ...styles.switchModeBtn, marginTop: 22, opacity: 0, animation: "fadeUp 0.4s cubic-bezier(.16,1,.3,1) 0.6s forwards" }
        }, "Start your own gym →")
      )
    );
  }

  function ResetPasswordScreen({ onDone }) {
    const [password, setPassword] = useState("");
    const [confirm, setConfirm] = useState("");
    const [loading, setLoading] = useState(false);
    const [error, setError] = useState("");

    async function handleSave() {
      setError("");
      if (password.length < 6) { setError("Use at least 6 characters."); return; }
      if (password !== confirm) { setError("Passwords don't match."); return; }
      setLoading(true);
      const { error: err } = await sb.auth.updateUser({ password });
      setLoading(false);
      if (err) { setError(err.message || "Couldn't set your new password."); return; }
      onDone();
    }

    // Sept 15 2026, Jimmy: "fix... the reset password and new password
    // sections" — same GateDecor + staggered popIn/fadeUp entrance as the
    // other upgraded gate screens; this one was still the plain static
    // version. Fields/logic unchanged.
    return e("div", { style: { ...styles.gateWrap, position: "relative" } },
      e(GateDecor, {}),
      e("div", { style: { ...styles.gateCard, position: "relative", zIndex: 1 } },
        e("div", { style: { opacity: 0, animation: "popIn 0.4s cubic-bezier(.16,1,.3,1) 0.06s forwards" } }, e(BrandMark, {})),
        e("h1", { style: { ...styles.gateTitle, opacity: 0, animation: "fadeUp 0.4s cubic-bezier(.16,1,.3,1) 0.16s forwards" } }, "Set a new password"),
        e("p", { style: { ...styles.gateSub, opacity: 0, animation: "fadeUp 0.4s cubic-bezier(.16,1,.3,1) 0.26s forwards" } }, "Choose a new password for your account."),
        e("div", { style: { width: "100%", display: "flex", flexDirection: "column", gap: 12, opacity: 0, animation: "fadeUp 0.4s cubic-bezier(.16,1,.3,1) 0.38s forwards" } },
          e(PasswordField, {
            autoFocus: true, placeholder: "New password", value: password,
            onChange: (ev) => setPassword(ev.target.value)
          }),
          e(PasswordField, {
            placeholder: "Confirm new password", value: confirm,
            onChange: (ev) => setConfirm(ev.target.value),
            onKeyDown: (ev) => { if (ev.key === "Enter") handleSave(); }
          })
        ),
        error && e("span", { style: styles.inlineError }, error),
        e("button", {
          style: { ...styles.saveBtn, opacity: 0, animation: "fadeUp 0.4s cubic-bezier(.16,1,.3,1) 0.5s forwards", ...(loading ? styles.btnDisabled : {}) }, disabled: loading, onClick: handleSave
        }, loading ? "Saving…" : "Save new password")
      )
    );
  }

  function WizardShell({ step, totalSteps, onBack, hideBack = false, direction = "next", children }) {
    // The outer card no longer remounts (and re-pops) on every step — only
    // its very first appearance plays gatePop now. Each question's content
    // slides in on its own, direction-aware (see wizQSlideInRight/Left
    // above), which reads as one continuous quiz rather than a new card
    // popping up eight times in a row.
    return e("div", { style: { ...styles.profileGateWrap, position: "relative" } },
      e(GateDecor, {}),
      e("div", { style: { ...styles.profileGateCard, position: "relative", zIndex: 1, animation: "gatePop 0.3s ease-out" } },
        e("div", { style: styles.wizardProgressRow },
          !hideBack && e("button", { type: "button", style: styles.wizardBackCircle, onClick: onBack, "aria-label": "Back" }, e(Icon, { name: "back", size: 14 })),
          e("div", { style: styles.wizardProgressTrack },
            Array.from({ length: totalSteps }).map((_, i) =>
              e("div", { key: i, style: styles.wizardProgressSeg }, i <= step && e("div", { style: styles.wizardProgressSegFill }))
            )
          )
        ),
        e("div", { style: styles.wizardBody },
          e("div", {
            key: step,
            style: { display: "flex", flexDirection: "column", alignItems: "center", width: "100%", animation: `${direction === "back" ? "wizQSlideInLeft" : "wizQSlideInRight"} 0.32s cubic-bezier(.2,.8,.2,1)` }
          }, children)
        )
      )
    );
  }

export { ALLOW_GYM_SIGNUP, PasswordField, PrivacyPolicyModal, WelcomeGate, RoleGate, ResetPasswordScreen, WizardShell };
