// @generated by tools/extract/extract.py — bodies copied verbatim from index.html
import { fetchAssessmentHistory } from "../../data/group1.js";
import { recalcBmrAndTargets } from "../../data/recalcBmrAndTargets.js";
import { ASSESSMENT_METRICS, BODY_FAT_PCT_RANGE, FAT_MASS_KG_RANGE, WATER_PCT_RANGE, WEIGHT_KG_RANGE } from "../../domain/body.js";
import { inRange, isAutoAssessmentNote } from "../../domain/group3.js";
import { MUSCLE_MASS_KG_RANGE } from "../../domain/muscles.js";
import { MANUAL_BMR_RANGE } from "../../domain/nutrition.js";
import { sb } from "../../platform/supabase.js";
import { todayISO } from "../../shared/lib/dates.js";
import { fmtDate, fmtDateMed } from "../../shared/lib/format.js";
import { e } from "../../shared/react.js";
import { C, styles } from "../../shared/theme.js";
import { Icon } from "../../shared/ui/Icon.js";
import { AssessmentEmptyArt } from "../../shared/ui/empty-art.js";
import { VoiceMicButton } from "../../shared/widgets/VoiceMicButton.js";
import { MetricTrendCard } from "./group1.js";
import React, { useEffect, useState } from "react";

  // onSaved: optional — fires right after a new assessment is written. Only
  // needed where this panel sits on the SAME screen as something else that
  // reads body_assessments (today just DietLogPanel's "Energy balance" card,
  // on a trainer's own "My Diet" page) — that sibling fetches its own latest
  // BMR once on mount and has no other way to find out a fresh one was just
  // added right above it without a full page reload. Every other call site
  // leaves this unset and nothing changes for it.
  function AssessmentPanel({ userId, clientName, canManage = false, canDelete = canManage, onSaved = null }) {
    const [assessments, setAssessments] = useState([]);
    const [loaded, setLoaded] = useState(false);
    const [date, setDate] = useState(todayISO());
    const [weight, setWeight] = useState("");
    const [bodyFat, setBodyFat] = useState("");
    const [muscleMass, setMuscleMass] = useState("");
    const [fatMass, setFatMass] = useState("");
    const [waterPct, setWaterPct] = useState("");
    const [bmr, setBmr] = useState("");
    const [note, setNote] = useState("");
    const [saving, setSaving] = useState(false);
    const [error, setError] = useState("");
    // Sept 13 2026, Jimmy: inline "are you sure" instead of window.confirm()
    // — which history row (if any) has its delete button swapped for the
    // inline confirm bar.
    const [confirmDeleteId, setConfirmDeleteId] = useState(null);
    // Sept 18 2026: History has no way to narrow it down at all, unlike
    // Personal Records (which got a search for the exact same "too much to
    // scroll through" problem). A text search doesn't fit here — a reading
    // has no name, just a date — so this is a collapsible From/To date
    // range instead, same collapsed-behind-an-icon UX as PR's search.
    const [historySearchOpen, setHistorySearchOpen] = useState(false);
    const [historyFrom, setHistoryFrom] = useState("");
    const [historyTo, setHistoryTo] = useState("");

    useEffect(() => {
      if (!userId || !sb) { setAssessments([]); setLoaded(true); return; }
      setLoaded(false);
      sb.from("body_assessments").select("*").eq("user_id", userId).order("assessed_on", { ascending: true }).then(({ data, error: err }) => {
        if (!err && data) {
          setAssessments(data.map((r) => ({
            id: r.id, date: r.assessed_on, weight: r.weight_kg, bodyFat: r.body_fat_pct,
            muscleMass: r.muscle_mass_kg, fatMass: r.fat_mass_kg, waterPct: r.water_pct, bmr: r.bmr, note: r.note
          })));
        } else {
          setAssessments([]);
        }
        setLoaded(true);
      });
    }, [userId]);

    async function handleSave() {
      setError("");
      if (!date) { setError("Pick a date."); return; }
      const hasAny = [weight, bodyFat, muscleMass, fatMass, waterPct, bmr].some((v) => v !== "");
      if (!hasAny) { setError("Fill in at least one measurement."); return; }
      if (weight !== "" && !inRange(Number(weight), WEIGHT_KG_RANGE)) { setError(`Weight should be between ${WEIGHT_KG_RANGE[0]} and ${WEIGHT_KG_RANGE[1]} kg.`); return; }
      if (bodyFat !== "" && !inRange(Number(bodyFat), BODY_FAT_PCT_RANGE)) { setError(`Body fat % should be between ${BODY_FAT_PCT_RANGE[0]} and ${BODY_FAT_PCT_RANGE[1]}.`); return; }
      if (muscleMass !== "" && !inRange(Number(muscleMass), MUSCLE_MASS_KG_RANGE)) { setError(`Muscle mass should be between ${MUSCLE_MASS_KG_RANGE[0]} and ${MUSCLE_MASS_KG_RANGE[1]} kg.`); return; }
      if (fatMass !== "" && !inRange(Number(fatMass), FAT_MASS_KG_RANGE)) { setError(`Fat mass should be between ${FAT_MASS_KG_RANGE[0]} and ${FAT_MASS_KG_RANGE[1]} kg.`); return; }
      if (waterPct !== "" && !inRange(Number(waterPct), WATER_PCT_RANGE)) { setError(`Body water % should be between ${WATER_PCT_RANGE[0]} and ${WATER_PCT_RANGE[1]}.`); return; }
      if (bmr !== "" && !inRange(Number(bmr), MANUAL_BMR_RANGE)) { setError(`BMR should be between ${MANUAL_BMR_RANGE[0]} and ${MANUAL_BMR_RANGE[1]} kcal.`); return; }
      if (!sb || !userId) { setError("Backend not configured yet."); return; }
      setSaving(true);
      const payload = {
        user_id: userId, client_name: clientName, assessed_on: date,
        weight_kg: weight === "" ? null : Number(weight),
        body_fat_pct: bodyFat === "" ? null : Number(bodyFat),
        muscle_mass_kg: muscleMass === "" ? null : Number(muscleMass),
        fat_mass_kg: fatMass === "" ? null : Number(fatMass),
        water_pct: waterPct === "" ? null : Number(waterPct),
        bmr: bmr === "" ? null : Number(bmr),
        note: note.trim() || null
      };
      const { data, error: err } = await sb.from("body_assessments").insert([payload]).select();
      setSaving(false);
      if (err || !data) {
        console.error("[assessment-save] failed:", err);
        setError(`Couldn't save that assessment${err && err.message ? ` (${err.message})` : ""}. Try again.`);
        return;
      }
      const row = data[0];
      const mapped = { id: row.id, date: row.assessed_on, weight: row.weight_kg, bodyFat: row.body_fat_pct, muscleMass: row.muscle_mass_kg, fatMass: row.fat_mass_kg, waterPct: row.water_pct, bmr: row.bmr, note: row.note };
      setAssessments((prev) => [...prev, mapped].sort((a, b) => (a.date < b.date ? -1 : 1)));
      setWeight(""); setBodyFat(""); setMuscleMass(""); setFatMass(""); setWaterPct(""); setBmr(""); setNote("");
      // Sept 9 2026, Jimmy: "i changed the weight here for my client but the
      // bmr didnt change" — logging a fresh reading through THIS form never
      // recalculated BMR at all, unlike editing weight/height/age/gender via
      // "Edit profile" elsewhere, which already does (see recalcBmrAndTargets's
      // other call sites). That was a known, deliberate gap until now (see
      // maybeRecalcBmr's comment on the trainer self-track panel: "add it
      // later still works too, via the manual Assessments form... untouched
      // by this") — Jimmy now wants that path to auto-calculate too, same as
      // he asked for the BMR field itself: enter one and it's used as-is,
      // don't enter one and the app works it out.
      // Sept 9 2026, round 2: after trying this, Jimmy logged two more
      // weight-only readings on a client who already had a real 1895 BMR on
      // file — "if i already put my bmr from the assessment i dont want to
      // automatically calculate this i want it to calculate if only i didnt
      // put the assessment bmr." So this only fires at all when NOTHING has
      // ever been manually entered as a BMR for this person — once a real
      // one exists, logging more weight/body-fat/muscle-mass never touches
      // BMR again unless a new one is typed in right here.
      if (bmr === "" && (weight !== "" || bodyFat !== "" || muscleMass !== "")) {
        // Sept 9 2026, round 4: reuses the same consolidated "manual vs
        // auto" matching as recalcBmrAndTargets/fetchLatestDisplayAssessment
        // now, so the initial signup-calculated row counts as auto here too
        // (it didn't before) — otherwise a client who's never manually typed
        // in a BMR, but did complete signup, would look like she already
        // had a manual one and this would never fire for her at all.
        const existingHistory = await fetchAssessmentHistory(userId);
        const existingManualBmr = existingHistory.find((r) => !isAutoAssessmentNote(r.note) && r.bmr != null);
        if (!existingManualBmr) {
          const { data: profile } = await sb.from("client_profiles").select("*").eq("user_id", userId).maybeSingle();
          const w = weight !== "" ? Number(weight) : profile && profile.weight_kg;
          const result = await recalcBmrAndTargets(userId, clientName, {
            weight: w, height: profile && profile.height_cm, age: profile && profile.age,
            gender: profile && profile.gender, daysPerWeek: profile && profile.days_per_week, goal: profile && profile.goal
          });
          if (result && result.ok) {
            const { data: fresh, error: refetchErr } = await sb.from("body_assessments").select("*").eq("user_id", userId).order("assessed_on", { ascending: true });
            if (!refetchErr && fresh) {
              setAssessments(fresh.map((r) => ({
                id: r.id, date: r.assessed_on, weight: r.weight_kg, bodyFat: r.body_fat_pct,
                muscleMass: r.muscle_mass_kg, fatMass: r.fat_mass_kg, waterPct: r.water_pct, bmr: r.bmr, note: r.note
              })));
            }
          }
        }
      }
      if (onSaved) onSaved();
    }

    // Sept 6 2026, Jimmy: a trainer's newest auto-calculated BMR reading got
    // wiped out by an accidental tap here — no confirmation, no undo. Same
    // window.confirm pattern already used for a diet plan request/switch
    // elsewhere in the app.
    async function handleDelete(id) {
      setConfirmDeleteId(null);
      setAssessments((prev) => prev.filter((a) => a.id !== id));
      if (sb) await sb.from("body_assessments").delete().eq("id", id);
    }

    if (!loaded) return e("div", { style: styles.empty }, e("p", { style: styles.emptyText }, "Loading assessments…"));

    const latest = assessments.length > 0 ? assessments[assessments.length - 1] : null;
    const prevAssessment = assessments.length > 1 ? assessments[assessments.length - 2] : null;

    function deltaFor(field) {
      if (!prevAssessment || latest[field] == null || prevAssessment[field] == null) return null;
      const diff = latest[field] - prevAssessment[field];
      if (Math.abs(diff) < 0.05) return { text: "flat", dir: "flat" };
      return { text: `${diff > 0 ? "+" : ""}${Math.round(diff * 10) / 10}`, dir: diff > 0 ? "up" : "down" };
    }

    return e("div", null,
      // Sept 13 2026, Jimmy: "more pro and fun...less cluttered...branded"
      // — the same soft brand-gradient card treatment DietLogPanel's Energy
      // balance card already established (Sept 12), instead of a plain
      // neutral box, so this form doesn't look like a leftover unstyled
      // screen next to the rest of the (already-branded) Diet tab.
      canManage && e("div", { style: styles.assessmentFormCard },
        e("div", { style: { display: "flex", alignItems: "center", gap: 8, marginBottom: 4 } },
          e("span", { style: styles.progressCardTitle }, "Log a new reading")
        ),
        e("label", { style: styles.formLabel }, "Date"),
        // Sept 6 2026, Jimmy — took two rounds to actually find this: it
        // wasn't the box's WIDTH, it was that iOS Safari centers the value
        // text inside a native <input type="date"> no matter what text-align
        // is set to (a real iOS quirk, not fixable with CSS on the input
        // itself) — so "Sep 6, 2026" sat centered while every other field's
        // value sits left-aligned under its label, i.e. not lined up in the
        // same left column as everything else. Fix: render our own
        // left-aligned box showing the formatted date, with the real
        // <input type="date"> stretched invisibly on top of it so tapping
        // anywhere still opens the native date picker and still writes into
        // the same `date` state exactly as before.
        e("div", { style: { position: "relative" } },
          e("div", { style: { ...styles.input, display: "flex", alignItems: "center", pointerEvents: "none", color: date ? C.ink : C.ink3 } },
            date ? fmtDateMed(date) : "Pick a date"
          ),
          e("input", {
            type: "date", value: date, max: todayISO(), onChange: (ev) => setDate(ev.target.value),
            style: { position: "absolute", inset: 0, width: "100%", height: "100%", opacity: 0, border: 0, padding: 0, margin: 0, cursor: "pointer" }
          })
        ),
        // Sept 13 2026: an emoji per field (same house pattern as ASSESSMENT_METRICS
        // below and DietLogPanel's own labels) — six identical gray boxes
        // become six quickly-scannable ones without changing what's asked for.
        e("div", { style: styles.assessmentFormGrid },
          e("div", null, e("label", { style: styles.formLabel }, "⚖️ Weight (kg)"), e("input", { type: "number", min: "0", step: "0.1", style: styles.input, value: weight, onChange: (ev) => setWeight(ev.target.value) })),
          e("div", null, e("label", { style: styles.formLabel }, "📊 Body fat (%)"), e("input", { type: "number", min: "0", step: "0.1", style: styles.input, value: bodyFat, onChange: (ev) => setBodyFat(ev.target.value) })),
          e("div", null, e("label", { style: styles.formLabel }, "💪 Muscle mass (kg)"), e("input", { type: "number", min: "0", step: "0.1", style: styles.input, value: muscleMass, onChange: (ev) => setMuscleMass(ev.target.value) })),
          e("div", null, e("label", { style: styles.formLabel }, "📉 Fat mass (kg)"), e("input", { type: "number", min: "0", step: "0.1", style: styles.input, value: fatMass, onChange: (ev) => setFatMass(ev.target.value) })),
          e("div", null, e("label", { style: styles.formLabel }, "💧 Body water (%)"), e("input", { type: "number", min: "0", step: "0.1", style: styles.input, value: waterPct, onChange: (ev) => setWaterPct(ev.target.value) })),
          e("div", null, e("label", { style: styles.formLabel }, "🔥 BMR (kcal)"), e("input", { type: "number", min: "0", step: "1", style: styles.input, value: bmr, onChange: (ev) => setBmr(ev.target.value) }))
        ),
        e("div", { style: { display: "flex", gap: 8, marginTop: 10, marginBottom: 12 } },
          e("input", { style: { ...styles.input, flex: 1 }, placeholder: "Note (optional)", value: note, onChange: (ev) => setNote(ev.target.value) }),
          e(VoiceMicButton, { title: "Say a note", onTranscribed: setNote })
        ),
        error && e("div", { style: { ...styles.errorBanner, marginBottom: 12 } }, e(Icon, { name: "x", size: 13, color: C.critical }), error),
        e("button", { style: { ...styles.saveBtn, marginTop: 0, ...(saving ? styles.btnDisabled : {}) }, disabled: saving, onClick: handleSave }, e(Icon, { name: "check", size: 15 }), saving ? "Saving…" : "Save assessment")
      ),
      assessments.length === 0 && e("div", { style: styles.empty }, e(AssessmentEmptyArt, {}), e("p", { style: styles.emptyText }, "No assessments logged yet.")),
      latest && e(React.Fragment, null,
        e("div", { style: styles.sectionHead }, e("span", { style: styles.sectionTitle }, "Latest — ", fmtDate(latest.date))),
        e("div", { style: styles.assessmentSummaryGrid }, ASSESSMENT_METRICS.map((m) => {
          const val = latest[m.key];
          if (val === null || val === undefined) return null;
          const d = deltaFor(m.key);
          // Sept 13 2026: local flex+icon override on this card only (see
          // the comment on assessmentMetricCard's shared definition) — a
          // small brand-tinted emoji badge instead of the label sitting
          // alone above the value.
          return e("div", { key: m.key, style: { ...styles.assessmentMetricCard, display: "flex", alignItems: "center", gap: 10 } },
            e("span", { style: styles.assessmentMetricIcon }, m.emoji),
            e("div", { style: { minWidth: 0 } },
              e("span", { style: styles.profileLabel }, m.label),
              e("div", { style: { display: "flex", alignItems: "baseline", gap: 6, flexWrap: "wrap" } },
                e("span", { style: styles.profileValue }, val, e("span", { style: styles.statUnit }, " ", m.unit)),
                d && d.dir !== "flat" && e("span", { style: styles.assessmentDelta }, e(Icon, { name: d.dir === "up" ? "trendUp" : "trendDown", size: 10, strokeWidth: 2.5 }), d.text)
              )
            )
          );
        }))
      ),
      // Sept 18 2026: "no trend view" review finding — see MetricTrendCard's
      // own comment for the full reasoning. assessments is already sorted
      // ascending by date from the fetch above, which is exactly what the
      // chart needs.
      assessments.length > 1 && e(React.Fragment, null,
        e("div", { style: { ...styles.sectionHead, marginTop: 22 } }, e("span", { style: styles.sectionTitle }, "Trend")),
        e(MetricTrendCard, { rows: assessments, metrics: ASSESSMENT_METRICS })
      ),
      assessments.length > 0 && (() => {
        const historyFiltered = assessments.filter((a) => (!historyFrom || a.date >= historyFrom) && (!historyTo || a.date <= historyTo));
        return e(React.Fragment, null,
        e("div", { style: { ...styles.sectionHead, marginTop: 22, flexDirection: "row", alignItems: "center", justifyContent: "space-between" } },
          e("span", { style: styles.sectionTitle }, "History"),
          e("button", {
            style: { ...styles.prSearchBtn, ...(historySearchOpen ? styles.prSearchBtnActive : {}) },
            onClick: () => { setHistorySearchOpen((v) => !v); if (historySearchOpen) { setHistoryFrom(""); setHistoryTo(""); } },
            "aria-label": "Filter by date"
          }, e(Icon, { name: historySearchOpen ? "x" : "search", size: 14 }))
        ),
        historySearchOpen && e("div", { style: { display: "flex", gap: 8, marginBottom: 12 } },
          e("input", { type: "date", style: { ...styles.input, flex: 1 }, value: historyFrom, max: historyTo || todayISO(), onChange: (ev) => setHistoryFrom(ev.target.value) }),
          e("input", { type: "date", style: { ...styles.input, flex: 1 }, value: historyTo, min: historyFrom || undefined, max: todayISO(), onChange: (ev) => setHistoryTo(ev.target.value) })
        ),
        historyFiltered.length === 0 && e("p", { style: styles.emptyText }, "No readings in that range."),
        e("div", { style: { display: "flex", flexDirection: "column", gap: 8 } }, historyFiltered.slice().reverse().map((a) => e("div", { key: a.id, style: styles.assessmentRow },
          e("div", { style: { display: "flex", justifyContent: "space-between", alignItems: "center" } },
            e("span", { style: styles.profileLabel }, fmtDate(a.date)),
            canDelete && confirmDeleteId !== a.id && e("button", { style: styles.deleteBtn, onClick: () => setConfirmDeleteId(a.id), "aria-label": "Delete assessment" }, e(Icon, { name: "trash", size: 13 }))
          ),
          confirmDeleteId === a.id
            ? e("div", { style: { ...styles.deleteConfirmBar, marginTop: 6 } },
                e("span", { style: styles.deleteConfirmText }, "Delete this assessment? Affects BMR/target calcs that used it."),
                e("div", { style: { display: "flex", gap: 6, flexShrink: 0 } },
                  e("button", { type: "button", style: styles.setConfirmCancelBtn, onClick: () => setConfirmDeleteId(null) }, "Cancel"),
                  e("button", { type: "button", style: styles.setConfirmDangerBtn, onClick: () => handleDelete(a.id) }, "Delete")
                )
              )
            : e(React.Fragment, null,
                e("div", { style: styles.assessmentRowValues }, ASSESSMENT_METRICS.map((m) => (a[m.key] === null || a[m.key] === undefined) ? null : e("span", { key: m.key, style: styles.assessmentRowChip }, `${m.emoji} ${a[m.key]}${m.unit}`))),
                a.note && e("p", { style: styles.profileGoalText }, a.note)
              )
        )))
      );
      })()
    );
  }

export { AssessmentPanel };
