// @generated by tools/extract/extract.py — bodies copied verbatim from index.html
import { notifyTrainer } from "../../data/group1.js";
import { detectMoodEmoji } from "../../domain/group2.js";
import { sb } from "../../platform/supabase.js";
import { e } from "../../shared/react.js";
import { C, styles } from "../../shared/theme.js";
import { Icon } from "../../shared/ui/Icon.js";
import { CheckInVoiceCapture } from "../voice/index.js";
import { useEffect, useState } from "react";

  // Shown on a client's own Log tab (canManage: true — they can speak a new one) and
  // on a trainer/manager's view of that same client (canManage: false — read-only,
  // so a trainer glancing at a client's page can see how they've been feeling without
  // the client having to say it out loud in person first).
  function CheckInPanel({ clientId, clientName, canManage = false, trainerId = null }) {
    const [checkIns, setCheckIns] = useState([]);
    const [loaded, setLoaded] = useState(false);
    const [showRecorder, setShowRecorder] = useState(false);
    const [saving, setSaving] = useState(false);
    const [saveError, setSaveError] = useState("");
    // Sept 18 2026: this list was hard-capped at the 8 most recent check-ins
    // with no way to see older ones at all — older notes were effectively
    // gone. Page size stays 8 (keeps the initial load light), but now a
    // "Show older" button pages in the next 8 instead of that being the end.
    const [hasMore, setHasMore] = useState(false);
    const [loadingMore, setLoadingMore] = useState(false);
    const PAGE_SIZE = 8;

    useEffect(() => {
      if (!sb || !clientId) { setLoaded(true); return; }
      setLoaded(false);
      setHasMore(false);
      sb.from("client_check_ins").select("*").eq("client_id", clientId).order("created_at", { ascending: false }).range(0, PAGE_SIZE - 1)
        .then(({ data, error: err }) => {
          if (!err && data) { setCheckIns(data); setHasMore(data.length === PAGE_SIZE); }
          setLoaded(true);
        });
    }, [clientId]);

    async function handleLoadMore() {
      if (!sb || !clientId || loadingMore) return;
      setLoadingMore(true);
      const { data, error: err } = await sb.from("client_check_ins").select("*").eq("client_id", clientId)
        .order("created_at", { ascending: false }).range(checkIns.length, checkIns.length + PAGE_SIZE - 1);
      setLoadingMore(false);
      if (err || !data) return;
      setCheckIns((prev) => [...prev, ...data]);
      setHasMore(data.length === PAGE_SIZE);
    }

    async function saveNote(note) {
      if (!sb || !clientId || !note.trim()) return false;
      setSaving(true);
      setSaveError("");
      const { data, error: err } = await sb.from("client_check_ins")
        .insert([{ client_id: clientId, client_name: clientName, note: note.trim() }])
        .select();
      setSaving(false);
      if (err || !data) { setSaveError("Couldn't save that check-in — try again."); return false; }
      setCheckIns((prev) => [data[0], ...prev]);
      setShowRecorder(false);
      // Sept 17 2026, Jimmy: "the trainers how they get notifications" —
      // client check-ins is one of the three events he wants pushed. Only
      // reachable here when canManage is true (the client speaking their own
      // note — see this component's own header comment), never when a
      // trainer/manager is just viewing a client's check-ins read-only.
      if (trainerId) notifyTrainer(trainerId, `${clientName} checked in: "${note.trim().slice(0, 100)}"`);
      return true;
    }

    async function handleDelete(id) {
      const idx = checkIns.findIndex((c) => c.id === id);
      const target = idx !== -1 ? checkIns[idx] : null;
      setCheckIns((prev) => prev.filter((c) => c.id !== id));
      if (!sb) return;
      const { error: err } = await sb.from("client_check_ins").delete().eq("id", id);
      if (err) {
        // Delete failed server-side — put the row back rather than leaving
        // the screen showing a delete that didn't actually happen.
        if (target) setCheckIns((prev) => { const next = [...prev]; next.splice(Math.min(idx, next.length), 0, target); return next; });
        setSaveError(`Couldn't delete that${err.message ? ` (${err.message})` : ""}. Try again.`);
      }
    }

    if (!clientId) return null;

    // Sept 11 2026, Jimmy: "make it look like a branded app like we did for
    // the program and diet to look less cluttery" — header now carries the
    // same brand-accent left border every other section head on
    // Programs/Diet uses instead of a bare flex row, and each check-in is
    // now an icon-wrap card (same anatomy as a browseCard) instead of a
    // plain bordered box, so this reads as one consistent design language
    // with the rest of the app rather than a leftover older screen.
    return e("div", { style: { marginBottom: 18 } },
      e("div", { style: { display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 10, paddingLeft: 11, borderLeft: `3px solid ${C.brand}` } },
        e("span", { style: styles.sectionTitle }, "Check-ins"),
        // Sept 12 2026, Jimmy: "change the check in phrase to something more
        // understandable for clients" — "Speak a check-in" read like an
        // internal feature name; this is just telling someone how you're
        // doing today, so the button now says exactly that.
        canManage && e("button", {
          style: { ...styles.ghostPillBtn, width: "auto", padding: "8px 14px", display: "flex", alignItems: "center", gap: 6 },
          onClick: () => setShowRecorder((v) => !v)
        }, e(Icon, { name: "mic", size: 13 }), showRecorder ? "Cancel" : "Tell us how you're doing")
      ),
      showRecorder && e(CheckInVoiceCapture, { onSave: saveNote, saving }),
      saveError && e("div", { style: { ...styles.inlineError, marginBottom: 8 } }, saveError),
      !loaded ? e("p", { style: styles.emptyText }, "Loading…")
        : checkIns.length === 0
        ? e("p", { style: { ...styles.emptyText, fontStyle: "italic", fontSize: 13 } }, canManage ? "Nothing yet — tap the mic and tell us how you're doing today." : "No check-ins from this client yet.")
        : e("div", { style: { display: "flex", flexDirection: "column", gap: 10 } },
            checkIns.map((c) => {
              // A detected mood emoji replaces the generic mic icon on that
              // card, so scanning the list at a glance shows who's sore,
              // tired, excited, etc. without reading every note.
              const mood = detectMoodEmoji(c.note);
              return e("div", { key: c.id, style: { ...styles.browseCard, padding: 14, flexDirection: "row", alignItems: "flex-start" } },
                e("div", { style: styles.browseCardIconWrap }, mood ? e("span", { style: { fontSize: 16 } }, mood) : e(Icon, { name: "mic", size: 16, color: C.ink2 })),
                e("div", { style: { flex: 1, minWidth: 0 } },
                  e("p", { style: { margin: 0, fontSize: 13.5, color: C.ink, lineHeight: 1.5 } }, c.note),
                  e("span", { style: { fontSize: 11, color: C.ink3, fontFamily: "'JetBrains Mono', monospace" } },
                    new Date(c.created_at).toLocaleString(undefined, { month: "short", day: "numeric", hour: "numeric", minute: "2-digit" }))
                ),
                canManage && e("button", { style: styles.deleteBtn, onClick: () => handleDelete(c.id), "aria-label": "Delete check-in" }, e(Icon, { name: "trash", size: 14 }))
              );
            })
          ),
      hasMore && e("button", {
        type: "button",
        style: { ...styles.ghostPillBtn, width: "100%", marginTop: 10, ...(loadingMore ? styles.btnDisabled : {}) },
        disabled: loadingMore,
        onClick: handleLoadMore
      }, loadingMore ? "Loading…" : "Show older check-ins")
    );
  }

export { CheckInPanel };
