// @generated by tools/extract/extract.py — bodies copied verbatim from index.html
import { sb } from "../../platform/supabase.js";
import { BrandMark } from "../../shared/brand.js";
import { todayISO } from "../../shared/lib/dates.js";
import { fmtDate, fmtDateMed } from "../../shared/lib/format.js";
import { e } from "../../shared/react.js";
import { C, styles } from "../../shared/theme.js";
import { Icon } from "../../shared/ui/Icon.js";
import { Select } from "../../shared/ui/group1.js";
import React, { useEffect, useRef, useState } from "react";

  function ProgressPanel({ userId, clientName, canManage = false }) {
    const [photos, setPhotos] = useState([]);
    const [loaded, setLoaded] = useState(false);
    const [uploading, setUploading] = useState(false);
    const [takenOn, setTakenOn] = useState(todayISO());
    const [note, setNote] = useState("");
    const [error, setError] = useState("");
    const fileInputRef = useRef(null);
    // Which two photos are picked for the before/after comparison — defaults
    // to earliest vs. most recent (the obvious pair), but a client or trainer
    // can pick any two dates instead, e.g. two specific check-ins to compare.
    const [compareLeftId, setCompareLeftId] = useState(null);
    const [compareRightId, setCompareRightId] = useState(null);
    // Sept 13 2026, Jimmy: inline "are you sure" instead of window.confirm()
    // — which photo card (if any) has its delete button swapped for the
    // inline confirm bar.
    const [confirmDeletePhotoId, setConfirmDeletePhotoId] = useState(null);
    // Sept 15 2026, Jimmy: "make this section more interactive and engaging
    // with clients... 2 compares the before and after and be pro and
    // branded" — the static side-by-side "Before/after" got replaced with a
    // draggable slide-to-reveal compare card (sliderPos, sliderRef, the
    // pointer handlers below), a JimFit-branded header, and a computed
    // "X weeks apart" badge. The "All photos" grid also gained a tap-to-
    // -zoom lightbox (zoomedPhotoId) instead of only ever showing thumbnails.
    const [sliderPos, setSliderPos] = useState(50);
    const sliderRef = useRef(null);
    const draggingRef = useRef(false);
    const [zoomedPhotoId, setZoomedPhotoId] = useState(null);

    useEffect(() => {
      if (!userId || !sb) { setPhotos([]); setLoaded(true); return; }
      setLoaded(false);
      sb.from("progress_photos").select("*").eq("user_id", userId).order("taken_on", { ascending: true }).then(async ({ data, error: err }) => {
        if (err || !data) { setPhotos([]); setLoaded(true); return; }
        const withUrls = await Promise.all(data.map(async (r) => {
          const { data: signed } = await sb.storage.from("progress-photos").createSignedUrl(r.storage_path, 3600);
          return { id: r.id, takenOn: r.taken_on, note: r.note, path: r.storage_path, url: signed ? signed.signedUrl : null };
        }));
        setPhotos(withUrls);
        setLoaded(true);
      });
    }, [userId]);

    // Recenters the drag handle whenever a different pair of photos is
    // picked to compare, so it never starts a new comparison mid-drag from
    // wherever the last one was left.
    useEffect(() => { setSliderPos(50); }, [compareLeftId, compareRightId]);

    async function handleUpload(ev) {
      const file = ev.target.files && ev.target.files[0];
      if (!file) return;
      setError("");
      if (!sb || !userId) { setError("Backend not configured yet."); return; }
      setUploading(true);
      const path = `${userId}/${Date.now()}_${file.name.replace(/[^a-zA-Z0-9._-]/g, "")}`;
      const { error: upErr } = await sb.storage.from("progress-photos").upload(path, file);
      if (upErr) { setUploading(false); setError("Couldn't upload that photo. Try again."); return; }
      const { data, error: insErr } = await sb.from("progress_photos").insert([{
        user_id: userId, client_name: clientName, storage_path: path, taken_on: takenOn, note: note.trim() || null
      }]).select();
      setUploading(false);
      if (insErr || !data) { setError("Photo uploaded but couldn't save the record. Try again."); return; }
      const { data: signed } = await sb.storage.from("progress-photos").createSignedUrl(path, 3600);
      const row = data[0];
      setPhotos((prev) => [...prev, { id: row.id, takenOn: row.taken_on, note: row.note, path, url: signed ? signed.signedUrl : null }].sort((a, b) => (a.takenOn < b.takenOn ? -1 : 1)));
      setNote("");
      if (fileInputRef.current) fileInputRef.current.value = "";
    }

    async function handleDeletePhoto(photo) {
      setConfirmDeletePhotoId(null);
      setZoomedPhotoId((id) => (id === photo.id ? null : id));
      setPhotos((prev) => prev.filter((p) => p.id !== photo.id));
      if (sb) {
        await sb.from("progress_photos").delete().eq("id", photo.id);
        await sb.storage.from("progress-photos").remove([photo.path]);
      }
    }

    if (!loaded) return e("div", { style: styles.empty }, e("p", { style: styles.emptyText }, "Loading photos…"));

    const first = photos.length > 0 ? photos[0] : null;
    const last = photos.length > 1 ? photos[photos.length - 1] : null;
    const photoOptions = photos.map((p) => ({ value: p.id, label: fmtDateMed(p.takenOn) + (p.note ? ` — ${p.note}` : "") }));
    const compareLeft = photos.find((p) => p.id === compareLeftId) || first;
    const compareRight = photos.find((p) => p.id === compareRightId) || last;
    const compareDiffDays = compareLeft && compareRight
      ? Math.abs(Math.round((new Date(compareRight.takenOn) - new Date(compareLeft.takenOn)) / 86400000))
      : null;
    const durationLabel = compareDiffDays == null ? null
      : compareDiffDays === 0 ? "Same day"
      : compareDiffDays < 14 ? `${compareDiffDays} day${compareDiffDays === 1 ? "" : "s"} apart`
      : `${Math.round(compareDiffDays / 7)} weeks apart`;
    const zoomedPhoto = photos.find((p) => p.id === zoomedPhotoId) || null;

    // Drag-to-reveal handlers for the before/after slider — pointer capture
    // means the handle keeps tracking the finger/cursor even once it leaves
    // the card's bounds, so a fast drag never "drops" the slider mid-swipe.
    function updateSliderFromEvent(ev) {
      const el = sliderRef.current;
      if (!el) return;
      const rect = el.getBoundingClientRect();
      const pct = ((ev.clientX - rect.left) / rect.width) * 100;
      setSliderPos(Math.max(0, Math.min(100, pct)));
    }
    function handleSliderPointerDown(ev) {
      draggingRef.current = true;
      try { ev.currentTarget.setPointerCapture(ev.pointerId); } catch (e) {}
      updateSliderFromEvent(ev);
    }
    function handleSliderPointerMove(ev) {
      if (!draggingRef.current) return;
      updateSliderFromEvent(ev);
    }
    function handleSliderPointerUp() { draggingRef.current = false; }
    const compareBadgeStyle = { position: "absolute", top: 10, background: "rgba(11,21,38,0.7)", color: "#FFFFFF", fontFamily: "'JetBrains Mono', monospace", fontSize: 10, fontWeight: 700, letterSpacing: 0.6, padding: "4px 9px", borderRadius: 20, backdropFilter: "blur(3px)", pointerEvents: "none" };
    const compareDateChipStyle = { position: "absolute", bottom: 10, background: "rgba(11,21,38,0.7)", color: "#FFFFFF", fontFamily: "'JetBrains Mono', monospace", fontSize: 10, fontWeight: 600, padding: "4px 8px", borderRadius: 8, backdropFilter: "blur(3px)", pointerEvents: "none" };

    return e("div", null,
      canManage && e("div", { style: styles.sessionForm },
        e("label", { style: styles.formLabel }, "Date"),
        e("input", { type: "date", value: takenOn, max: todayISO(), onChange: (ev) => setTakenOn(ev.target.value), style: styles.input }),
        e("input", { style: { ...styles.input, marginTop: 10, marginBottom: 12 }, placeholder: 'Note (optional) — e.g. "Week 4"', value: note, onChange: (ev) => setNote(ev.target.value) }),
        error && e("div", { style: { ...styles.errorBanner, marginBottom: 12 } }, e(Icon, { name: "x", size: 13, color: C.critical }), error),
        e("input", { ref: fileInputRef, type: "file", accept: "image/*", onChange: handleUpload, disabled: uploading, style: { display: "none" }, id: "progress-photo-input" }),
        e("label", { htmlFor: "progress-photo-input", style: { ...styles.saveBtn, ...(uploading ? styles.btnDisabled : {}), display: "flex", justifyContent: "center", cursor: uploading ? "default" : "pointer" } },
          e(Icon, { name: "camera", size: 16 }), uploading ? "Uploading…" : "Add progress photo"
        )
      ),
      // Sept 15 2026, Jimmy: "still same" — re: the empty state, before any
      // photos exist. The "Your transformation" hero card below only ever
      // renders once there are 2+ photos, so a client's very first look at
      // this tab was still the plain old gray icon + one line of text. This
      // gives the empty state the same branded treatment as the hero card —
      // JimFit mark, a "ghost" preview of the drag-slider (so the feature is
      // visible before there's any real data to power it) — instead of only
      // improving what shows up once photos already exist.
      photos.length === 0 && e("div", { style: { ...styles.goalCard, marginBottom: 16, textAlign: "center" } },
        e(BrandMark, { size: 36 }),
        e("p", { style: { fontFamily: "'Oswald', sans-serif", fontWeight: 600, fontSize: 15, letterSpacing: "0.02em", color: C.ink, margin: "12px 0 4px" } }, "Start your transformation story"),
        e("p", { style: { ...styles.profileGoalText, maxWidth: 260, margin: "0 auto 16px" } }, "Snap a photo at every check-in and it builds into a before/after you can drag through, right here."),
        e("div", {
          style: {
            position: "relative", width: "100%", maxWidth: 200, margin: "0 auto",
            aspectRatio: "3/4", borderRadius: 16, overflow: "hidden",
            border: `1px dashed ${C.cardBorderStrong}`, background: C.subtleFill
          }
        },
          e("div", { style: { position: "absolute", inset: 0, right: "50%", display: "flex", alignItems: "center", justifyContent: "center", borderRight: `1px dashed ${C.cardBorderStrong}` } }, e(Icon, { name: "camera", size: 22, color: C.ink3 })),
          e("div", { style: { position: "absolute", inset: 0, left: "50%", display: "flex", alignItems: "center", justifyContent: "center" } }, e(Icon, { name: "camera", size: 22, color: C.ink3 })),
          e("span", { style: { position: "absolute", top: 8, left: 8, fontFamily: "'JetBrains Mono', monospace", fontSize: 9, fontWeight: 700, letterSpacing: 0.5, color: C.ink3, background: C.card, border: `1px solid ${C.cardBorder}`, borderRadius: 20, padding: "3px 8px" } }, "BEFORE"),
          e("span", { style: { position: "absolute", top: 8, right: 8, fontFamily: "'JetBrains Mono', monospace", fontSize: 9, fontWeight: 700, letterSpacing: 0.5, color: C.ink3, background: C.card, border: `1px solid ${C.cardBorder}`, borderRadius: 20, padding: "3px 8px" } }, "AFTER"),
          e("div", { style: { position: "absolute", top: "50%", left: "50%", transform: "translate(-50%,-50%)", width: 30, height: 30, borderRadius: "50%", background: C.card, border: `1px solid ${C.cardBorderStrong}`, display: "flex", alignItems: "center", justifyContent: "center" } }, e(Icon, { name: "swap", size: 14, color: C.ink3 }))
        )
      ),
      first && last && e(React.Fragment, null,
        e("div", { style: { ...styles.goalCard, marginBottom: 16 } },
          e("div", { style: { display: "flex", alignItems: "center", gap: 10, marginBottom: 14 } },
            e(BrandMark, { size: 32 }),
            e("div", null,
              e("div", { style: { fontFamily: "'Oswald', sans-serif", fontWeight: 600, fontSize: 14, letterSpacing: "0.02em", color: C.ink } }, "Your transformation"),
              durationLabel && e("div", { style: { fontFamily: "'JetBrains Mono', monospace", fontSize: 10.5, color: C.brand, fontWeight: 700, letterSpacing: 0.4, marginTop: 2 } }, durationLabel)
            )
          ),
          e("div", { style: { display: "flex", gap: 10, marginBottom: 12, flexWrap: "wrap" } },
            e("div", { style: { flex: 1, minWidth: 130 } },
              e("span", { style: styles.profileLabel }, "Before"),
              e(Select, { value: compareLeft ? compareLeft.id : "", onChange: setCompareLeftId, options: photoOptions, style: { width: "100%" } })
            ),
            e("div", { style: { flex: 1, minWidth: 130 } },
              e("span", { style: styles.profileLabel }, "After"),
              e(Select, { value: compareRight ? compareRight.id : "", onChange: setCompareRightId, options: photoOptions, style: { width: "100%" } })
            )
          ),
          compareLeft && compareRight && e("div", {
            ref: sliderRef,
            style: { position: "relative", width: "100%", aspectRatio: "3/4", borderRadius: 16, overflow: "hidden", border: `1px solid ${C.cardBorderStrong}`, cursor: "ew-resize", touchAction: "none", userSelect: "none", background: C.subtleFill, boxShadow: "0 8px 24px rgba(0,0,0,0.22)" },
            onPointerDown: handleSliderPointerDown,
            onPointerMove: handleSliderPointerMove,
            onPointerUp: handleSliderPointerUp,
            onPointerCancel: handleSliderPointerUp
          },
            e("img", { src: compareRight.url, draggable: false, alt: "After", style: { position: "absolute", inset: 0, width: "100%", height: "100%", objectFit: "cover" } }),
            e("img", {
              src: compareLeft.url, draggable: false, alt: "Before",
              style: { position: "absolute", inset: 0, width: "100%", height: "100%", objectFit: "cover", clipPath: `inset(0 ${100 - sliderPos}% 0 0)` }
            }),
            e("span", { style: { ...compareBadgeStyle, left: 10 } }, "BEFORE"),
            e("span", { style: { ...compareBadgeStyle, right: 10 } }, "AFTER"),
            e("span", { style: { ...compareDateChipStyle, left: 10 } }, fmtDateMed(compareLeft.takenOn)),
            e("span", { style: { ...compareDateChipStyle, right: 10 } }, fmtDateMed(compareRight.takenOn)),
            e("div", { style: { position: "absolute", top: 0, bottom: 0, left: `${sliderPos}%`, width: 0, borderLeft: "2px solid #FFFFFF", boxShadow: "0 0 0 1px rgba(0,0,0,0.25)", pointerEvents: "none" } }),
            e("div", {
              style: {
                position: "absolute", top: "50%", left: `${sliderPos}%`, transform: "translate(-50%,-50%)",
                width: 36, height: 36, borderRadius: "50%", background: "#FFFFFF",
                display: "flex", alignItems: "center", justifyContent: "center",
                boxShadow: "0 2px 10px rgba(0,0,0,0.35)", pointerEvents: "none"
              }
            }, e(Icon, { name: "swap", size: 16, color: C.brand }))
          ),
          compareLeft && compareRight && e("div", { style: { textAlign: "center", marginTop: 10, fontSize: 11.5, color: C.ink3 } }, "Drag to compare")
        )
      ),
      photos.length > 0 && e(React.Fragment, null,
        e("div", { style: styles.sectionHead }, e("span", { style: styles.sectionTitle }, "All photos")),
        e("div", { style: styles.photoGrid }, photos.slice().reverse().map((p) => e("div", { key: p.id, style: styles.photoCard },
          e("img", { src: p.url, alt: `Progress photo from ${fmtDate(p.takenOn)}`, style: { ...styles.photoThumb, cursor: "pointer" }, onClick: () => setZoomedPhotoId(p.id) }),
          e("div", { style: styles.photoMeta },
            e("span", { style: styles.profileLabel }, fmtDate(p.takenOn)),
            p.note && e("span", { style: styles.profileGoalText }, p.note)
          ),
          canManage && (
            confirmDeletePhotoId === p.id
              ? e("div", { style: { ...styles.deleteConfirmBar, flexDirection: "column", alignItems: "stretch", gap: 6, padding: 8 } },
                  e("span", { style: { ...styles.deleteConfirmText, fontSize: 11 } }, "Delete this photo?"),
                  e("div", { style: { display: "flex", gap: 6 } },
                    e("button", { type: "button", style: { ...styles.setConfirmCancelBtn, flex: 1 }, onClick: () => setConfirmDeletePhotoId(null) }, "Cancel"),
                    e("button", { type: "button", style: { ...styles.setConfirmDangerBtn, flex: 1 }, onClick: () => handleDeletePhoto(p) }, "Delete")
                  )
                )
              : e("button", { style: styles.deleteBtn, onClick: () => setConfirmDeletePhotoId(p.id), "aria-label": "Delete photo" }, e(Icon, { name: "trash", size: 14 }))
          )
        )))
      ),
      // Sept 15 2026, Jimmy — tap any thumbnail in "All photos" to see it full
      // size with its date/note, same fullscreen tap-to-dismiss pattern as
      // TrainerAvatar's photo zoom elsewhere in the app.
      zoomedPhoto && e("div", {
        style: { position: "fixed", inset: 0, background: C.scrim, display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", zIndex: 70, padding: 24 },
        onClick: () => setZoomedPhotoId(null)
      },
        e("img", {
          src: zoomedPhoto.url, alt: "",
          style: { maxWidth: "100%", maxHeight: "68vh", borderRadius: 16, boxShadow: "0 20px 60px rgba(0,0,0,0.5)" },
          onClick: (ev) => ev.stopPropagation()
        }),
        e("div", { style: { marginTop: 14, display: "flex", flexDirection: "column", alignItems: "center", gap: 4 }, onClick: (ev) => ev.stopPropagation() },
          e("span", { style: { color: "#FFFFFF", fontFamily: "'Space Grotesk', sans-serif", fontWeight: 600, fontSize: 14 } }, fmtDateMed(zoomedPhoto.takenOn)),
          zoomedPhoto.note && e("span", { style: { color: "rgba(255,255,255,0.75)", fontSize: 13 } }, zoomedPhoto.note),
          canManage && e("button", {
            type: "button",
            style: { marginTop: 10, display: "flex", alignItems: "center", gap: 6, background: "rgba(255,255,255,0.1)", border: "1px solid rgba(255,255,255,0.25)", borderRadius: 20, padding: "6px 14px", color: "#FFFFFF", fontFamily: "'Inter', sans-serif", fontSize: 12, fontWeight: 600, cursor: "pointer" },
            onClick: () => { setConfirmDeletePhotoId(zoomedPhoto.id); setZoomedPhotoId(null); }
          }, e(Icon, { name: "trash", size: 13, color: "#FFFFFF" }), "Delete photo")
        ),
        e("button", {
          type: "button",
          style: { position: "fixed", top: "max(16px, env(safe-area-inset-top))", right: 16, background: "rgba(0,0,0,0.4)", border: "none", borderRadius: "50%", width: 34, height: 34, display: "flex", alignItems: "center", justifyContent: "center", cursor: "pointer" },
          onClick: () => setZoomedPhotoId(null), "aria-label": "Close photo"
        }, e(Icon, { name: "x", size: 18, color: "#FFFFFF" }))
      )
    );
  }

  // ---- body composition assessments ----

export { ProgressPanel };
