// @generated by tools/extract/extract.py — bodies copied verbatim from index.html
import { computeWeekStreak, computeWeekToDate } from "../../domain/group2.js";
import { fmtDateMed } from "../../shared/lib/format.js";
import { e } from "../../shared/react.js";
import { C, styles, withAlpha } from "../../shared/theme.js";
import { Icon } from "../../shared/ui/Icon.js";
import { useMemo } from "react";

  // Live status for the week that's actually happening right now — the
  // counterpart to WeeklyRecapCard below, which only ever reports on a week
  // once it's over. Without this, "Missed goal" on last week's card reads as
  // if it's judging today, when today's training hasn't even been counted
  // anywhere yet. Only renders once a days/week target is actually set.
  function ThisWeekCard({ entries, daysPerWeek }) {
    const week = useMemo(() => computeWeekToDate(entries, daysPerWeek), [entries, daysPerWeek]);
    // Reuses the exact same weeks-in-a-row streak SessionGoalCard already
    // shows further down — jimfit-flow_12.html restyle just surfaces it here
    // too, as a small badge next to "This week", matching the prototype's
    // streak-badge placement. No new calculation.
    const streak = useMemo(() => computeWeekStreak(entries, daysPerWeek), [entries, daysPerWeek]);
    if (!daysPerWeek) return null;
    const remaining = Math.max(0, week.daysPerWeek - week.sessions);
    const hit = week.sessions >= week.daysPerWeek;
    const stillPossible = hit || remaining <= week.daysLeft;
    let statusText, statusColor;
    if (hit) { statusText = "Goal already hit for this week."; statusColor = C.good; }
    else if (stillPossible) { statusText = `${remaining} more day${remaining === 1 ? "" : "s"} needed — ${week.daysLeft} day${week.daysLeft === 1 ? "" : "s"} left this week.`; statusColor = C.brand; }
    else { statusText = `Can't reach ${week.daysPerWeek} days this week — only ${week.daysLeft} day${week.daysLeft === 1 ? "" : "s"} left.`; statusColor = C.critical; }
    // jimfit-flow_12.html restyle — a ring showing sessions-vs-goal (same
    // week.sessions/week.daysPerWeek this card already had) sits beside the
    // day chips, matching the prototype's week-ring-row. Nothing removed —
    // the "X of Y so far" chip and the per-day strip both stay exactly as
    // they were, the ring is purely additive.
    const ringFrac = week.daysPerWeek ? Math.min(1, week.sessions / week.daysPerWeek) : 0;
    const ringR = 30, ringCx = 36, ringCy = 36, ringCirc = 2 * Math.PI * ringR;
    return e("div", { style: { ...styles.goalCard, marginBottom: 16 } },
      e("div", { style: { display: "flex", flexWrap: "wrap", justifyContent: "space-between", alignItems: "flex-start", gap: 8, marginBottom: 12 } },
        e("div", null,
          e("div", { style: styles.progressCardTitle }, "This week"),
          e("div", { style: { fontFamily: "'JetBrains Mono', monospace", fontSize: 10, color: C.ink3, marginTop: 3 } }, fmtDateMed(week.start), " – ", fmtDateMed(week.end))
        ),
        streak > 0 && e("span", { style: styles.streakBadge }, e(Icon, { name: "flame", size: 12, color: C.brand }), `${streak}wk streak`)
      ),
      e("div", { style: { display: "flex", alignItems: "center", gap: 14, marginBottom: 10 } },
        e("svg", { width: 72, height: 72, viewBox: "0 0 72 72", style: { flexShrink: 0 } },
          e("circle", { cx: ringCx, cy: ringCy, r: ringR, fill: "none", stroke: C.subtleFill, strokeWidth: 8 }),
          e("circle", {
            cx: ringCx, cy: ringCy, r: ringR, fill: "none", stroke: hit ? C.good : C.brand, strokeWidth: 8, strokeLinecap: "round",
            strokeDasharray: `${(ringFrac * ringCirc).toFixed(2)} ${ringCirc.toFixed(2)}`,
            transform: `rotate(-90 ${ringCx} ${ringCy})`, style: { transition: "stroke-dasharray 0.4s ease" }
          }),
          e("text", { x: ringCx, y: ringCy - 1, textAnchor: "middle", fontFamily: "'Space Grotesk', sans-serif", fontWeight: 700, fontSize: 15, fill: C.ink }, `${week.sessions}/${week.daysPerWeek}`),
          e("text", { x: ringCx, y: ringCy + 12, textAnchor: "middle", fontFamily: "'JetBrains Mono', monospace", fontSize: 6.5, fill: C.ink3 }, "SESSIONS")
        ),
        e("div", { style: { flex: 1, minWidth: 0 } },
          e("div", { style: { display: "flex", gap: 4, flexWrap: "wrap" } }, week.days.map((d) => e("div", {
            key: d.date,
            title: `${fmtDateMed(d.date)}${d.isFuture ? " — upcoming" : d.trained ? " — trained" : " — no session logged"}`,
            style: {
              width: 22, height: 22, borderRadius: 6, display: "flex", alignItems: "center", justifyContent: "center", boxSizing: "border-box",
              fontFamily: "'JetBrains Mono', monospace", fontSize: 10, fontWeight: 700,
              background: d.isFuture ? C.subtleFill : d.trained ? withAlpha(C.good, 0.18) : withAlpha(C.critical, 0.12),
              color: d.isFuture ? C.ink3 : d.trained ? C.good : C.critical,
              border: `1px solid ${d.isToday ? C.brand : d.isFuture ? C.cardBorder : d.trained ? withAlpha(C.good, 0.4) : withAlpha(C.critical, 0.3)}`
            }
          }, d.label)))
        )
      ),
      e("div", { style: { fontSize: 12.5, fontWeight: 600, color: statusColor } }, statusText)
    );
  }

export { ThisWeekCard };
