// @generated by tools/extract/extract.py — bodies copied verbatim from index.html
import { extractSpokenNumber } from "../../domain/group2.js";
import { e } from "../react.js";
import { C, styles, withAlpha } from "../theme.js";
import { VoiceMicButton } from "./VoiceMicButton.js";
import { useEffect, useState } from "react";

  function EditableStat({ label, value, suffix = "", type = "number", options, onCommit, block = false, placeholder = "Set", min, max, hideMic = false }) {
    const [editing, setEditing] = useState(false);
    const [draft, setDraft] = useState(value != null ? String(value) : "");
    const [rangeError, setRangeError] = useState(false);

    useEffect(() => { setDraft(value != null ? String(value) : ""); }, [value]);

    function commit() {
      if (type === "number") {
        if (draft === "") { setEditing(false); onCommit(null); return; }
        const n = Number(draft);
        if (Number.isNaN(n)) { setEditing(false); setDraft(value != null ? String(value) : ""); return; }
        // Reject anything outside a realistic range instead of silently
        // saving it — this is what let a stray extra digit turn into a
        // nonsense BMR before nobody could tell why (Sept 6 2026).
        if ((min != null && n < min) || (max != null && n > max)) {
          setRangeError(true);
          return; // stay in edit mode so they can see and fix the number
        }
        setRangeError(false);
        setEditing(false);
        onCommit(n);
      } else {
        setEditing(false);
        onCommit(draft.trim() || null);
      }
    }

    if (type === "select") {
      return e("div", null,
        e("span", { style: styles.profileLabel }, label),
        e("select", {
          value: value || "", onChange: (ev) => onCommit(ev.target.value), style: styles.compactSelect
        }, options.map((o) => e("option", { key: o, value: o }, o)))
      );
    }

    if (type === "date") {
      return e("div", block ? { style: { marginTop: 10 } } : null,
        e("span", { style: styles.profileLabel }, label),
        e("input", {
          type: "date", style: { ...styles.input, marginTop: block ? 4 : 2, padding: block ? "9px 10px" : "6px 8px", fontSize: block ? 14 : 13.5 },
          value: value || "", onChange: (ev) => onCommit(ev.target.value || null)
        })
      );
    }

    const hasValue = value != null && value !== "";
    const displayValue = hasValue ? `${value}${suffix}` : placeholder;

    return e("div", block ? { style: { marginTop: 10 } } : null,
      e("span", { style: styles.profileLabel }, label),
      editing
        ? e("div", null,
            e("div", { style: { display: "flex", gap: 6, alignItems: "center", marginTop: block ? 4 : 2 } },
              e("input", {
                type: type === "number" ? "number" : "text", autoFocus: true,
                style: { ...styles.input, flex: 1, marginTop: 0, padding: block ? "9px 10px" : "6px 8px", fontSize: block ? 14 : 13.5, ...(rangeError ? { borderColor: C.critical } : {}) },
                value: draft, onChange: (ev) => { setDraft(ev.target.value); setRangeError(false); }, onBlur: commit,
                onKeyDown: (ev) => { if (ev.key === "Enter") commit(); if (ev.key === "Escape") { setDraft(value != null ? String(value) : ""); setRangeError(false); setEditing(false); } }
              }),
              !hideMic && e(VoiceMicButton, {
                title: `Say the ${label.toLowerCase()}`,
                onTranscribed: (text) => setDraft(type === "number" ? extractSpokenNumber(text) : text)
              })
            ),
            rangeError && e("p", { style: { color: C.critical, fontSize: 11, margin: "3px 0 0" } }, `Enter a value between ${min}${suffix} and ${max}${suffix}.`)
          )
        // Sept 8 2026, Jimmy: match the always-boxed look of the "date"/
        // "select" fields above (Birthday, Gender) instead of plain
        // tap-to-edit text that only looks like an input once tapped — same
        // border/padding as the real input, just not focusable until tapped.
        // Sept 12 2026, Jimmy: "the name and everything to be more better to
        // the eye" — a light brand-blue tint on the tap-to-edit display
        // state (not the real <input> above, which keeps the normal
        // editing look) makes it read as a chip you tap rather than a
        // plain gray box.
        // Sept 14 2026: found doing a full trainer walkthrough — an empty
        // field showed its placeholder ("Set") in the exact same bold,
        // full-color text as a real value (e.g. Last Name read "Set" with
        // no visual difference from a name someone actually typed). Empty
        // state now renders muted/italic like a placeholder everywhere else
        // in the app, so it reads as "nothing entered yet", not as data.
        : e("div", {
            style: {
              ...styles.input, background: withAlpha(C.brand, 0.06), border: `1px solid ${withAlpha(C.brand, 0.22)}`,
              marginTop: block ? 4 : 2, padding: block ? "9px 10px" : "6px 8px", fontSize: block ? 14 : 13.5, cursor: "pointer",
              ...(hasValue ? { fontWeight: 600, color: C.ink } : { fontWeight: 500, fontStyle: "italic", color: C.ink3 })
            },
            onClick: () => { setRangeError(false); setEditing(true); }, title: "Tap to edit"
          }, displayValue)
    );
  }

export { EditableStat };
