// @generated by tools/extract/extract.py — bodies copied verbatim from index.html
import { saveManualExerciseGif, saveManualExerciseMuscles } from "../../data/group1.js";
import { fetchExerciseDemoVisual, fetchExerciseMuscles } from "../../data/queries.js";
import { exerciseDemoVisualMemCache, exerciseGifKey, exerciseMusclesMemCache } from "../../domain/group2.js";
import { youtubeEmbedUrl, youtubeSearchUrl } from "../../domain/group4.js";
import { MUSCLE_DISPLAY_ORDER, PRIMARY_MUSCLE_LABEL } from "../../domain/muscles.js";
import { e } from "../react.js";
import { C, styles } from "../theme.js";
import { Icon } from "../ui/Icon.js";
import { MuscleDiagram } from "../ui/cross.js";
import React, { useEffect, useState } from "react";

  // Sept 13 2026, Jimmy: "cant open it" (re: the small icon) — forwardRef +
  // an exposed open() lets ExerciseIcon (a separate sibling component) open
  // this same panel, not just its own "Show demo" button.
  const ExerciseDemo = React.forwardRef(function ExerciseDemo({ name }, ref) {
    const [open, setOpen] = useState(false);
    const [loading, setLoading] = useState(false);
    const [result, setResult] = useState(exerciseDemoVisualMemCache[exerciseGifKey(name)] || null);
    const [checked, setChecked] = useState(exerciseGifKey(name) in exerciseDemoVisualMemCache);
    const [showManual, setShowManual] = useState(false);
    const [manualUrl, setManualUrl] = useState("");
    const [muscles, setMuscles] = useState(exerciseMusclesMemCache[exerciseGifKey(name)] || null);
    const [musclesChecked, setMusclesChecked] = useState(exerciseGifKey(name) in exerciseMusclesMemCache);
    const [showMuscleForm, setShowMuscleForm] = useState(false);
    const [muscleFormPrimary, setMuscleFormPrimary] = useState("");
    const [muscleFormSecondary, setMuscleFormSecondary] = useState([]);

    async function handleSaveMuscleTags() {
      if (!muscleFormPrimary) return;
      await saveManualExerciseMuscles(name, muscleFormPrimary, muscleFormSecondary);
      setMuscles({ primary: muscleFormPrimary, secondary: muscleFormSecondary });
      setShowMuscleForm(false);
    }

    async function handleOpen() {
      const next = !open;
      setOpen(next);
      if (next && !checked) {
        setLoading(true);
        const r = await fetchExerciseDemoVisual(name);
        setResult(r);
        setChecked(true);
        setLoading(false);
      }
      // Independent of the demo-photo lookup above (and never blocked by its
      // loading state) — a manual gif-link override shouldn't hide the muscle
      // diagram, since that always comes straight from the catalog.
      if (next && !musclesChecked) {
        fetchExerciseMuscles(name).then((m) => { setMuscles(m); setMusclesChecked(true); });
      }
    }
    React.useImperativeHandle(ref, () => ({ open: handleOpen }));

    async function handleSaveManual() {
      if (!manualUrl.trim()) return;
      await saveManualExerciseGif(name, manualUrl.trim());
      setResult({ imageUrl: manualUrl.trim(), imageUrl2: null, isManual: true, matchedName: null });
      setShowManual(false);
      setManualUrl("");
    }

    const imgUrl = result && result.imageUrl;
    const imgUrl2 = result && result.imageUrl2;
    const isManual = result && result.isManual;
    const matchedName = result && result.matchedName;
    const looksOff = matchedName && exerciseGifKey(matchedName) !== exerciseGifKey(name);
    const ytEmbed = youtubeEmbedUrl(imgUrl);

    // Same "looks like it's moving" trick the old real-photo demo used —
    // flip between RepDB's paired start/peak illustration frames when both
    // are available for this exercise (most are; a few only have one pose).
    const [frameOn, setFrameOn] = useState(false);
    useEffect(() => {
      if (!open || ytEmbed || !imgUrl2) return;
      const id = setInterval(() => setFrameOn((v) => !v), 700);
      return () => clearInterval(id);
    }, [open, ytEmbed, imgUrl2]);
    const displaySrc = imgUrl2 && frameOn ? imgUrl2 : imgUrl;

    return e("div", { style: { marginTop: open ? 8 : 0 } },
      e("button", { style: styles.demoToggleBtn, onClick: handleOpen },
        e(Icon, { name: "play", size: 12 }), open ? "Hide demo" : "Show demo"),
      open && e("div", { style: styles.demoPanel },
        loading && e("span", { style: styles.demoNote }, "Looking up a demo…"),
        !loading && imgUrl && e("div", null,
          ytEmbed
            ? e("iframe", { src: ytEmbed, style: { ...styles.demoImg, height: 150, border: "none" }, allow: "autoplay; encrypted-media", allowFullScreen: true })
            : e("img", { src: displaySrc, alt: `${name} demo`, style: styles.demoImg }),
          // Same consistent RepDB style everywhere now — only call out a
          // "matched" name when it's an automatic match that might be wrong;
          // a trainer's own manually-added link needs no such caveat.
          !isManual && matchedName && e("span", { style: { ...styles.demoNote, display: "block", marginTop: 6 } },
            "Matched: “", matchedName, "”", looksOff ? " — does this look right?" : ""),
          !showManual && e("button", { style: styles.demoLinkBtn, onClick: () => setShowManual(true) },
            !isManual && looksOff ? "That's not right — add the correct link" : "Not right? Add your own link")
        ),
        !loading && !imgUrl && !showManual && e("div", null,
          e("span", { style: styles.demoNote }, "No demo found for “", name, "”."),
          e("div", { style: { display: "flex", gap: 14, marginTop: 4 } },
            e("a", { href: youtubeSearchUrl(name), target: "_blank", rel: "noopener noreferrer", style: { ...styles.demoLinkBtn, marginTop: 0 } }, "Search YouTube ↗"),
            e("button", { style: { ...styles.demoLinkBtn, marginTop: 0 }, onClick: () => setShowManual(true) }, "+ Add your own link")
          )
        ),
        !loading && showManual && e("div", { style: { display: "flex", gap: 8, marginTop: 6, flexWrap: "wrap" } },
          e("input", {
            style: { ...styles.input, flex: 1, minWidth: 160 }, placeholder: "Paste a YouTube link or direct GIF/image URL",
            value: manualUrl, onChange: (ev) => setManualUrl(ev.target.value)
          }),
          e("button", { style: styles.saveBtn, onClick: handleSaveManual }, "Save")
        ),
        muscles && e(MuscleDiagram, { primary: muscles.primary, secondary: muscles.secondary }),
        // Plenty of exercises aren't in the free dataset at all — same reason
        // they have no demo photo also means no muscle tags. Let whoever's
        // looking tag it once; after that, everyone who looks this exercise
        // up gets the diagram too, same as a manually-added demo link.
        !loading && musclesChecked && !muscles && !showMuscleForm && e("button", { style: styles.demoLinkBtn, onClick: () => setShowMuscleForm(true) }, "+ Tag which muscles this works"),
        showMuscleForm && e("div", { style: { marginTop: 8, display: "flex", flexDirection: "column", gap: 8 } },
          e("select", {
            style: styles.input, value: muscleFormPrimary,
            onChange: (ev) => { setMuscleFormPrimary(ev.target.value); setMuscleFormSecondary((prev) => prev.filter((k) => k !== ev.target.value)); }
          },
            e("option", { value: "" }, "Primary muscle…"),
            MUSCLE_DISPLAY_ORDER.map((k) => e("option", { key: k, value: k }, PRIMARY_MUSCLE_LABEL[k]))
          ),
          e("span", { style: styles.demoNote }, "Secondary (optional) — tap any that also work:"),
          e("div", { style: { display: "flex", flexWrap: "wrap", gap: 6 } },
            MUSCLE_DISPLAY_ORDER.filter((k) => k !== muscleFormPrimary).map((k) => e("button", {
              key: k, type: "button",
              style: {
                ...styles.demoToggleBtn, marginTop: 0,
                ...(muscleFormSecondary.includes(k) ? { background: C.brandSoft, color: C.brand, borderColor: C.brand } : {})
              },
              onClick: () => setMuscleFormSecondary((prev) => prev.includes(k) ? prev.filter((x) => x !== k) : [...prev, k])
            }, PRIMARY_MUSCLE_LABEL[k]))
          ),
          e("div", { style: { display: "flex", gap: 8 } },
            e("button", {
              style: { ...styles.saveBtn, marginTop: 0, flex: 1, ...(!muscleFormPrimary ? styles.btnDisabled : {}) },
              disabled: !muscleFormPrimary, onClick: handleSaveMuscleTags
            }, "Save"),
            e("button", { style: { ...styles.demoLinkBtn, padding: "0 10px" }, onClick: () => setShowMuscleForm(false) }, "Cancel")
          )
        )
      )
    );
  });

export { ExerciseDemo };
