// @generated by tools/extract/extract.py — bodies copied verbatim from index.html
import { fetchExerciseIcon } from "../../data/queries.js";
import { exerciseGifKey, exerciseIconMemCache } from "../../domain/group2.js";
import { e } from "../react.js";
import { C } from "../theme.js";
import { Icon } from "../ui/Icon.js";
import { useEffect, useState } from "react";

  // Small always-visible icon using the RepDB match above — falls back to a
  // plain dumbbell glyph (still themed/consistent) for exercises not in
  // RepDB's 601-exercise set, so every row still looks uniform.
  // Sept 13 2026, Jimmy: "i see it but cant open it" — tapping the icon
  // itself used to do nothing; onOpen (wired to the paired ExerciseDemo's
  // own open() below) lets tapping the icon open the same big view "Show
  // demo" opens, instead of only working from that separate button.
  function ExerciseIcon({ name, size = 40, onOpen }) {
    const [icon, setIcon] = useState(exerciseIconMemCache[exerciseGifKey(name)] || null);
    useEffect(() => {
      let cancelled = false;
      const key = exerciseGifKey(name);
      if (key in exerciseIconMemCache) { setIcon(exerciseIconMemCache[key]); return; }
      fetchExerciseIcon(name).then((r) => { if (!cancelled) setIcon(r); });
      return () => { cancelled = true; };
    }, [name]);
    const iconUrl = icon && icon.iconUrl;
    return e("div", {
      onClick: onOpen,
      role: onOpen ? "button" : undefined,
      "aria-label": onOpen ? `Show ${name} demo` : undefined,
      style: {
        width: size, height: size, borderRadius: "50%", flexShrink: 0, overflow: "hidden",
        background: C.subtleFill, border: `1px solid ${C.cardBorder}`,
        display: "flex", alignItems: "center", justifyContent: "center",
        cursor: onOpen ? "pointer" : "default"
      }
    },
      iconUrl
        ? e("img", { src: iconUrl, alt: "", style: { width: "100%", height: "100%", objectFit: "cover" } })
        : e(Icon, { name: "dumbbell", size: Math.round(size * 0.42), color: C.ink3 })
    );
  }

export { ExerciseIcon };
