// @generated by tools/extract/extract.py — bodies copied verbatim from index.html
import { TURNSTILE_ENABLED, TURNSTILE_SITE_KEY } from "../../platform/captcha.js";
import { e } from "../react.js";
import { C } from "../theme.js";
import React, { useEffect, useRef, useState } from "react";

  // Sept 16 2026, Jimmy: Attack Protection — renders Cloudflare's Turnstile
  // widget (see TURNSTILE_SITE_KEY above). No-ops entirely (renders nothing,
  // never calls onToken) when TURNSTILE_ENABLED is false, so it's safe to
  // mount unconditionally once TURNSTILE_ENABLED flips on. `onToken` fires
  // with a fresh token on success and with "" on expiry/error, so the form
  // can block submit until a real token is present — a token is single-use,
  // so the parent bumps `resetKey` after every submit attempt to force a
  // fresh widget for the next one.
  function TurnstileWidget({ onToken, resetKey, theme = "dark" }) {
    const containerRef = useRef(null);
    const widgetIdRef = useRef(null);
    // Sept 16 2026, Jimmy: an ad blocker or privacy extension blocking
    // challenges.cloudflare.com (not rare — some block it by default), or
    // just a bad connection, would otherwise leave the submit button
    // silently disabled forever with no explanation. 8s without
    // window.turnstile showing up flips this so the form can say what's
    // actually wrong instead of looking broken.
    const [loadFailed, setLoadFailed] = useState(false);

    useEffect(() => {
      if (!TURNSTILE_ENABLED) return;
      let cancelled = false;
      let pollId = null;
      let timeoutId = null;

      function renderWidget() {
        if (cancelled || !containerRef.current || !window.turnstile) return;
        setLoadFailed(false);
        if (widgetIdRef.current) {
          try { window.turnstile.remove(widgetIdRef.current); } catch (e) {}
        }
        containerRef.current.innerHTML = "";
        widgetIdRef.current = window.turnstile.render(containerRef.current, {
          sitekey: TURNSTILE_SITE_KEY,
          theme,
          callback: (token) => { if (!cancelled) onToken(token); },
          "expired-callback": () => { if (!cancelled) onToken(""); },
          "error-callback": () => { if (!cancelled) onToken(""); }
        });
      }

      if (window.turnstile) {
        renderWidget();
      } else {
        // api.js in <head> loads async/defer — poll briefly instead of
        // assuming it's already there by the time this mounts.
        pollId = setInterval(() => {
          if (window.turnstile) { clearInterval(pollId); renderWidget(); }
        }, 150);
        timeoutId = setTimeout(() => {
          if (!cancelled && !window.turnstile) setLoadFailed(true);
        }, 8000);
      }

      return () => {
        cancelled = true;
        if (pollId) clearInterval(pollId);
        if (timeoutId) clearTimeout(timeoutId);
        if (widgetIdRef.current) {
          try { window.turnstile.remove(widgetIdRef.current); } catch (e) {}
        }
      };
    }, [resetKey]);

    if (!TURNSTILE_ENABLED) return null;
    return e(React.Fragment, null,
      e("div", { ref: containerRef, style: { margin: "14px 0 4px", display: "flex", justifyContent: "center" } }),
      loadFailed && e("p", { style: { fontSize: 11.5, color: C.ink3, textAlign: "center", margin: "0 0 4px" } },
        "Verification didn't load — check your connection or disable any ad blocker for this page, then reload."
      )
    );
  }

export { TurnstileWidget };
