// @generated by tools/extract/extract.py — bodies copied verbatim from index.html
import { fetchLatestPaymentClaim, submitPaymentClaim } from "../../data/group1.js";
import { PAYMENT_CLAIM_FRESH_MS } from "../../domain/access.js";
import { e } from "../react.js";
import { C, styles } from "../theme.js";
import { WhishPayBox } from "../ui/group1.js";
import { useEffect, useState } from "react";

  // Real 3-step payment status: "Send payment" (with an "I've sent it"
  // button that records a real timestamp), "Under review" (the natural
  // resting state once sent but not yet confirmed), and "Approved" — which,
  // by definition, is never actually seen as done from in here, since the
  // whole locked screen this sits on disappears the moment a trainer/
  // manager confirms it. It stays visible as the pending next step, same as
  // the mockup, never marked complete on this screen.
  function PaymentStatusStepper({ email, context, amount, approvedCopy }) {
    const [claim, setClaim] = useState(null);
    const [loaded, setLoaded] = useState(false);
    const [submitting, setSubmitting] = useState(false);

    useEffect(() => {
      let cancelled = false;
      setLoaded(false);
      fetchLatestPaymentClaim(email, context).then((row) => {
        if (!cancelled) { setClaim(row); setLoaded(true); }
      });
      return () => { cancelled = true; };
    }, [email, context]);

    const isFresh = !!claim && (Date.now() - new Date(claim.submitted_at).getTime()) < PAYMENT_CLAIM_FRESH_MS;

    async function handleSubmit() {
      setSubmitting(true);
      const row = await submitPaymentClaim(email, context);
      setSubmitting(false);
      if (row) setClaim(row);
    }

    // Sept 13 2026, Jimmy: "when i unlock and buy its something else" — swap
    // the old 3-item vertical stepper list for jimfit-flow_15.html's compact
    // readout: title, pay box, one full-width action button that turns into
    // a disabled "Marked as sent" confirmation, then a small 3-dot progress
    // row with a single line of status copy underneath. Same underlying
    // data (isFresh/claim/handleSubmit) — only the layout changed.
    return e("div", { style: { width: "100%", marginTop: 4 } },
      e("div", { style: styles.stepperTitle }, "Send payment via Whish"),
      e(WhishPayBox, { amount }),
      e("button", {
        style: { ...styles.saveBtn, marginTop: 10, width: "100%", ...((isFresh || submitting || !loaded) ? styles.btnDisabled : {}) },
        disabled: isFresh || submitting || !loaded,
        onClick: handleSubmit
      }, submitting ? "Marking as sent…" : isFresh ? "Marked as sent ✓" : "I've sent the payment"),
      e("div", { style: styles.stepperDotsRow },
        e("span", { style: { ...styles.stepperDotSmall, ...styles.stepperDotSmallLit } }),
        e("span", { style: { ...styles.stepperDotSmall, ...(isFresh ? styles.stepperDotSmallLit : {}) } }),
        e("span", { style: styles.stepperDotSmall })
      ),
      // Sept 13 2026, Jimmy: "marked it as yellow here also" — same amber
      // "pending" treatment as the trainer-request banner (C.warning),
      // applied to the "sent, waiting on us to confirm" line specifically —
      // the "send the payment" instructions below it (isFresh false) aren't
      // a pending state, so those stay the plain neutral color.
      e("p", { style: { ...styles.stepperHintLine, ...(isFresh ? { color: C.warning } : {}) } },
        isFresh
          ? `Sent ${fmtDateTimeMed(claim.submitted_at)} — usually confirmed within a day.`
          : "Send the payment above, then mark it as sent."
      ),
      isFresh && e("p", { style: { ...styles.stepperHintLine, marginTop: 4, color: C.ink3, fontSize: 11 } }, approvedCopy || "We'll notify you the moment it's approved.")
    );
  }

export { PaymentStatusStepper };
