// @generated by tools/extract/extract.py — bodies copied verbatim from index.html
import { clientRiskLabel } from "../../domain/group1.js";
import { isBirthdayToday } from "../../domain/group3.js";
import { fmtDate } from "../../shared/lib/format.js";
import { e } from "../../shared/react.js";
import { C, styles } from "../../shared/theme.js";
import { Icon } from "../../shared/ui/Icon.js";
import { PeopleEmptyArt } from "../../shared/ui/empty-art.js";
import { BirthdayBadge } from "../../shared/ui/group1.js";
import React, { useState } from "react";

  // Rows come from the id-first `roster` builder below — each row already
  // carries its own profile fields (clientEmail/birthday/trainerId) directly,
  // so this list never needs to look anything up by display name. That's the
  // fix: two clients who happen to share a name used to collide the moment
  // any lookup here went through a name-keyed map (profileByName[r.name]) —
  // whichever one was last in the map "won" for both cards. Selecting,
  // clearing, and deleting are all now keyed by r.id too.
  function ClientRosterList({ roster, balanceFor, onSelect, onDelete, onClearWorkouts, emptyText, trainerNameFor, categoriesFor, renewalFor }) {
    // Sept 14 2026, Jimmy: "i want for every tab in it a search button i
    // dont want to scroll all the way down" — this roster is used by both
    // the Clients and My clients sections of the Owner/manager menu, both
    // of which can run long. Same search-by-name-or-email pattern
    // TrainerView's own client roster already uses (added Sept 13 2026),
    // just self-contained here since this component is shared across two
    // different call sites that each own their own `roster` prop.
    const [search, setSearch] = useState("");
    // Sept 18 2026, Jimmy: "i want the client to see... their account is
    // freezed until they paid" prompted the matching manager-side ask —
    // seeing WHO needs to pay meant scrolling the whole roster looking for
    // a red "Trial ended"/"Lapsed" badge. This toggle filters straight down
    // to just those.
    //
    // Sept 18 2026 retest fix: this originally only checked renewalFor
    // (self-train trial/subscription lapse), which is null for anyone
    // billed outside the app — fine on the pure "My clients" (trainer-only)
    // list, but this same component also backs the mixed "Paid —
    // Subscription/Diet/Program" screens where self-train and
    // trainer-billed clients sit side by side. On those, the filter was
    // silently excluding trainer-billed clients who owe real money, even
    // though their own card shows a "$X due" badge right there
    // (balanceFor, used below at the card level). Now matches either
    // condition — a self-train lapse, OR a real positive balance — same
    // `balanceFor(r.profile) != null && > 0` check TrainerView's own
    // roster already uses correctly for this exact purpose.
    const ownesMoney = (r) => {
      const rn = renewalFor ? renewalFor(r.profile) : null;
      if (rn && rn.ok === false) return true;
      const b = balanceFor ? balanceFor(r.profile) : null;
      return b != null && b > 0;
    };
    const [needsPaymentOnly, setNeedsPaymentOnly] = useState(false);
    const needsPaymentCount = React.useMemo(() => roster.filter(ownesMoney).length, [roster, renewalFor, balanceFor]);
    const visibleRoster = React.useMemo(() => {
      const q = search.trim().toLowerCase();
      let list = roster;
      if (q) list = list.filter((r) => (r.name || "").toLowerCase().includes(q) || (r.clientEmail || "").toLowerCase().includes(q));
      if (needsPaymentOnly) list = list.filter(ownesMoney);
      return list;
    }, [roster, search, needsPaymentOnly, renewalFor, balanceFor]);
    return e(React.Fragment, null,
      roster.length === 0 && e("div", { style: styles.empty }, e(PeopleEmptyArt, {}), e("p", { style: styles.emptyText }, emptyText)),
      roster.length > 0 && e("div", { style: { display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: 12, flexWrap: "wrap", gap: 8 } },
        e("div", { style: styles.rosterSearchWrap },
          e(Icon, { name: "search", size: 14, color: C.ink3 }),
          e("input", {
            style: styles.rosterSearchInput, type: "text", value: search,
            onChange: (ev) => setSearch(ev.target.value),
            placeholder: "Search by name or email…"
          }),
          search && e("button", {
            type: "button", onClick: () => setSearch(""), style: styles.rosterSearchClear, "aria-label": "Clear search"
          }, e(Icon, { name: "x", size: 12, color: C.ink3 }))
        ),
        e("div", { style: { display: "flex", alignItems: "center", gap: 8 } },
          needsPaymentCount > 0 && e("button", {
            type: "button",
            onClick: () => setNeedsPaymentOnly((v) => !v),
            style: needsPaymentOnly
              ? { ...styles.goalChip, ...styles.goalChipBad, cursor: "pointer", border: "none" }
              : { ...styles.goalChip, background: C.subtleFill, color: C.ink2, border: `1px solid ${C.cardBorder}`, cursor: "pointer" }
          }, e(Icon, { name: "alert", size: 10 }), ` Needs payment (${needsPaymentCount})`),
          e("span", { style: styles.rosterCount }, visibleRoster.length, "/", roster.length)
        )
      ),
      roster.length > 0 && visibleRoster.length === 0 && e("div", { style: styles.empty },
        e("p", { style: styles.emptyText }, needsPaymentOnly ? "No clients currently need to pay." : `No clients match "${search.trim()}".`)
      ),
      // Sept 11 2026, Jimmy: brand pass, step 6 (phase 3 — decluttering the
      // busiest screens) — a card here can stack up to 5 lines (name, email,
      // sessions, per-type paid breakdown, renewal/birthday/risk badges) with
      // only 3px between each, which is what made this list feel cramped.
      // Bumping the internal line gap and the space between cards gives each
      // piece of info room to be read on its own instead of running together
      // — no content removed or hidden, just more breathing room.
      e("div", { style: { display: "flex", flexDirection: "column", gap: 12 } }, visibleRoster.map((r) => {
        const risk = clientRiskLabel(r.lastDate);
        const bday = isBirthdayToday(r.birthday);
        // Per-type paid totals and (for self-train clients) the subscription
        // renewal date, both right on the card — added so a manager scanning
        // this whole list doesn't have to open every client just to see what
        // they've paid for and when they're due again.
        const cats = categoriesFor ? categoriesFor(r.profile) : null;
        const hasCats = cats && (cats.subscription > 0 || cats.diet > 0 || cats.programs > 0 || cats.other > 0);
        const renewal = renewalFor ? renewalFor(r.profile) : null;
        return e("div", { key: r.id, style: styles.clientCard, onClick: () => onSelect(r.id), role: "button", tabIndex: 0, onKeyDown: (ev) => { if (ev.key === "Enter" || ev.key === " ") { ev.preventDefault(); onSelect(r.id); } } },
        e("div", { style: styles.clientCardLeft },
          e("div", { style: styles.avatar }, r.name.slice(0, 1).toUpperCase()),
          e("div", { style: { display: "flex", flexDirection: "column", gap: 5 } },
            e("span", { style: styles.exerciseName }, r.name),
            r.clientEmail && e("span", { style: { ...styles.muscleSubText, opacity: 0.75 } }, r.clientEmail),
            e("span", { style: styles.muscleSubText },
              r.sessions, " session", r.sessions === 1 ? "" : "s", " · last ", r.lastDate ? fmtDate(r.lastDate) : "—",
              trainerNameFor && ` · trains with ${trainerNameFor(r.trainerId)}`
            ),
            hasCats && e("span", { style: { ...styles.muscleSubText, opacity: 0.85 } },
              [
                cats.subscription > 0 ? `Sub $${cats.subscription.toLocaleString()}` : null,
                cats.diet > 0 ? `Diet $${cats.diet.toLocaleString()}` : null,
                cats.programs > 0 ? `Program $${cats.programs.toLocaleString()}` : null,
                cats.other > 0 ? `Other $${cats.other.toLocaleString()}` : null
              ].filter(Boolean).join(" · ")
            ),
            renewal && e("span", { style: { ...styles.goalChip, ...(renewal.ok ? styles.goalChipGood : styles.goalChipBad), alignSelf: "flex-start", marginTop: 2 } }, renewal.label),
            bday && e(BirthdayBadge, { style: { marginTop: 2 } }),
            risk && e("span", { style: { ...styles.goalChip, ...styles.goalChipBad, alignSelf: "flex-start", marginTop: 2 } }, e(Icon, { name: "alert", size: 10 }), " ", risk)
          )
        ),
        e("div", { style: { display: "flex", alignItems: "center", gap: 10 } },
          (() => {
            const balance = balanceFor(r.profile);
            if (balance == null) return null;
            const paidUp = balance <= 0;
            return e("span", { style: { ...styles.goalChip, ...(paidUp ? styles.goalChipGood : styles.goalChipBad) } }, paidUp ? "Paid up" : `$${balance.toLocaleString()} due`);
          })(),
          e("span", { style: styles.rosterVol }, r.vol7.toLocaleString(), e("span", { style: styles.statUnit }, " vol/7d")),
          onClearWorkouts && e("button", {
            style: { ...styles.deleteBtn, color: C.ink3 },
            onClick: (ev) => { ev.stopPropagation(); onClearWorkouts(r.id); },
            "aria-label": "Clear workout history", title: "Clear workout history"
          }, e(Icon, { name: "activity", size: 15 })),
          onDelete && e("button", { style: styles.deleteBtn, onClick: (ev) => { ev.stopPropagation(); onDelete(r.id); }, "aria-label": "Delete client", title: "Delete client entirely" }, e(Icon, { name: "trash", size: 15 }))
        )
        );
      }))
    );
  }

export { ClientRosterList };
