// @generated by tools/extract/extract.py — bodies copied verbatim from index.html
import { INJURY_BODY_PARTS, INJURY_SEVERITIES } from "../../domain/body.js";
import { sb } from "../../platform/supabase.js";
import { e } from "../../shared/react.js";
import { C, styles, withAlpha } from "../../shared/theme.js";
import { Icon } from "../../shared/ui/Icon.js";
import { Select } from "../../shared/ui/group1.js";
import { VoiceMicButton } from "../../shared/widgets/VoiceMicButton.js";
import { injurySeverityColor } from "./group1.js";
import { useEffect, useState } from "react";

  function ClientInjuriesPanel({ userId, clientName, canManage = false, legacyProfile = null, onUpdateLegacy = null }) {
    const [rows, setRows] = useState([]);
    const [loaded, setLoaded] = useState(false);
    const [adding, setAdding] = useState(false);
    const [bodyPart, setBodyPart] = useState(INJURY_BODY_PARTS[0]);
    const [customPart, setCustomPart] = useState("");
    const [severity, setSeverity] = useState("Mild");
    const [note, setNote] = useState("");
    const [saving, setSaving] = useState(false);
    const [error, setError] = useState("");
    const [confirmDeleteId, setConfirmDeleteId] = useState(null);

    useEffect(() => {
      if (!userId || !sb) { setRows([]); setLoaded(true); return; }
      setLoaded(false);
      sb.from("client_injuries").select("*").eq("user_id", userId).order("created_at", { ascending: true }).then(({ data, error: err }) => {
        setRows(!err && data ? data : []);
        setLoaded(true);
      });
    }, [userId]);

    async function handleSave() {
      setError("");
      const part = bodyPart === "Other" ? customPart.trim() : bodyPart;
      if (!part) { setError("Pick or type a body part / area."); return; }
      if (!sb || !userId) { setError("Backend not configured yet."); return; }
      setSaving(true);
      const payload = { user_id: userId, client_name: clientName, body_part: part, severity, note: note.trim() || null };
      const { data, error: err } = await sb.from("client_injuries").insert([payload]).select();
      setSaving(false);
      if (err || !data) {
        setError(`Couldn't save that${err && err.message ? ` (${err.message})` : ""}. Try again.`);
        return;
      }
      setRows((prev) => [...prev, data[0]]);
      setBodyPart(INJURY_BODY_PARTS[0]); setCustomPart(""); setSeverity("Mild"); setNote(""); setAdding(false);
    }

    async function handleDelete(id) {
      setConfirmDeleteId(null);
      const idx = rows.findIndex((r) => r.id === id);
      const target = idx !== -1 ? rows[idx] : null;
      setRows((prev) => prev.filter((r) => r.id !== id));
      if (!sb) return;
      const { error: err } = await sb.from("client_injuries").delete().eq("id", id);
      if (err) {
        // Delete failed server-side — put the row back rather than leaving
        // the screen showing a delete that didn't actually happen.
        if (target) setRows((prev) => { const next = [...prev]; next.splice(Math.min(idx, next.length), 0, target); return next; });
        setError(`Couldn't delete that${err.message ? ` (${err.message})` : ""}. Try again.`);
      }
    }

    const hasLegacy = !!(legacyProfile && legacyProfile.has_medical_condition && legacyProfile.medical_details);

    function convertLegacy() {
      setAdding(true);
      setBodyPart("Other"); setCustomPart(""); setSeverity("Moderate");
      setNote(legacyProfile.medical_details || "");
    }
    function dismissLegacy() {
      if (onUpdateLegacy) { onUpdateLegacy("medical_details", null); onUpdateLegacy("has_medical_condition", false); }
    }

    if (!loaded) return e("div", { style: { marginTop: 10 } }, e("p", { style: styles.profileGoalText }, "Loading…"));

    return e("div", { style: { marginTop: 10 } },
      e("div", { style: { display: "flex", alignItems: "center", justifyContent: "space-between" } },
        e("span", { style: styles.profileLabel }, "Injuries / limitations"),
        canManage && !adding && e("button", {
          type: "button",
          style: { display: "flex", alignItems: "center", gap: 4, background: "none", border: "none", padding: 0, cursor: "pointer", color: C.brand, fontSize: 11.5, fontWeight: 700, fontFamily: "'JetBrains Mono', monospace" },
          onClick: () => setAdding(true)
        }, e(Icon, { name: "plus", size: 12, strokeWidth: 2.6 }), "ADD")
      ),

      hasLegacy && e("div", { style: { display: "flex", alignItems: "flex-start", gap: 7, marginTop: 8, padding: "8px 10px", borderRadius: 8, background: C.subtleFill, border: `1px solid ${C.cardBorder}` } },
        e(Icon, { name: "alert", size: 13, color: C.ink3 }),
        e("div", { style: { flex: 1, minWidth: 0 } },
          e("p", { style: { margin: 0, fontSize: 11.5, color: C.ink3, lineHeight: 1.4 } }, "From the signup questionnaire: “", legacyProfile.medical_details, "”"),
          canManage && e("div", { style: { display: "flex", gap: 12, marginTop: 5 } },
            e("button", { type: "button", style: { background: "none", border: "none", padding: 0, cursor: "pointer", color: C.brand, fontSize: 11, fontWeight: 700 }, onClick: convertLegacy }, "Add as tracked entry"),
            e("button", { type: "button", style: { background: "none", border: "none", padding: 0, cursor: "pointer", color: C.ink3, fontSize: 11, fontWeight: 700 }, onClick: dismissLegacy }, "Dismiss")
          )
        )
      ),

      adding && e("div", { style: { marginTop: 8, padding: "10px 11px", borderRadius: 10, background: C.subtleFill, border: `1px solid ${C.cardBorder}` } },
        e("div", { style: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 8 } },
          e("div", null,
            e("span", { style: styles.profileLabel }, "Body part / area"),
            e(Select, { value: bodyPart, onChange: setBodyPart, options: INJURY_BODY_PARTS, style: { marginTop: 3 } })
          ),
          e("div", null,
            e("span", { style: styles.profileLabel }, "Severity"),
            e(Select, { value: severity, onChange: setSeverity, options: INJURY_SEVERITIES.map((s) => s.value), style: { marginTop: 3 } })
          )
        ),
        bodyPart === "Other" && e("input", { style: { ...styles.input, marginTop: 8 }, placeholder: "Type the body part / area", value: customPart, onChange: (ev) => setCustomPart(ev.target.value) }),
        e("div", { style: { display: "flex", gap: 6, alignItems: "center", marginTop: 8 } },
          e("input", { style: { ...styles.input, flex: 1 }, placeholder: "Note (optional) — e.g. avoid overhead pressing", value: note, onChange: (ev) => setNote(ev.target.value) }),
          e(VoiceMicButton, { title: "Say the note", onTranscribed: (text) => setNote((prev) => (prev ? `${prev} ${text}` : text)) })
        ),
        error && e("p", { style: { color: C.critical, fontSize: 11, margin: "6px 0 0" } }, error),
        e("div", { style: { display: "flex", gap: 8, marginTop: 9 } },
          e("button", { type: "button", style: { ...styles.saveBtn, marginTop: 0, flex: 1, ...(saving ? styles.btnDisabled : {}) }, disabled: saving, onClick: handleSave }, e(Icon, { name: "check", size: 14 }), saving ? "Saving…" : "Save"),
          e("button", { type: "button", style: styles.setConfirmCancelBtn, onClick: () => { setAdding(false); setError(""); } }, "Cancel")
        )
      ),

      rows.length === 0 && !adding && !hasLegacy && e("p", { style: { ...styles.profileGoalText, fontStyle: "italic", color: C.ink3, marginTop: 6 } }, canManage ? "None on file. Tap ADD to log one — e.g. old knee injury, avoid overhead pressing." : "None on file."),

      rows.length > 0 && e("div", { style: { display: "flex", flexDirection: "column", gap: 6, marginTop: 8 } },
        rows.map((r) => {
          const sevColor = injurySeverityColor(r.severity);
          return e("div", { key: r.id, style: { display: "flex", alignItems: "flex-start", gap: 8, padding: "8px 10px", borderRadius: 10, background: withAlpha(sevColor, 0.1), border: `1px solid ${withAlpha(sevColor, 0.3)}` } },
            e(Icon, { name: "alert", size: 13, color: sevColor, strokeWidth: 2.2 }),
            e("div", { style: { flex: 1, minWidth: 0 } },
              e("div", { style: { display: "flex", alignItems: "center", gap: 6, flexWrap: "wrap" } },
                e("span", { style: { fontFamily: "'Space Grotesk', sans-serif", fontWeight: 700, fontSize: 12.5, color: C.ink } }, r.body_part),
                e("span", { style: { fontFamily: "'JetBrains Mono', monospace", fontSize: 9.5, fontWeight: 700, letterSpacing: "0.04em", textTransform: "uppercase", color: sevColor, background: withAlpha(sevColor, 0.16), padding: "2px 6px", borderRadius: 20 } }, r.severity)
              ),
              r.note && e("p", { style: { margin: "3px 0 0", fontSize: 12, color: C.ink2, lineHeight: 1.4 } }, r.note)
            ),
            canManage && (confirmDeleteId === r.id
              ? e("div", { style: { display: "flex", gap: 4, flexShrink: 0 } },
                  e("button", { type: "button", style: styles.setConfirmCancelBtn, onClick: () => setConfirmDeleteId(null) }, "Cancel"),
                  e("button", { type: "button", style: styles.setConfirmDangerBtn, onClick: () => handleDelete(r.id) }, "Delete")
                )
              : e("button", { style: { ...styles.deleteBtn, flexShrink: 0 }, onClick: () => setConfirmDeleteId(r.id), "aria-label": "Delete injury entry" }, e(Icon, { name: "trash", size: 12 }))
            )
          );
        })
      )
    );
  }

export { ClientInjuriesPanel };
