// @generated by tools/extract/extract.py — bodies copied verbatim from index.html
import { notifyClient, notifyTrainer } from "../../data/group1.js";
import { PROGRAM_PRICE, SELF_TRAIN_MONTHLY_PRICE } from "../../domain/access.js";
import { styleLabel } from "../../domain/group4.js";
import { sb } from "../../platform/supabase.js";
import { ProgramWatermark } from "../../shared/brand.js";
import { e } from "../../shared/react.js";
import { C, styles } from "../../shared/theme.js";
import { Icon } from "../../shared/ui/Icon.js";
import { ProgramsEmptyArt } from "../../shared/ui/empty-art.js";
import { Select, WhishPayBox } from "../../shared/ui/group1.js";
import { LogProgramWeightModal } from "../../shared/widgets/LogProgramWeightModal.js";
import { PaymentStatusStepper } from "../../shared/widgets/PaymentStatusStepper.js";
import { ProgramExerciseRow } from "../../shared/widgets/ProgramExerciseRow.js";
import React, { useEffect, useRef, useState } from "react";
import { withAlpha } from "../../shared/theme.js";

  // Shows (and, for a trainer/manager, lets you set) the ONE program a specific client is
  // actually following right now — distinct from the full template library in ProgramsPanel,
  // which every trainer can browse and build from. Assigning here is what turns a shared
  // template into "this is Sarah's program."
  // Sept 10 2026, Jimmy: a self-train client's own "request a program" affordance
  // (the Assign button + picker below) only ever lived up in "Your program," well
  // above the fold once someone's scrolled down into "Browse all programs" — each
  // locked card down there just said "pick it above" as plain, non-clickable text.
  // forwardRef + quickPick exposes a way for ProgramsPanel's own browse cards to
  // trigger a pick directly (see the "Request this program" button below), reusing
  // this exact same tested assign logic instead of duplicating it.
  const ClientProgramCard = React.forwardRef(function ClientProgramCard({ clientName, clientId, userId = null, userEmail = null, canAssign = false, isSelfTrain = false, gatePayment = false, appAccessOk = true, paidAccessOk = true, trainerId = null, onAssignmentChange = null }, ref) {
    const [loaded, setLoaded] = useState(false);
    const [assignment, setAssignment] = useState(null);
    const [program, setProgram] = useState(null);
    const [exercises, setExercises] = useState([]);
    const [allPrograms, setAllPrograms] = useState([]);
    const [picking, setPicking] = useState(false);
    const [pickedId, setPickedId] = useState("");
    const [saving, setSaving] = useState(false);
    const [error, setError] = useState("");
    // Sept 13 2026, Jimmy: inline "are you sure" instead of window.confirm().
    const [confirmUnassign, setConfirmUnassign] = useState(false);
    // Sept 11 2026: "View full program" on the restyled hero card scrolls
    // down to the existing day-by-day exercise list instead of duplicating it.
    const programDetailRef = useRef(null);
    // Sept 14 2026, Jimmy: which exercise's "Log weight" button was tapped
    // (holds both the exercise row and its day label, for LogProgramWeightModal's
    // context line) — works the same whether this program was bought
    // (self-train, no trainer) or assigned by a trainer, since it's just
    // logging into the client's own workout log either way.
    const [logTarget, setLogTarget] = useState(null);
    // Sept 15 2026, Jimmy: "i want the client to be able to tap on every
    // week like the program the trainer assign so he's doesnt have to
    // scroll all the way down" — same week-chip filter
    // ClientCustomProgramCard already has for a trainer-written program;
    // this card (the shared-catalog "Your program") never had it, so a
    // long multi-week program was one long scroll with no way to jump
    // straight to, say, Week 8. "all" shows every week same as before.
    const [activeWeek, setActiveWeek] = useState("all");
    // Sept 19 2026, walkthrough finding: same one-tap nudge DietPanel
    // already has for a client stuck waiting on their trainer — this card's
    // own "ask your trainer" empty state (below) had no equivalent.
    const [nudgeSent, setNudgeSent] = useState(false);
    function handleNudgeTrainer() {
      if (!trainerId) return;
      notifyTrainer(trainerId, `${clientName || "Your client"} is waiting on a program to be assigned.`);
      setNudgeSent(true);
    }

    useEffect(() => { loadAssignment(); }, [clientName, clientId]);

    // Guards against a dangling week filter (e.g. the program gets
    // reassigned/changed and the previously-selected week label no longer
    // exists), which would otherwise silently show nothing.
    useEffect(() => {
      if (activeWeek !== "all" && !weekGroups().some((w) => w.label === activeWeek)) setActiveWeek("all");
    }, [exercises]);

    async function loadAssignment() {
      // Sept 10 2026: this used to also require clientName truthy — but the
      // actual lookup below keys entirely on clientId, and clientName can be
      // legitimately blank/still-loading for a real client. Requiring it too
      // was silently hiding this whole "request a program" card for anyone
      // it happened to be blank for, with no error and no obvious cause.
      if (!sb || !clientId) { setLoaded(true); return; }
      setLoaded(false);
      const { data: rows } = await sb.from("client_program_assignments").select("*").eq("client_id", clientId).order("assigned_at", { ascending: false }).limit(1);
      const a = rows && rows[0];
      setAssignment(a || null);
      if (onAssignmentChange) onAssignmentChange(a || null);
      if (a) {
        const { data: prog } = await sb.from("training_programs").select("*").eq("id", a.program_id).maybeSingle();
        setProgram(prog || null);
        if (prog) {
          const { data: exRows } = await sb.from("program_exercises").select("*").eq("program_id", prog.id).order("order_index", { ascending: true });
          setExercises(exRows || []);
        } else {
          setExercises([]);
        }
      } else {
        setProgram(null);
        setExercises([]);
      }
      setLoaded(true);
    }

    async function openPicker() {
      // Belt-and-suspenders — the button that calls this is hidden while
      // purchaseLocked, but guard here too in case anything else ever calls it.
      if (purchaseLocked) return;
      setPicking(true);
      setError("");
      setPickedId("");
      if (sb) {
        const { data } = await sb.from("training_programs").select("id, name, style").order("style", { ascending: true }).order("order_index", { ascending: true });
        const list = data || [];
        setAllPrograms(list);
        // A native <select> with no matching option for value="" still visually
        // shows the first option in the list — but our state stays empty until
        // the user actually changes it, so clicking Assign without touching the
        // dropdown looked like it did nothing. Default the picked id to whatever
        // is actually shown so Assign works immediately.
        if (list.length > 0) setPickedId(list[0].id);
      }
    }

    // Sept 10 2026: accepts an explicit programId so a "Request this program"
    // button elsewhere (ProgramsPanel's own browse cards, via the quickPick
    // ref below) can trigger the exact same assign flow directly on one
    // specific card, instead of only ever working through the picker
    // dropdown's own pickedId state. The picker's Assign button still calls
    // this with no argument, which falls back to pickedId exactly as before.
    // Returns true/false so a caller (ProgramsPanel's browse-list "Choose
    // this program" button, via quickPick below) can tell whether a pick
    // actually went through, instead of assuming it always did.
    async function handleAssign(explicitId) {
      const id = explicitId || pickedId;
      if (!id) { setError("Pick a program."); return false; }
      // Sept 18 2026, Jimmy retest: the picker's own "Assign" button and
      // openPicker() both already check purchaseLocked before letting
      // anyone get this far, but the browse-list "Choose this program"
      // button (ProgramsPanel -> handleRequestProgram -> quickPick) called
      // straight into this function with no check at all — a self-train
      // client whose trial AND payment had both lapsed could still request
      // a brand-new program. Same belt-and-suspenders guard as openPicker.
      //
      // Sept 18 2026 retest round 2: this can also be hit by a client still
      // inside their free trial who just hasn't paid the app-access fee
      // yet (purchaseLocked is about payment, not trial expiry) — "lapsed"
      // wrongly implied something that used to work had broken.
      if (purchaseLocked) { setError("Pay to unlock picking a program."); return false; }
      if (!sb) { setError("Backend not configured yet."); return false; }
      setSaving(true);
      setError("");
      if (assignment) await sb.from("client_program_assignments").delete().eq("id", assignment.id);
      const payload = { client_name: clientName, client_id: clientId, program_id: id };
      // Self-train clients only need to pay once per program — if
      // client_payments already has a row for this exact client + program_id
      // (even from an assignment that's since been deleted, e.g. they
      // removed it and are picking it back), this pick comes back already
      // unlocked instead of re-gating something they've genuinely already
      // paid for. Checked by isSelfTrain (a real client property), not
      // gatePayment (which is only true in the client's own view — the
      // manager's assign screen always passes gatePayment=false but still
      // needs this same check when reassigning a self-train client's
      // program). Trainer-owned clients are untouched — paid never gates
      // them either way.
      //
      // Matched by userId (client_payments.user_id, the same real key every
      // payment row is written against everywhere else in this file) —
      // NOT client_name. Two different clients can share the same display
      // name, and matching on the name alone would either wrongly grant one
      // of them free access off the other's payment, or wrongly block a
      // legitimate re-charge after a client renames themselves. If userId
      // isn't available for some reason, this safely skips the check rather
      // than querying on a name — worst case a client is asked to pay again,
      // never wrongly granted free access.
      if (isSelfTrain && userId) {
        const { data: priorPayment } = await sb.from("client_payments").select("id").eq("user_id", userId).eq("program_id", id).limit(1).maybeSingle();
        if (priorPayment) payload.paid = true;
      }
      const { error: err } = await sb.from("client_program_assignments").insert([payload]);
      setSaving(false);
      if (err) { setError("Couldn't assign that program. Try again."); return false; }
      // Notify the client only once this pick is actually usable — a
      // trainer-attached client is never payment-gated, so an assignment IS
      // the unlock; a self-train client only counts as unlocked here if they
      // already had a prior payment for this exact program (payload.paid,
      // set above). If they haven't paid, ProgramRequestRow.handleUnlock is
      // the thing that notifies them once that payment is marked received —
      // notifying here too would tell them it's "ready" before it actually is.
      if (userId && (!isSelfTrain || payload.paid)) {
        const pickedProgram = allPrograms.find((p) => p.id === id);
        notifyClient(userId, `Your program${pickedProgram ? ` "${pickedProgram.name}"` : ""} is ready — check your Programs tab.`);
      }
      setPicking(false);
      setPickedId("");
      // Awaited (not fire-and-forget) so a caller using quickPick via ref —
      // ProgramsPanel's "Request this program" button — can rely on this
      // resolving only once assignment state (and onAssignmentChange) is
      // actually up to date, not just once the insert itself finished.
      await loadAssignment();
      if (onAssignmentChange) onAssignmentChange();
      return true;
    }

    async function handleUnassign() {
      if (!assignment || !sb) return;
      setConfirmUnassign(false);
      setSaving(true);
      await sb.from("client_program_assignments").delete().eq("id", assignment.id);
      setSaving(false);
      loadAssignment();
      if (onAssignmentChange) onAssignmentChange();
    }

    // Sept 15 2026: groups by week_label first, then day_label within it —
    // a plain dayGroups() (day_label only) used to silently MERGE two
    // different weeks' exercises together whenever they reused the same day
    // label (e.g. every week's "Day 1 — Squat"), which is exactly what a
    // duplicated week would do. week_label missing (an older row, or a
    // program with only one week) reads as "Week 1".
    function weekGroups() {
      const byWeek = {};
      const order = [];
      exercises.forEach((r) => {
        const wl = r.week_label || "Week 1";
        if (!byWeek[wl]) { byWeek[wl] = { days: {}, dayOrder: [] }; order.push(wl); }
        const wk = byWeek[wl];
        if (!wk.days[r.day_label]) { wk.days[r.day_label] = []; wk.dayOrder.push(r.day_label); }
        wk.days[r.day_label].push(r);
      });
      return order.map((label) => ({ label, days: byWeek[label].dayOrder.map((d) => ({ label: d, rows: byWeek[label].days[d] })) }));
    }

    // Exposed so ProgramsPanel's own "Request this program" button (on each
    // locked browse card) can trigger a real pick directly, reusing this
    // exact tested handleAssign logic instead of a second copy of it. Called
    // unconditionally, before the loading early-return below, per the rules
    // of hooks.
    React.useImperativeHandle(ref, () => ({ quickPick: (programId) => handleAssign(programId) }));

    if (!loaded) return e("div", { style: styles.empty }, e("p", { style: styles.emptyText }, "Loading program…"));

    // Blocks picking or changing a program at all, before any $35 payment
    // even enters the picture — Jimmy's call (Sept 5 2026): a self-train
    // client must already have this month's $10 app access marked PAID
    // (not just be inside the free trial) before they're allowed to buy a
    // program. Never true for a manager or a trainer-attached client.
    const purchaseLocked = gatePayment && !paidAccessOk;
    const pendingPayment = gatePayment && !(assignment && assignment.paid);
    // The $35 unlocks this program once, but a self-train client's monthly
    // $10 is what keeps it viewable — same rule as Log/Diet. If they've paid
    // for the program but their app access has lapsed, the program re-locks
    // too, and comes back as soon as they're paid up again (no re-buying the
    // program). appAccessOk is always true for managers and trainer-attached
    // clients, so this never affects them.
    const subscriptionLocked = gatePayment && !pendingPayment && !appAccessOk;
    const contentLocked = pendingPayment || subscriptionLocked;

    // Shown instead of the program card's own content whenever picking is
    // true — for BOTH "has a program, tapped Change" and "no program yet,
    // tapped Assign a program". Previously this form only ever rendered
    // appended after the current program's full exercise list, which for a
    // multi-day circuit program could be 30+ rows down — easy to tap
    // "Change" and see nothing happen without scrolling a long way. Putting
    // it right where the program's own content normally sits means it's
    // visible immediately, no scrolling required.
    const pickerForm = e("div", { style: { ...styles.sessionForm, marginTop: program ? 0 : 14 } },
      e("label", { style: styles.formLabel }, "Choose a program"),
      allPrograms.length === 0
        ? e("p", { style: styles.emptyText }, "No programs exist yet — build one in the Programs tab first.")
        : e(Select, { value: pickedId, onChange: setPickedId, options: allPrograms.map((p) => ({ value: p.id, label: `${styleLabel(p.style)} — ${p.name}` })), style: { width: "100%" } }),
      e("div", { style: { display: "flex", gap: 8, marginTop: 12 } },
        // Sept 18 2026 retest round 2: this was `onClick: handleAssign`,
        // which hands handleAssign the raw click SyntheticEvent as its
        // `explicitId` argument (React always passes the event to a
        // directly-referenced handler). Since that event object is truthy,
        // `explicitId || pickedId` picked the EVENT over the actual
        // dropdown selection every time — the insert then failed (an event
        // object isn't a program id) and "Assign" from this picker form
        // could never actually succeed, always landing on the generic
        // "Couldn't assign that program" error. Wrapping in an arrow so no
        // argument is passed and it correctly falls back to pickedId.
        e("button", { style: { ...styles.saveBtn, marginTop: 0, flex: 1, ...(saving ? styles.btnDisabled : {}) }, disabled: saving || allPrograms.length === 0, onClick: () => handleAssign() }, saving ? "Assigning…" : "Assign"),
        e("button", { style: { ...styles.demoLinkBtn, padding: "0 10px" }, onClick: () => { setPicking(false); setPickedId(""); setError(""); } }, "Cancel")
      )
    );

    const allWeekGroups = weekGroups();
    const groupsToShow = activeWeek === "all" ? allWeekGroups : allWeekGroups.filter((w) => w.label === activeWeek);

    return e("div", null,
      error && e("div", { style: { ...styles.errorBanner, margin: "0 0 12px" } }, e(Icon, { name: "x", size: 13, color: C.critical }), error),
      program
        ? e("div", {
            style: {
              ...styles.programCard, position: "relative", overflow: "hidden",
              // Sept 11 2026, Jimmy: brand-ring "current plan" treatment,
              // matching the reference mockup — only once it's actually
              // live (not mid-pick, not still locked behind payment).
              ...(!contentLocked && !picking ? { boxShadow: `inset 0 0 0 1.5px ${C.brand}, ${C.cardShadow}` } : {})
            }
          },
            e("div", { style: { display: "flex", justifyContent: "space-between", alignItems: "flex-start", gap: 8 } },
              e("div", { style: styles.programHeader },
                e("div", { style: { display: "flex", alignItems: "center", gap: 10 } },
                  !contentLocked && !picking && e("div", { style: styles.planHeroIconWrap }, e(Icon, { name: "dumbbell", size: 16, color: C.brand })),
                  e("div", null,
                    e("span", { style: styles.demoNote }, styleLabel(program.style)),
                    e("span", { style: { ...styles.sectionTitle, display: "block", marginTop: 2 } }, program.name)
                  )
                ),
                // Picking a program (even before paying) used to reveal its
                // full description here immediately — same leak as the
                // browse list, just one screen later. Clamp it the same way
                // while payment/access is locked; it opens up full-width the
                // moment contentLocked clears.
                !picking && program.description && e("p", {
                  style: contentLocked
                    ? { ...styles.profileGoalText, marginTop: 4, display: "-webkit-box", WebkitLineClamp: 3, WebkitBoxOrient: "vertical", overflow: "hidden" }
                    : { ...styles.profileGoalText, marginTop: 4 }
                }, program.description)
              ),
              e("div", { style: { display: "flex", flexDirection: "column", alignItems: "flex-end", gap: 8, flexShrink: 0 } },
                !contentLocked && !picking && e("span", { style: styles.currentBadge }, e(Icon, { name: "check", size: 9, color: C.brandInk }), "CURRENT"),
                canAssign && !picking && e("div", { style: { display: "flex", gap: 8, alignItems: "center" } },
                  // Switching to a different program is a new pick — same
                  // paid-access-required rule as picking one the first time —
                  // so "Change" is hidden while purchaseLocked. Removing the
                  // current pick (trash) stays available either way; it's not
                  // a purchase.
                  !purchaseLocked && e("button", { style: styles.demoLinkBtn, onClick: openPicker }, "Change"),
                  e("button", { style: styles.deleteBtn, onClick: () => setConfirmUnassign(true), "aria-label": "Unassign program" }, e(Icon, { name: "trash", size: 14 }))
                )
              )
            ),
            confirmUnassign && e("div", { style: { ...styles.deleteConfirmBar, flexDirection: "column", alignItems: "stretch", gap: 8, marginTop: 10 } },
              e("span", { style: styles.deleteConfirmText },
                isSelfTrain
                  ? `Remove this program? ${gatePayment ? "You'll" : "They'll"} lose access to it. Picking it again later won't ask for payment again, but a different one will.`
                  : "Remove this program? They'll lose access to it until it's assigned again."
              ),
              e("div", { style: { display: "flex", gap: 8 } },
                e("button", { style: { ...styles.confirmCancelBtn, flex: 1 }, onClick: () => setConfirmUnassign(false) }, "Cancel"),
                e("button", { style: { ...styles.confirmDangerBtn, flex: 1 }, onClick: handleUnassign }, "Remove")
              )
            ),
            !contentLocked && !picking && allWeekGroups.length > 0 && e("button", {
              style: { ...styles.ghostPillBtn, marginTop: 12 },
              onClick: () => programDetailRef.current && programDetailRef.current.scrollIntoView({ behavior: "smooth", block: "start" })
            }, "View full program", e(Icon, { name: "chevron", size: 13, color: C.ink, strokeWidth: 2.4 })),
            picking
              ? e("div", { style: { marginTop: 16 } }, pickerForm)
              : (pendingPayment
                  ? e("div", { style: { ...styles.empty, marginTop: 16, flexDirection: "column", alignItems: "center", gap: 8 } },
                      e(Icon, { name: "lock", size: 20, color: C.ink3 }), e("p", { style: styles.emptyText }, "Pay below to unlock this program."),
                      // Same real stepper as the app-access lock screens — the
                      // client can mark "I've sent the payment" and then see
                      // "Under review" right here instead of a static line
                      // with no way to tell it went anywhere. Context is keyed
                      // per program (program.id), separate from the app-access
                      // claim below, since a client can owe both at once.
                      e(PaymentStatusStepper, { email: userEmail, context: `program_${program.id}`, amount: PROGRAM_PRICE, approvedCopy: "Approved — unlocked" })
                    )
                  : subscriptionLocked
                  ? e("div", { style: { ...styles.empty, marginTop: 16, flexDirection: "column", alignItems: "center", gap: 8 } },
                      e(Icon, { name: "lock", size: 20, color: C.ink3 }), e("p", { style: styles.emptyText }, `Your $${PROGRAM_PRICE} program is on hold — pay this month's $${SELF_TRAIN_MONTHLY_PRICE} app access to see it again.`),
                      // Same claim as the Log/Diet app-access lock screen
                      // (context "self_train_access") — it's the same $/month
                      // payment, so marking it sent on either screen clears
                      // both.
                      e(PaymentStatusStepper, { email: userEmail, context: "self_train_access", amount: SELF_TRAIN_MONTHLY_PRICE, approvedCopy: "Approved — unlocked" })
                    )
                  : e("div", { ref: programDetailRef },
                      // Sept 15 2026, Jimmy: same "press the week and see
                      // the workout" chip row as the trainer-written
                      // program below — jumping to a specific week is one
                      // tap instead of a scroll past every week before it.
                      allWeekGroups.length > 1 && e("div", { style: { display: "flex", gap: 6, flexWrap: "wrap", marginBottom: 16 } },
                        [{ label: "all", text: "All weeks" }, ...allWeekGroups.map((w) => ({ label: w.label, text: w.label }))].map((opt) => {
                          const active = activeWeek === opt.label;
                          return e("button", {
                            key: opt.label, type: "button", onClick: () => setActiveWeek(opt.label),
                            style: {
                              display: "inline-flex", alignItems: "center", background: active ? C.brandSoft : "transparent",
                              color: active ? C.brand : C.ink3, border: `1px solid ${active ? withAlpha(C.brand, 0.4) : C.cardBorder}`,
                              borderRadius: 20, padding: "6px 12px", fontFamily: "'Inter', sans-serif", fontSize: 12.5, fontWeight: 700,
                              cursor: "pointer", whiteSpace: "nowrap"
                            }
                          }, opt.text);
                        })
                      ),
                      groupsToShow.map((week) => e("div", { key: week.label, style: { marginTop: 16 } },
                        e("div", { style: { ...styles.sectionTitle, fontSize: 13.5 } }, week.label),
                        week.days.map((day) => e("div", { key: day.label, style: { marginTop: 10, marginLeft: 8 } },
                          e("div", { style: styles.dayHead }, day.label),
                          e("div", { style: { display: "flex", flexDirection: "column", gap: 8, marginTop: 8 } },
                            day.rows.map((ex) => e(ProgramExerciseRow, { key: ex.id, ex, canManage: false, onEdit: () => {}, onDelete: () => {}, onLogWeight: () => setLogTarget({ ex, contextLabel: `${program.name} — ${week.label} · ${day.label}` }) }))
                          )
                        ))
                      ))
                    )
                ),
            !contentLocked && !picking && e(ProgramWatermark, { label: clientName }),
            logTarget && e(LogProgramWeightModal, {
              ex: logTarget.ex, clientId, clientName, contextLabel: logTarget.contextLabel,
              onClose: () => setLogTarget(null)
            })
          )
        : e("div", { style: styles.empty }, e(ProgramsEmptyArt, {}), e("p", { style: { ...styles.emptyText, ...(!canAssign && !isSelfTrain && !nudgeSent ? { marginBottom: 8 } : {}) } },
            canAssign
              ? (purchaseLocked
                  // Sept 13 2026, Jimmy: "to be clear that the $10 is
                  // subscription before he buys the program" — a
                  // self-train client hits this even mid-free-trial (see
                  // the purchaseLocked rule above: paid access, not just
                  // "in trial", is required before picking a program), so
                  // without this the $10 read as if it were the program's
                  // price. Spelled out as the recurring monthly app
                  // subscription, separate from the program itself.
                  ? `This $${SELF_TRAIN_MONTHLY_PRICE} is your monthly app subscription — not the program itself. It needs to be paid first, even while your free trial is still running, before you can pick a program. Pay below, then come back here.`
                  : gatePayment ? `No program picked yet — browse below, choose one, then pay to unlock it ($${PROGRAM_PRICE}).` : "No program assigned yet.")
              : (isSelfTrain ? "No program assigned yet — pay to unlock the program library." : "No program assigned yet — ask your trainer.")
          ),
          // Sept 19 2026, walkthrough fix: same one-tap nudge DietPanel
          // already has — only for the trainer-attached case (the only one
          // with a real trainer to nudge; isSelfTrain has no trainer,
          // canAssign is a manager viewing a client, not the client itself).
          !canAssign && !isSelfTrain && trainerId && (!nudgeSent
            ? e("button", { type: "button", style: { ...styles.demoLinkBtn, padding: "0" }, onClick: handleNudgeTrainer }, "Nudge my trainer →")
            : nudgeSent && e("p", { style: { ...styles.emptyText, fontSize: 11.5, color: C.good } }, "Nudge sent — your trainer's been notified.")),
          purchaseLocked && e(WhishPayBox, { amount: SELF_TRAIN_MONTHLY_PRICE, note: "which is your monthly app subscription, then wait for JimFit to confirm — programs unlock once you're paid up" })
          ),
      // "Assign a program" reads like manager/trainer language when it's a
      // self-training client picking one for themselves — same button and
      // handler, just a wording swap based on who's looking at it.
      canAssign && !program && !picking && !purchaseLocked && e("button", { style: { ...styles.newBtn, marginTop: 14 }, onClick: openPicker }, e(Icon, { name: "calendar", size: 15 }), isSelfTrain ? "Choose a program" : "Assign a program"),
      canAssign && !program && picking && pickerForm
    );
  });

export { ClientProgramCard };
