// @generated by tools/extract/extract.py — bodies copied verbatim from index.html
import { INJURY_SEVERITIES } from "../../domain/body.js";
import { C } from "../../shared/theme.js";

  function injurySeverityColor(sev) {
    const found = INJURY_SEVERITIES.find((s) => s.value === sev);
    return C[found ? found.colorKey : "warning"];
  }

export { injurySeverityColor };
