// @generated by tools/extract/extract.py — app bootstrap
import { TrainingLog } from "./app/TrainingLog.js";
import { e } from "./shared/react.js";
import ReactDOM from "react-dom/client";

const root = ReactDOM.createRoot(document.getElementById("root"));
  // Guarantee the branded splash (#__strain_loading, in the static HTML
  // above) is visible for at least MIN_SPLASH_MS from true page-load start
  // (stamped at the very top of <head>, before the CDN scripts). On a fast
  // / cached connection the whole boot can finish in well under a frame,
  // which made the splash invisible in practice. On a slow connection this
  // adds no extra wait at all, since the CDN load already ate the budget.
  var MIN_SPLASH_MS = 550;
  var __bootStart = window.__jimfitBootStart || Date.now();
  var __wait = Math.max(0, MIN_SPLASH_MS - (Date.now() - __bootStart));
  setTimeout(function () { root.render(e(TrainingLog, null)); }, __wait);
