// @generated by tools/extract/extract.py — bodies copied verbatim from index.html
import { ACTIVITY_LEVELS, FAT_PCT_OPTIONS } from "../../domain/body.js";
import { GOAL_TYPES } from "../../domain/group1.js";
import { defaultActivityKey } from "../../domain/group2.js";
import { e } from "../../shared/react.js";
import { C, styles } from "../../shared/theme.js";
import { Select } from "../../shared/ui/group1.js";
import { useState } from "react";

  function CalorieCalculator({ latestAssessment, profile, onApply }) {
    const bmr = latestAssessment && latestAssessment.bmr;
    const bodyWeight = (latestAssessment && latestAssessment.weight) || (profile && profile.weight_kg);
    const [activityKey, setActivityKey] = useState(defaultActivityKey(profile && profile.days_per_week));
    const [goalKey, setGoalKey] = useState("maintain");
    const [fatPct, setFatPct] = useState(0.25);
    const [applied, setApplied] = useState(false);

    if (bmr == null) return null;

    const activity = ACTIVITY_LEVELS.find((a) => a.key === activityKey) || ACTIVITY_LEVELS[2];
    const goal = GOAL_TYPES.find((g) => g.key === goalKey) || GOAL_TYPES[1];
    const tdee = Math.round(bmr * activity.mult);
    const suggestedCalories = Math.round(tdee * goal.mult);
    const proteinPerKg = (profile && profile.gender === "Female") ? 1.6 : 2;
    const suggestedProtein = bodyWeight ? Math.round(bodyWeight * proteinPerKg) : null;
    const proteinCals = suggestedProtein ? suggestedProtein * 4 : 0;
    const suggestedFat = Math.round((suggestedCalories * fatPct) / 9);
    const fatCals = suggestedFat * 9;
    const suggestedCarbs = Math.max(0, Math.round((suggestedCalories - proteinCals - fatCals) / 4));

    return e("div", { style: { ...styles.card, marginBottom: 14 } },
      e("span", { style: styles.profileLabel }, "🧮 Calorie calculator (from BMR)"),
      // Sept 14 2026, Jimmy: "same here to show that is tappable" — these
      // were plain <select> elements styled like a text input, with no
      // visible dropdown affordance. Swapped for the shared Select component
      // (same chevron treatment used for the workout filter elsewhere), so
      // it's obvious these are pickers, not a box to type into.
      e("div", { style: { display: "flex", gap: 10, marginTop: 8, marginBottom: 10, flexWrap: "wrap" } },
        e(Select, {
          style: { flex: "1 1 160px" }, value: activityKey,
          onChange: (v) => { setActivityKey(v); setApplied(false); },
          options: ACTIVITY_LEVELS.map((a) => ({ value: a.key, label: `${a.emoji} ${a.label}` }))
        }),
        e(Select, {
          style: { flex: "1 1 120px" }, value: goalKey,
          onChange: (v) => { setGoalKey(v); setApplied(false); },
          options: GOAL_TYPES.map((g) => ({ value: g.key, label: `${g.emoji} ${g.label}` }))
        })
      ),
      e("div", { style: { marginBottom: 10 } },
        e("span", { style: { ...styles.profileLabel, marginBottom: 6 } }, "🥑 Fat % of calories"),
        e(Select, {
          value: String(fatPct),
          onChange: (v) => { setFatPct(Number(v)); setApplied(false); },
          options: FAT_PCT_OPTIONS.map((p) => ({ value: String(p), label: `🥑 ${Math.round(p * 100)}% — carbs fill the rest` }))
        })
      ),
      e("p", { style: { ...styles.profileGoalText, marginBottom: 6 } },
        `${bmr} kcal BMR × ${activity.mult} activity = ${tdee} kcal maintenance, × ${goal.mult} for ${goal.label.split(" (")[0].toLowerCase()} = `,
        e("span", { style: { color: C.brand, fontWeight: 700 } }, `${suggestedCalories} kcal/day`)
      ),
      e("p", { style: { ...styles.profileGoalText, marginBottom: 12, fontSize: 12 } },
        bodyWeight != null
          ? `Suggested split (protein at ${proteinPerKg}g/kg, fat at ${Math.round(fatPct * 100)}%): ${suggestedProtein}g protein · ${suggestedCarbs}g carbs · ${suggestedFat}g fat`
          : "Add a body weight in Assessments to also get a suggested macro split."
      ),
      e("button", {
        style: { ...styles.saveBtn, marginTop: 0, ...(applied ? { background: C.good } : {}) },
        onClick: () => { onApply({ calories: suggestedCalories, protein: suggestedProtein, carbs: suggestedCarbs, fat: suggestedFat }); setApplied(true); }
      }, applied ? "Applied to targets ✓" : "Apply to daily targets")
    );
  }

export { CalorieCalculator };
