// @generated by tools/extract/extract.py — bodies copied verbatim from index.html
import { DIET_REQUEST_TABS } from "../../domain/group1.js";
import { sb } from "../../platform/supabase.js";
import { fmtDate } from "../../shared/lib/format.js";
import { e } from "../../shared/react.js";
import { C, styles } from "../../shared/theme.js";
import { Icon } from "../../shared/ui/Icon.js";
import { PeopleEmptyArt } from "../../shared/ui/empty-art.js";
import { Segmented } from "../../shared/ui/group1.js";
import { DietPlanRequestRow } from "./DietPlanRequestRow.js";
import { useEffect, useMemo, useState } from "react";

  // Doubles as the paid-vs-unpaid diet roster Jimmy asked for, same pattern
  // as ProgramRequestsPanel's Paid tab: a running total off paidPayments
  // (sourced from allPayments up in the Owner view — no separate fetch).
  // Diet payments aren't tied to a specific template the way a program
  // payment is tied to a program_id, so a paid row shows client/amount/date
  // only — no "which plan" column.
  function DietPlanRequestsPanel({ requests, paidPayments = [], profiles = [], trainers = [], onResolved, onDeletePayment, onIncrementTotalDue = null }) {
    const [tab, setTab] = useState("pending");
    // Sept 14 2026, Jimmy: "add here a search button" on the Paid list —
    // same search-by-name pattern as every other roster in this app.
    const [paidSearch, setPaidSearch] = useState("");
    const visiblePaidPayments = useMemo(() => {
      const q = paidSearch.trim().toLowerCase();
      if (!q) return paidPayments;
      return paidPayments.filter((p) => (p.client_name || "").toLowerCase().includes(q));
    }, [paidPayments, paidSearch]);
    // Sept 6 2026, Jimmy: "no phone number for trainer! i need this for
    // trainers" — a trainer's own diet plan request (selfLog, from his "My
    // Diet" tab) showed no phone here at all, since `profiles` deliberately
    // excludes every is_trainer_self_log row (see CoachView's fetch) so it
    // never pollutes a real client roster. Fetched separately here: just
    // enough to map that self-log row's user_id to the trainer's own name
    // (client_name is always set to trainer.name for these rows — see the
    // self-log row's insert on My Diet), then resolved to a phone via the
    // trainers list (now has its own phone column, settable from Trainer
    // billing or at Add-trainer time).
    const [selfLogNameByUserId, setSelfLogNameByUserId] = useState({});
    useEffect(() => {
      if (!sb) return;
      sb.from("client_profiles").select("user_id, client_name").eq("is_trainer_self_log", true).then(({ data, error: err }) => {
        if (err || !data) return;
        const map = {};
        data.forEach((r) => { if (r.user_id && r.client_name) map[r.user_id] = r.client_name; });
        setSelfLogNameByUserId(map);
      });
    }, []);
    const trainerPhoneByName = useMemo(() => {
      const map = {};
      trainers.forEach((t) => { if (t.name && t.phone) map[t.name] = t.phone; });
      return map;
    }, [trainers]);
    // A Whish transfer shows up by phone number, not by name — this is how
    // Jimmy matches an incoming payment to the right pending request when
    // he's checking his Whish app, without needing to open every client's
    // profile first.
    const phoneByUserId = useMemo(() => {
      const map = {};
      profiles.forEach((p) => { if (p.user_id && p.phone) map[p.user_id] = p.phone; });
      Object.keys(selfLogNameByUserId).forEach((userId) => {
        const phone = trainerPhoneByName[selfLogNameByUserId[userId]];
        if (phone) map[userId] = phone;
      });
      return map;
    }, [profiles, selfLogNameByUserId, trainerPhoneByName]);
    // Sept 19 2026 inspection fix: lets DietPlanRequestRow bump the right
    // client's total_due on unlock (see handleUnlock there). Deliberately
    // built from `profiles` alone, same as phoneByUserId's real-client
    // half — a trainer's own self-log request has no matching entry here
    // (profiles excludes those rows) and correctly ends up with no
    // clientId, so it's skipped rather than touching some other row.
    const clientIdByUserId = useMemo(() => {
      const map = {};
      profiles.forEach((p) => { if (p.user_id) map[p.user_id] = p.id; });
      return map;
    }, [profiles]);

    // Just for resolving a requested ready plan's name onto its row below —
    // the request itself only ever stores template_id, same "join" pattern
    // ClientProgramCard uses to look up a program's name from program_id.
    const [templates, setTemplates] = useState([]);
    useEffect(() => {
      if (!sb) return;
      sb.from("diet_plan_templates").select("id, name").then(({ data, error: err }) => {
        if (!err && data) setTemplates(data);
      });
    }, []);

    const paidTotal = useMemo(() => paidPayments.reduce((sum, p) => sum + (Number(p.amount) || 0), 0), [paidPayments]);
    // Sept 6 2026, Jimmy: "if he deleted the plan he took by mistake or the
    // client did can they also get the plan again without paying... he
    // chose other program then he pay for it" — every past diet-plan
    // payment now tags which template it was for (see the two unlock
    // sites that insert client_payments), so a pending request whose
    // template exactly matches a past payment BY THIS SAME PERSON is
    // recognized here as already paid. A different template never
    // matches, so switching to a new plan still charges — same rule
    // programs already use for client_program_assignments.
    const paidTemplateKeys = useMemo(() => {
      const set = new Set();
      paidPayments.forEach((p) => { if (p.user_id && p.template_id) set.add(`${p.user_id}:${p.template_id}`); });
      return set;
    }, [paidPayments]);

    return e("div", null,
      e(Segmented, {
        options: DIET_REQUEST_TABS.map((t) => ({
          ...t,
          label: t.value === "pending" ? (requests.length > 0 ? `${t.label} (${requests.length})` : t.label) : (paidPayments.length > 0 ? `${t.label} (${paidPayments.length})` : t.label)
        })),
        value: tab, onChange: setTab
      }),
      tab === "pending"
        ? (requests.length === 0
            ? e("div", { style: { ...styles.empty, marginTop: 14 } }, e(PeopleEmptyArt, {}), e("p", { style: styles.emptyText }, "No pending diet plan requests."))
            : e("div", { style: { display: "flex", flexDirection: "column", gap: 10, marginTop: 14 } },
                requests.map((req) => {
                  // A switch request (already-unlocked client) stores the
                  // NEW pick in pending_switch_template_id, not template_id
                  // (which still holds their current, still-active plan) —
                  // resolve whichever one is actually the pending ask.
                  const isSwitch = !!req.pending_switch_template_id;
                  const tplId = isSwitch ? req.pending_switch_template_id : req.template_id;
                  const tpl = tplId ? templates.find((t) => t.id === tplId) : null;
                  const alreadyPaid = !!(tplId && req.user_id && paidTemplateKeys.has(`${req.user_id}:${tplId}`));
                  return e(DietPlanRequestRow, { key: req.id, req, templateName: tpl ? tpl.name : null, isSwitch, clientPhone: phoneByUserId[req.user_id] || null, alreadyPaid, clientId: clientIdByUserId[req.user_id] || null, onIncrementTotalDue, onResolved });
                })
              )
          )
        : (paidPayments.length === 0
            ? e("div", { style: { ...styles.empty, marginTop: 14 } }, e(PeopleEmptyArt, {}), e("p", { style: styles.emptyText }, "No diet plan payments logged yet."))
            : e("div", { style: { marginTop: 14 } },
                e("div", { style: styles.dashGrid },
                  e("div", { style: styles.dashTile }, e("span", { style: styles.profileLabel }, "Collected"), e("span", { style: styles.dashTileValue }, `$${paidTotal.toLocaleString()}`)),
                  e("div", { style: styles.dashTile }, e("span", { style: styles.profileLabel }, "Clients"), e("span", { style: styles.dashTileValue }, String(paidPayments.length)))
                ),
                e("div", { style: { display: "flex", alignItems: "center", justifyContent: "space-between", marginTop: 14, marginBottom: 4 } },
                  e("div", { style: styles.rosterSearchWrap },
                    e(Icon, { name: "search", size: 14, color: C.ink3 }),
                    e("input", {
                      style: styles.rosterSearchInput, type: "text", value: paidSearch,
                      onChange: (ev) => setPaidSearch(ev.target.value),
                      placeholder: "Search by name…"
                    }),
                    paidSearch && e("button", {
                      type: "button", onClick: () => setPaidSearch(""), style: styles.rosterSearchClear, "aria-label": "Clear search"
                    }, e(Icon, { name: "x", size: 12, color: C.ink3 }))
                  ),
                  e("span", { style: styles.rosterCount }, visiblePaidPayments.length, "/", paidPayments.length)
                ),
                visiblePaidPayments.length === 0
                  ? e("div", { style: styles.empty }, e("p", { style: styles.emptyText }, `No payments match "${paidSearch.trim()}".`))
                  : e("div", { style: { display: "flex", flexDirection: "column", gap: 10, marginTop: 10 } },
                      visiblePaidPayments.map((p) => {
                        // Sept 6 2026, Jimmy: "i want to see here what diet plan
                        // he chose" — now resolvable per-payment since each
                        // unlock tags its own template_id (previously this row
                        // just said "Diet plan" with no way to tell which one —
                        // see the comment this replaced). Still says "Diet
                        // plan" for a template-less custom pick or an older
                        // payment logged before this column existed.
                        const tpl = p.template_id ? templates.find((t) => t.id === p.template_id) : null;
                        return e("div", { key: p.id, style: styles.trainerStatCard },
                          e("div", { style: { display: "flex", justifyContent: "space-between", alignItems: "flex-start", gap: 8 } },
                            e("div", { style: { display: "flex", flexDirection: "column", gap: 3 } },
                              e("span", { style: styles.exerciseName }, p.client_name || "Unknown client"),
                              e("span", { style: styles.muscleSubText }, tpl ? tpl.name : "Diet plan")
                            ),
                            e("div", { style: { display: "flex", alignItems: "center", gap: 10 } },
                              e("div", { style: { display: "flex", flexDirection: "column", alignItems: "flex-end", gap: 3 } },
                                e("span", { style: styles.rosterVol }, `$${Number(p.amount).toLocaleString()}`),
                                e("span", { style: styles.muscleSubText }, fmtDate((p.paid_on || "").slice(0, 10)))
                              ),
                              onDeletePayment && e("button", {
                                style: styles.deleteBtn, onClick: () => onDeletePayment(p), "aria-label": "Delete payment", title: "Delete payment"
                              }, e(Icon, { name: "trash", size: 15 }))
                            )
                          )
                        );
                      })
                    )
              )
          )
    );
  }

export { DietPlanRequestsPanel };
