// @generated by tools/extract/extract.py — bodies copied verbatim from index.html
import { MEAL_GEN_DIET_OPTIONS, MEAL_GEN_GOALS, MEAL_GEN_GOAL_OPTIONS, MEAL_GEN_MEAL_LABELS, MEAL_GEN_MEAL_ORDER, MEAL_GEN_SWAPS } from "../../domain/nutrition.js";
import { sb } from "../../platform/supabase.js";
import { e } from "../../shared/react.js";
import { C, styles } from "../../shared/theme.js";
import { Icon } from "../../shared/ui/Icon.js";
import { Segmented } from "../../shared/ui/group1.js";
import { MealGenFoodRow, MealGroupHeader, generateMealPlan, mealTheme } from "./group1.js";
import { useMemo, useState } from "react";

  // Client-facing "build me a plan right now" flow — 3 quick picks (goal,
  // diet, calories) then a live-computed day of meals. Nothing here is saved;
  // changing any answer just recomputes instantly. Sits alongside (not
  // instead of) the ready-templates browser and the custom-plan request.
  // saved (when present, as {goal, diet, calories}) means the client already
  // confirmed a plan — render that result read-only, no picker, so reopening
  // the app always shows the same plan instead of asking them to choose
  // again. With no saved plan yet, canConfirm=true (the normal client path)
  // shows the picker plus a "Confirm & save" step; canConfirm=false is the
  // old free-preview behavior, unused by DietPanel now but kept in case a
  // manager wants a no-commitment preview later.
  function InstantMealPlanPanel({ onClose, clientName, saved = null, onSaved, canConfirm = true }) {
    const [genGoal, setGenGoal] = useState((saved && saved.goal) || MEAL_GEN_GOAL_OPTIONS[0].value);
    const [genDiet, setGenDiet] = useState((saved && saved.diet) || MEAL_GEN_DIET_OPTIONS[0].value);
    const [genCalories, setGenCalories] = useState((saved && saved.calories) || null);
    const [showSwaps, setShowSwaps] = useState(false);
    const [saving, setSaving] = useState(false);
    const [saveError, setSaveError] = useState("");

    const locked = !!saved;
    const dietKey = genDiet === "lactose_free" ? "lactose_free" : genDiet;
    const bands = MEAL_GEN_GOALS[genGoal].bands;
    const bandLabels = ["Lower", "Middle", "Higher"];
    const result = useMemo(
      () => (genCalories != null ? generateMealPlan(genGoal, dietKey, genCalories) : null),
      [genGoal, dietKey, genCalories]
    );
    const swaps = MEAL_GEN_SWAPS[dietKey] || MEAL_GEN_SWAPS.standard;

    // Only ever writes the caller's own diet_plans row (same SECURITY
    // DEFINER pattern as request_diet_plan) — a client has no direct write
    // access to diet_plans otherwise.
    async function handleConfirm() {
      if (!sb || !result) return;
      setSaveError("");
      setSaving(true);
      const { error: err } = await sb.rpc("save_instant_meal_plan", {
        p_client_name: clientName, p_goal: genGoal, p_diet: genDiet, p_calories: genCalories
      });
      setSaving(false);
      if (err) { setSaveError("Couldn't save: " + err.message); return; }
      if (onSaved) onSaved({ goal: genGoal, diet: genDiet, calories: genCalories });
    }

    return e("div", { style: { ...styles.sessionForm, marginTop: 10 } },
      e("div", { style: { display: "flex", justifyContent: "space-between", alignItems: "center" } },
        e("span", { style: { fontFamily: "'Oswald', sans-serif", fontWeight: 600, fontSize: 13, letterSpacing: "0.02em", color: C.ink } }, "Instant meal plan"),
        !locked && onClose && e("button", { style: { ...styles.demoLinkBtn, padding: "0 10px" }, onClick: onClose }, "Close")
      ),
      locked
        ? e("p", { style: { ...styles.profileGoalText, fontSize: 12, marginTop: 4 } }, "This is your confirmed plan — ask your gym if you'd like a different one.")
        : e("p", { style: { ...styles.profileGoalText, fontSize: 12, marginTop: 4 } }, canConfirm
            ? "Pick a goal, a diet, and a calorie target, preview it, then confirm to save it as your plan."
            : "Pick a goal, a diet, and a calorie target — we'll build today's meals from it on the spot. Nothing is saved; change any answer to regenerate."
          ),
      !locked && e("div", { style: { marginTop: 14 } },
        e("span", { style: { ...styles.profileLabel, display: "block", marginBottom: 6 } }, "Goal"),
        e(Segmented, { options: MEAL_GEN_GOAL_OPTIONS, value: genGoal, onChange: (v) => { setGenGoal(v); setGenCalories(null); } })
      ),
      !locked && e("div", { style: { marginTop: 12 } },
        e("span", { style: { ...styles.profileLabel, display: "block", marginBottom: 6 } }, "Diet"),
        e(Segmented, { options: MEAL_GEN_DIET_OPTIONS, value: genDiet, onChange: setGenDiet })
      ),
      !locked && e("div", { style: { marginTop: 12 } },
        e("span", { style: { ...styles.profileLabel, display: "block", marginBottom: 6 } }, "Calories"),
        e("div", { style: { display: "flex", gap: 8, flexWrap: "wrap" } },
          bands.map((kcal, i) => e("button", {
            key: i,
            style: {
              ...styles.demoLinkBtn,
              border: `1px solid ${genCalories === kcal ? C.brand : C.cardBorderStrong}`,
              ...(genCalories === kcal ? { color: C.brand, background: C.brandSoft } : {})
            },
            onClick: () => setGenCalories(kcal)
          }, `${bandLabels[i]} · ${kcal} kcal`))
        )
      ),
      result && e("div", { style: { marginTop: 18, paddingTop: 14, borderTop: `1px solid ${C.cardBorder}` } },
        e("div", { style: styles.dashGrid },
          e("div", { style: styles.trainerStatCard }, e("span", { style: styles.profileLabel }, "Calories"), e("span", { style: { ...styles.profileValue, display: "block" } }, `${result.achievedCalories} kcal`)),
          e("div", { style: styles.trainerStatCard }, e("span", { style: styles.profileLabel }, "Protein"), e("span", { style: { ...styles.profileValue, display: "block" } }, `${result.achievedProtein} g`)),
          e("div", { style: styles.trainerStatCard }, e("span", { style: styles.profileLabel }, "Carbs"), e("span", { style: { ...styles.profileValue, display: "block" } }, `${result.achievedCarbs} g`)),
          e("div", { style: styles.trainerStatCard }, e("span", { style: styles.profileLabel }, "Fat"), e("span", { style: { ...styles.profileValue, display: "block" } }, `${result.achievedFat} g`))
        ),
        result.showClosestMatchNote && e("div", { style: { ...styles.setupNotice, marginTop: 12 } },
          e(Icon, { name: "alert", size: 14, color: C.ink3 }),
          `Closest balanced match for this combination — about ${Math.abs(result.offBy)} kcal ${result.offBy > 0 ? "over" : "under"} your ${result.targetCalories} kcal target. This happens on the hardest macro combinations (e.g. high protein on plant foods) — still nutritionally balanced.`
        ),
        MEAL_GEN_MEAL_ORDER.filter((m) => result.meals[m].length > 0).map((m) => e("div", { key: m, style: { marginTop: 16 } },
          e(MealGroupHeader, { label: MEAL_GEN_MEAL_LABELS[m] }),
          e("div", { style: { display: "flex", flexDirection: "column", gap: 8, marginTop: 8 } },
            result.meals[m].map((it, i) => e(MealGenFoodRow, { key: `${it.food}-${i}`, food: it.food, grams: it.grams, accentColor: mealTheme(MEAL_GEN_MEAL_LABELS[m]).color }))
          )
        )),
        e("div", { style: { marginTop: 16 } },
          e("button", {
            style: { ...styles.energyPillBtn, display: "inline-flex", alignItems: "center", gap: 6 },
            onClick: () => setShowSwaps((v) => !v)
          }, e(Icon, { name: "swap", size: 13, color: C.brand }), showSwaps ? "Hide food swaps" : "Show food swaps"),
          showSwaps && e("div", { style: { marginTop: 8, display: "flex", flexDirection: "column", gap: 8 } },
            swaps.map((s, i) => e("div", { key: i },
              e("span", { style: { ...styles.goalChip, color: C.brand, background: C.brandSoft } }, s.group),
              e("p", { style: { ...styles.profileGoalText, fontSize: 12, marginTop: 4 } }, s.text)
            ))
          )
        ),
        e("p", { style: { ...styles.profileGoalText, fontSize: 11, marginTop: 16, color: C.ink3 } }, "General nutrition guidance for healthy adults — not medical or individualised advice. Doesn't account for allergies, intolerances, medical conditions, pregnancy, or medication. If you have a health condition or specific dietary need, work with your doctor or a registered dietitian. Adjust portions for your own tolerance, preferences, and hunger."),
        !locked && canConfirm && e("div", { style: { marginTop: 16 } },
          saveError && e("span", { style: { ...styles.inlineError, display: "block", marginBottom: 8 } }, saveError),
          e("button", { style: { ...styles.saveBtn, marginTop: 0, ...(saving ? styles.btnDisabled : {}) }, disabled: saving, onClick: handleConfirm },
            saving ? "Saving…" : "Confirm & save this plan →"
          ),
          e("p", { style: { ...styles.profileGoalText, fontSize: 11, marginTop: 6 } }, "Once confirmed, this becomes your plan — you won't be asked to choose again.")
        )
      )
    );
  }

export { InstantMealPlanPanel };
