// @generated by tools/extract/extract.py — bodies copied verbatim from index.html
import { C } from "../../shared/theme.js";

  // Each diet = fixed foods (never scaled) + three scaling groups (protein,
  // carb, fat). `meals` on each entry is which of Breakfast/Lunch/Snack/Dinner
  // it's split evenly across. The generator solves one multiplier per group.
  const MEAL_GEN_DIETS = {
    standard: {
      fixed: [
        { food: "mixedVeg", grams: 150, meals: ["L"] },
        { food: "berries", grams: 100, meals: ["B"] },
        { food: "greens", grams: 100, meals: ["D"] }
      ],
      P: [
        { food: "chicken", grams: 130, meals: ["L"] },
        { food: "eggs", grams: 80, meals: ["B"] },
        { food: "greekYogurt", grams: 150, meals: ["S"] },
        { food: "fish", grams: 120, meals: ["D"] }
      ],
      C: [
        { food: "oats", grams: 40, meals: ["B"] },
        { food: "rice", grams: 130, meals: ["L", "D"] },
        { food: "potato", grams: 120, meals: ["D"] },
        { food: "banana", grams: 80, meals: ["B"] }
      ],
      F: [
        { food: "oliveOil", grams: 15, meals: ["L", "D"] },
        { food: "almonds", grams: 15, meals: ["S"] }
      ]
    },
    lactose_free: null, // filled in below (identical to standard, one swap)
    vegetarian: {
      fixed: [
        { food: "mixedVeg", grams: 150, meals: ["L"] },
        { food: "berries", grams: 100, meals: ["B"] },
        { food: "greens", grams: 100, meals: ["D"] }
      ],
      P: [
        { food: "eggWhites", grams: 150, meals: ["B"] },
        { food: "greekYogurt", grams: 200, meals: ["B", "S"] },
        { food: "whey", grams: 25, meals: ["S"] },
        { food: "tofu", grams: 80, meals: ["L", "D"] },
        { food: "eggs", grams: 50, meals: ["B"] }
      ],
      C: [
        { food: "oats", grams: 40, meals: ["B"] },
        { food: "rice", grams: 130, meals: ["L", "D"] },
        { food: "potato", grams: 120, meals: ["D"] },
        { food: "banana", grams: 80, meals: ["B"] }
      ],
      F: [
        { food: "oliveOil", grams: 15, meals: ["L", "D"] },
        { food: "almonds", grams: 15, meals: ["S"] }
      ]
    },
    vegan: {
      fixed: [
        { food: "mixedVeg", grams: 150, meals: ["L"] },
        { food: "greens", grams: 100, meals: ["D"] }
      ],
      P: [
        { food: "peaProtein", grams: 45, meals: ["S"] },
        { food: "tofu", grams: 120, meals: ["B", "L"] },
        { food: "tempeh", grams: 70, meals: ["L"] },
        { food: "soyYogurt", grams: 200, meals: ["B", "S"] },
        { food: "lentils", grams: 100, meals: ["D"] },
        { food: "soyMilk", grams: 150, meals: ["B"] }
      ],
      C: [
        { food: "oats", grams: 50, meals: ["B"] },
        { food: "rice", grams: 130, meals: ["L", "D"] },
        { food: "potato", grams: 120, meals: ["D"] },
        { food: "banana", grams: 100, meals: ["B"] }
      ],
      F: [
        { food: "oliveOil", grams: 15, meals: ["L", "D"] },
        { food: "peanutButter", grams: 12, meals: ["S"] },
        { food: "almonds", grams: 8, meals: ["S"] }
      ]
    }
  };
  // Lactose-free = Standard with Greek yogurt swapped for the lactose-free version.
  MEAL_GEN_DIETS.lactose_free = {
    fixed: MEAL_GEN_DIETS.standard.fixed,
    P: MEAL_GEN_DIETS.standard.P.map((it) => (it.food === "greekYogurt" ? { ...it, food: "lactoseFreeYogurt" } : it)),
    C: MEAL_GEN_DIETS.standard.C,
    F: MEAL_GEN_DIETS.standard.F
  };

export { MEAL_GEN_DIETS };
