// @generated by tools/extract/extract.py — bodies copied verbatim from index.html
import { e } from "../../shared/react.js";
import { styles } from "../../shared/theme.js";
import { Icon } from "../../shared/ui/Icon.js";
import { useEffect, useRef, useState } from "react";

  // Sept 13 2026, Jimmy: "diet plan looks i sent earlier ... work on them to
  // slide to unlock" — a real drag-to-confirm gesture for the diet plan's
  // $30 purchase, matching jimfit-flow_15.html's paywall button, in place
  // of the plain "Pick this plan ($30) →" tap button it's used for below.
  // Same onConfirm as that button always called (onPick(t.id)) — just a
  // slide instead of a single tap. Enter/Space while focused confirms
  // immediately too, so it's still usable without a pointer (screen reader,
  // keyboard-only). If the pick call finishes without this card unmounting
  // (the parent swaps to "ACTIVE"/"OWNED" on success, which removes this
  // control entirely) — i.e. it silently failed — the knob snaps back so it
  // can be tried again instead of sitting stuck on "Unlocking…".
  function SlideToUnlock({ price, label = "Drag to unlock", busy = false, onConfirm }) {
    const trackRef = useRef(null);
    const [offset, setOffset] = useState(0);
    const [dragging, setDragging] = useState(false);
    const [triggered, setTriggered] = useState(false);
    const dragInfo = useRef({ startX: 0, startOffset: 0, maxOffset: 0 });
    const wasBusy = useRef(busy);
    const KNOB = 42;

    useEffect(() => {
      if (wasBusy.current && !busy) { setOffset(0); setTriggered(false); }
      wasBusy.current = busy;
    }, [busy]);

    function maxOffsetFor(el) { return Math.max(1, el.offsetWidth - KNOB - 6); }

    function trigger(maxOffset) {
      setOffset(maxOffset);
      setTriggered(true);
      if (onConfirm) onConfirm();
    }

    function onPointerDown(ev) {
      if (busy || triggered) return;
      const el = trackRef.current;
      if (!el) return;
      dragInfo.current = { startX: ev.clientX, startOffset: offset, maxOffset: maxOffsetFor(el) };
      setDragging(true);
      if (el.setPointerCapture) { try { el.setPointerCapture(ev.pointerId); } catch (err) {} }
    }
    function onPointerMove(ev) {
      if (!dragging) return;
      const { startX, startOffset, maxOffset } = dragInfo.current;
      setOffset(Math.max(0, Math.min(maxOffset, startOffset + (ev.clientX - startX))));
    }
    function onPointerUp() {
      if (!dragging) return;
      setDragging(false);
      const { maxOffset } = dragInfo.current;
      if (maxOffset > 0 && offset >= maxOffset * 0.82) trigger(maxOffset);
      else setOffset(0);
    }
    function onKeyDown(ev) {
      if (busy || triggered) return;
      if (ev.key === "Enter" || ev.key === " ") {
        ev.preventDefault();
        const el = trackRef.current;
        trigger(el ? maxOffsetFor(el) : 60);
      }
    }

    return e("div", {
      ref: trackRef,
      role: "slider",
      tabIndex: busy || triggered ? -1 : 0,
      "aria-label": `${label} — $${price}`,
      "aria-valuemin": 0, "aria-valuemax": 100, "aria-valuenow": triggered ? 100 : 0,
      style: { ...styles.slideUnlockTrack, ...((busy || triggered) ? { cursor: "default" } : {}) },
      onPointerDown, onPointerMove, onPointerUp, onPointerCancel: onPointerUp, onKeyDown
    },
      e("div", { style: { ...styles.slideUnlockFill, width: `${offset + KNOB / 2 + 4}px` } }),
      e("span", { style: styles.slideUnlockLabel }, (busy || triggered) ? "Unlocking…" : `🔒 ${label} — $${price}`),
      e("div", { style: { ...styles.slideUnlockKnob, transform: `translateX(${offset}px)` } },
        e(Icon, { name: "lock", size: 16, color: "#F5C542" })
      )
    );
  }

export { SlideToUnlock };
