// @generated by tools/extract/extract.py — bodies copied verbatim from index.html
import { sb } from "../../platform/supabase.js";
import { e } from "../../shared/react.js";
import { C } from "../../shared/theme.js";
import { Icon } from "../../shared/ui/cross.js";
import { VoiceMicButton } from "../../shared/widgets/index.js";
import { useEffect, useLayoutEffect, useRef, useState } from "react";

  // Owner-only for now (wired in behind isManager, same as the rest of CoachView).
  // Calls a Supabase Edge Function ("ai-chat") which holds the real AI provider
  // key server-side — the key must never live in this client-side file, since
  // anyone can view-source a static site. Until that function is deployed and
  // its secret set, this panel just shows a clear "not set up yet" message
  // instead of a confusing generic failure.
  function AiChatPanel({ role = "client", userId = null } = {}) {
    // Sept 18 2026: "injuries never show up in AI Chat" review finding —
    // pulled in for the client's own chat (userId only passed at that call
    // site) so the AI actually gets told what's on file instead of coaching
    // blind. Read-only, same client_injuries table as everywhere else. Sent
    // as clientContext on every message below; the ai-chat Edge Function
    // itself (deployed straight to Supabase, not in this codebase — see
    // JimFit's own setup notes) needs a matching update to actually weave
    // clientContext.injuries into its system prompt, handed to Jimmy
    // separately since that file isn't something this session can edit or
    // deploy.
    const [injuries, setInjuries] = useState([]);
    useEffect(() => {
      if (!userId || !sb) { setInjuries([]); return; }
      sb.from("client_injuries").select("body_part, severity, note").eq("user_id", userId).order("created_at", { ascending: true })
        .then(({ data, error: err }) => setInjuries(!err && data ? data : []));
    }, [userId]);
    // Sept 15 2026, Jimmy QA: a trainer's own AI Chat (both the real-trainer
    // bottom-nav tab and the owner/manager's copy of the same tab in
    // CoachView) was reusing this exact client-facing greeting, suggested
    // prompts, and "double-check with your coach" disclaimer — which reads
    // oddly for a trainer, since they ARE the coach. `role` swaps in
    // coaching-oriented copy for those two call sites; the client call site
    // passes nothing and keeps the original copy exactly as before.
    const isTrainer = role === "trainer";
    const [messages, setMessages] = useState([
      {
        role: "assistant",
        content: isTrainer
          ? "Hey — ask me anything about programming, coaching, or how to use JimFit."
          : "Hey — ask me anything about training, nutrition, or how to use JimFit."
      }
    ]);
    // Sept 18 2026, Jimmy: "AI Chat conversations vanish the moment you
    // switch tabs or reload" review finding — this used to be pure
    // component state (`useState` above), gone the instant AiChatPanel
    // unmounted. Now backed by a new `ai_chat_messages` table (SQL handed
    // to Jimmy separately — this session has no direct DB access), keyed by
    // whoever's actually chatting: the client call site already passes
    // `userId` directly; the two trainer/manager call sites (TrainerView's
    // own "My AI Chat", CoachView's copy) don't pass anything, so this
    // falls back to the logged-in auth session's own id — same person,
    // just resolved a different way, so persistence works for all three
    // without having to thread a new prop through call sites that don't
    // have a client-style id on hand.
    const [chatUserId, setChatUserId] = useState(userId);
    useEffect(() => {
      if (userId) { setChatUserId(userId); return; }
      if (!sb) return;
      sb.auth.getSession().then(({ data }) => {
        setChatUserId((data && data.session && data.session.user && data.session.user.id) || null);
      });
    }, [userId]);
    useEffect(() => {
      if (!sb || !chatUserId) return;
      // Sept 18 2026 retest fix: this used to order ascending + limit(60),
      // which returns the OLDEST 60 rows — fine for a short conversation,
      // but for anyone past 30 exchanges every reload kept showing the same
      // old beginning and never caught up to recent messages. Order
      // descending to actually get the most recent 60, then reverse
      // client-side back to chronological order for display.
      sb.from("ai_chat_messages").select("role, content").eq("user_id", chatUserId).order("created_at", { ascending: false }).limit(60)
        .then(({ data, error: err }) => {
          if (!err && data && data.length) setMessages(data.map((m) => ({ role: m.role, content: m.content })).reverse());
        });
    }, [chatUserId]);
    const [input, setInput] = useState("");
    const [sending, setSending] = useState(false);
    const [error, setError] = useState("");
    const scrollRef = useRef(null);
    const rootRef = useRef(null);
    const [panelHeight, setPanelHeight] = useState(null);

    useEffect(() => {
      if (scrollRef.current) scrollRef.current.scrollTop = scrollRef.current.scrollHeight;
    }, [messages, sending]);

    // The panel's available height depends on how much chrome is rendered
    // above it (header, trial banner — which can appear/disappear) and the
    // fixed bottomNav below. A fixed-pixel guess drifts whenever that chrome
    // changes height, letting the input row slide behind the nav — so we
    // measure the real gap instead: our own top position, minus the nav's
    // actual rendered height (which already bakes in its safe-area padding).
    // Runs once on mount plus on resize/layout changes; useLayoutEffect keeps
    // the correction invisible (applied before the browser paints).
    useLayoutEffect(() => {
      // Switching tabs never resets window scroll on its own — if the
      // PREVIOUS tab was scrolled down (e.g. Diet, which runs long), this
      // panel's own top position gets measured relative to that leftover
      // scroll offset instead of a stable starting point, under-counting
      // the space above it. That inflated the computed height enough to
      // push the greeting message and disclaimer off the top of the page,
      // with only the input (further down the now-too-tall panel) still
      // in view — exactly the "blank AI Chat" Jimmy hit after scrolling
      // down on Diet first. Snap to the top before measuring so `top`
      // below is always relative to the same known point.
      window.scrollTo(0, 0);
      function recompute() {
        if (!rootRef.current) return;
        const top = rootRef.current.getBoundingClientRect().top;
        const navEl = document.querySelector("nav");
        const navHeight = navEl ? navEl.getBoundingClientRect().height : 66;
        const next = Math.max(280, Math.round(window.innerHeight - top - navHeight - 8));
        setPanelHeight((prev) => (prev !== next ? next : prev));
      }
      recompute();
      window.addEventListener("resize", recompute);
      let ro;
      if (window.ResizeObserver) {
        ro = new ResizeObserver(recompute);
        ro.observe(document.documentElement);
      }
      return () => {
        window.removeEventListener("resize", recompute);
        if (ro) ro.disconnect();
      };
    }, []);

    async function sendMessage(text) {
      if (!text || sending) return;
      if (!sb) { setError("Backend not configured yet."); return; }
      setError("");
      const nextMessages = [...messages, { role: "user", content: text }];
      setMessages(nextMessages);
      setInput("");
      setSending(true);
      try {
        const history = nextMessages.slice(-10).map((m) => ({ role: m.role, content: m.content }));
        const clientContext = injuries.length ? { injuries: injuries.map((r) => ({ bodyPart: r.body_part, severity: r.severity, note: r.note })) } : null;
        const { data, error: err } = await sb.functions.invoke("ai-chat", { body: { message: text, history, clientContext } });
        if (err || !data || data.error) {
          setError("Couldn't reach the AI chat — it looks like it isn't set up yet (see the setup guide).");
        } else {
          setMessages((prev) => [...prev, { role: "assistant", content: data.reply }]);
          // Persist both sides of this exchange so the conversation survives
          // a tab switch/reload — best-effort; a failed insert here (table
          // not migrated yet, RLS not set up) shouldn't break the chat
          // itself, it just won't be remembered next time.
          if (chatUserId) {
            sb.from("ai_chat_messages").insert([
              { user_id: chatUserId, role: "user", content: text },
              { user_id: chatUserId, role: "assistant", content: data.reply }
            ]).then(() => {});
          }
        }
      } catch (e) {
        setError("Couldn't reach the AI chat — it looks like it isn't set up yet (see the setup guide).");
      }
      setSending(false);
    }
    function handleSend() { sendMessage(input.trim()); }
    // Sept 15 2026, Jimmy: app walkthrough — the empty chat (just the
    // greeting bubble) left a huge blank gap above the input with nothing
    // guiding a first-time tap. A one-tap row of real, on-brand prompts
    // (mirrors what the greeting text itself says: training, nutrition,
    // how to use the app) fills that space and gets someone talking to it
    // immediately instead of staring at a blank box wondering what to ask.
    // Only shown before the conversation actually starts (messages.length
    // === 1 is just the canned greeting) — it should never linger once a
    // real back-and-forth is underway.
    const SUGGESTED_PROMPTS = isTrainer
      ? [
          "Build a 4-week hypertrophy block for a beginner client",
          "How should I structure a deload week?",
          "How do I assign a program to a client in JimFit?",
          "Explain progressive overload to a new client"
        ]
      : [
          "Build me a beginner leg day",
          "How much protein should I eat to build muscle?",
          "How do I log a workout in JimFit?",
          "Explain progressive overload"
        ];

    // Fallback (used only for the very first frame, before the layout
    // effect above measures the real gap) clears a typical header and
    // reserves roughly a nav-bar's worth of space at the bottom.
    return e("div", { ref: rootRef, style: { display: "flex", flexDirection: "column", height: panelHeight != null ? `${panelHeight}px` : "calc(100dvh - 220px - 66px - env(safe-area-inset-bottom, 0px))" } },
      e("p", { style: { ...styles.demoNote, marginBottom: injuries.length ? 4 : 10 } },
        isTrainer
          ? "AI-generated — a useful starting point for programming and coaching questions, but always apply your own judgment for a client's injuries, medical conditions, or specific program."
          : "AI-generated — helpful for general questions, but always double-check anything about an injury, medical condition, or your specific program with your coach."
      ),
      !isTrainer && injuries.length > 0 && e("p", { style: { ...styles.demoNote, marginBottom: 10, fontStyle: "italic" } },
        `This chat knows about what's on file: ${injuries.map((r) => `${r.body_part} (${r.severity})`).join(", ")}.`
      ),
      e("div", { ref: scrollRef, style: { flex: 1, overflowY: "auto", display: "flex", flexDirection: "column", gap: 10, paddingBottom: 10 } },
        messages.map((m, i) => e("div", {
          key: i,
          style: {
            alignSelf: m.role === "user" ? "flex-end" : "flex-start",
            maxWidth: "85%",
            background: m.role === "user" ? C.brand : C.card,
            color: m.role === "user" ? C.brandInk : C.ink,
            border: m.role === "user" ? "none" : `1px solid ${C.cardBorder}`,
            borderRadius: 14,
            padding: "10px 13px",
            fontSize: 14,
            lineHeight: 1.45,
            whiteSpace: "pre-wrap"
          }
        }, m.content)),
        messages.length === 1 && !sending && e("div", { style: { display: "flex", flexWrap: "wrap", gap: 8, marginTop: 4 } },
          SUGGESTED_PROMPTS.map((p) => e("button", {
            key: p, type: "button", onClick: () => sendMessage(p),
            style: { ...styles.browseChip, flexShrink: 0 }
          }, p))
        ),
        sending && e("div", { style: { alignSelf: "flex-start", ...styles.demoNote } }, "Thinking…")
      ),
      error && e("div", { style: { ...styles.errorBanner, margin: "0 0 8px" } }, e(Icon, { name: "x", size: 13, color: C.critical }), error),
      e("div", { style: { display: "flex", gap: 8 } },
        e("input", {
          style: { ...styles.inputEllipsis, flex: 1 },
          placeholder: isTrainer ? "Ask about programming, coaching, or the app…" : "Ask about training, nutrition, or the app…",
          value: input,
          onChange: (ev) => setInput(ev.target.value),
          onKeyDown: (ev) => { if (ev.key === "Enter") handleSend(); }
        }),
        e(VoiceMicButton, { title: "Ask by voice", onTranscribed: setInput }),
        e("button", { style: { ...styles.saveBtn, width: "auto", marginTop: 0, padding: "0 16px", opacity: sending ? 0.6 : 1 }, disabled: sending, onClick: handleSend }, "Send")
      )
    );
  }

export { AiChatPanel };
